### ISSUE TITLE
Unique user id - what's the index: username or email?

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1012]
@childsb, @EldonReturn

See https://github.com/maqetta/maqetta/commit/583ffe2ddde48edea67df6e9240ff389cfb8a92b#commitcomment-587709

We need to have a formal decision about what's the "index" on our servers (i.e., a guaranteed unique ID for each and every user). Username? email?

Then we need to do a code review to make sure our code enforces uniqueness.

**Comment by peller** [comment]
I thought we were going to go with username == email

**Comment by JonFerraiolo** [comment]
If I remember correctly, we were looking at username being the unique ID that we use for indexing, and most of the time we will use the user's email as their username, but technically those are separate fields and username is the unique ID. But I'm not sure my memory is correct.

**Comment by waynevicknair** [comment]
FYI: In Joomla user management email addresses MUST be unique. So in the 'maqetta.org' case, we will need to impose that restriction in addition to the any other uniqueness criteria.

**Comment by waynevicknair** [comment]
I recommend email address be the unique identifier. If there are no strong objections, let's move this forward. 
@JonFerraiolo ? @jhpedemonte ?

**Comment by jhpedemonte** [comment]
Yes, email address.  Most other web apps also use email, at least recently.  Sometimes they also ask for a user name or "nickname", which is displayed instead of the email address (either for privacy or brevity).

**Comment by childsb** [comment]
We should internally generate this and NOT use the user information both from a design standpoint and also it's what orion's doing.  If we use Orion for authentication, we'll need to use their mechanism anyways.

From design standpoint, there may be instances when email address is duplicated (example cloud hosted: user has multiple userNames.. one for his consulting, and one for his volunteer service or similar..)  

Orion calls this UID for cookie/ref purpose.

**Comment by jhpedemonte** [comment]
Ah, good point, Brad. Sounds good to me. Also, allows for user to change email address without issue.

**Comment by JonFerraiolo** [comment]
Actually, I disagree with the comment that we should use email addresses. Exclusive of Orion (I didn't fully understand what Brad means above), here is what I think is the best way to go: 
- Our code maintains separate fields for: (a) user_name (e.g., "AwesomeOne"), (b) user_email (e.g., harrysmith@gmail.com), (c) user_real_name (e.g., Harry Smith)
- We use user_name as our "index" and therefore require that user_name be unique for a particular site
- But in most installations of Maqetta, we set up the registration and login screens so that user_name===user_email

I'm pretty sure that's how Phil set up our code originally. If you look at the default welcome screen, that's how he architected it. 

Joomla, Wordpress, and Mediawiki also by default has a separate user_name from user_email.  We overrode the Joomla defaults at Maqetta.org by customizing the PHP in order to equivalence user_name===user_email, but there will be a small percentage of sites that don't want to use emails as user names. Some major web properties such as Twitter have been successful where user names are not email addresses. Easier to support it now than try to figure out how to deal with that requirement after painting ourselves into a corner by forcing email addresses.

**Comment by waynevicknair** [comment]
Joomla will not support multiple users with the same email address. Whatever other uniqueness requirements we introduce to Maqetta, any Joomla deployment of Maqetta must make the email address associated with the user name immutable. We chose to modify Joomla sign-up forms to force email address to be assigned to user name also; that's two separate fields assigned the exact same value. We made this change in reaction to limitations of the Maqetta plugin model and the fact that Joomla does not publish user management REST APIs. The change was in support of the review and commenting feature which needed the email address in order to function. With the email address as the user name (and accordingly the user workspace directory name) we were able to pull the email address off of the filesystem when instantiating a User object. 

This above fact is orthogonal to the which-should-be-unique question posed by this issue. I agree with Jon's recommendation in the above comment. The good news is: we need only do a consistency check on the code to ensure that we are still using "username" as Maqetta's index.

**Comment by JonFerraiolo** [comment]
Pushing to M5

**Comment by jhpedemonte** [comment]
-> M6

**Comment by waynevicknair** [comment]
it's user name.
