### ISSUE TITLE
Test ability to access HTML files from other user workspaces

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1060]
@childsb, @billreed63

This issue is a testing issue. After testing, maybe other issues will be created if problems are discovered.

@billreed63 and @jonferraiolo were trying to access files from each other's workspace, such as http://maqetta.org:55556/maqetta/user/billreed@us.ibm.com/ws/workspace/project1/file4.html and http://maqetta.org:55556/maqetta/user/jferrai@us.ibm.com/ws/workspace/project1/SwitchTheme2.html, and sometimes could access the files and other times not. In one case, we couldn't access another workspace file if logged in, but after logging out, then access worked.

**Comment by JonFerraiolo** [comment]
@billreed63, I reassigned this to you for you to try to reproduce. I'm not closing this quite yet because we really did notice something is amiss and maybe you will find a way to reproduce.

I tried every combination I could envision and I could always get to files in the jferrai@us.ibm.com workspace when simulating other users/machines by using different browsers. I tried pretending I was a different user already logged in and a different user not logged in. I also tried to break thing by involving the "other user" in a review session.

**Comment by billreed63** [comment]
I can still reproduce on maqetta.org but that is preview 3 code. I can not reproduce on my dev system preview 4 code base.
So maybe it was fixed... 

I guess we should leave this open and test it again on maqetta.org once preview 4 is deployed for testing..

**Comment by billreed63** [comment]
This is what I am seeing today...
Run Maqetta multiple users

On chrome browser
1) Create "user1"
2) Create file1.html
3) DnD button
4) Preview in browser

On FF browser
5) Create "user2"
6) Create file1.html
7) DnD calendar
8) Preview in browser

9) from your chrome "preview in browser" tab copy url
10) create a new tab in you FF browser and paste the URL

Notice that the file displayed in your browser is user2 's file1.html (the calendar instead of the button", 

11) click on the maqetta tab in the FF browser and log out.
12) refresh the tab from step 10, now you will see user1 's file1.html (the button)

**Comment by childsb** [comment]
The user workspace code path wasn't looking at the path element, instead just looking at the logged in user.

fixed with #5c50eb83049c159342d9aa82e4dc380d98a297c1
