### ISSUE TITLE
TabContainer, then LABEL: ContentPane_0 id already registered

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1082]
I'm guessing this is a regression due to one of @peller's recent fixes.
- New HTML File
- Add a TabContainer, accept default tabs
- Add a `<label>` inside of TabContainer, accept "Label" as text for the label

Result=> dijit/dijit:15Uncaught Error: Tried to register widget with id==ContentPane_0 but that id is already registered

**Comment by peller** [comment]
nothing comes to mind (any specific checkins you're thinking of?) but I'll check it out

**Comment by peller** [comment]
In ModifyRichTextCommand, widget.getContainerNode is returning null, so the entire document is getting reparsed -- which of course is bad, since the widgets already exist (are not detached)  I think the intent of this code is to only reparse the contents of the widget (widget.domNode and children)

Seems to be the getAllowedChild logic here 7aa9bf9f    Is this appropriate for getContainerNode?  Shouldn't the container always be returned?

@billreed63

**Comment by jhpedemonte** [comment]
Well, **ContentPane** still defines `"allowedChild": "ANY"`, so it should return its `containerNode`.  I'll debug this later.

**Comment by peller** [comment]
it's not supposed to get to the **ContentPane** at all.  It's calling getContainerNode on the LABEL.  The only reason it's getting to the other (parent) widgets on the page is because LABEL's getContainerNode returns null, triggering a reparse of the entire page.

**Comment by jhpedemonte** [comment]
I added a null check to the code, since non-container widgets will return `null` from `getContainerNode()`.

But this code doesn't really make sense to me.  First, **ModifyRichTextCommand** is very similar to **ModifyCommand** (already opened a bug so we can refactor and merge the two).

Here's a bit of code from `ModifyCommand.execute()`:

``` javascript
        if(this._context){
            this._context.attach(newWidget);
            newWidget.startup();
            newWidget.renderWidget();
        }
```

And here's what `ModifyRichTextCommand` does at the same location:

``` javascript
        if(this._context){
            this._refresh(newWidget);
        }
```

`ModifyRichTextCommand._refresh()` looks like this:

``` javascript

    _refresh: function(widget){
        // refresh the page designer, sometimes the widgets are not redrawn for children
        // we need the timer to let the model catch up to prevent corruption.

        // this is from davinci.ve.Context. _processWidgets line 584
        var dj = this._context.getDojo(),
            containerNode = widget.getContainerNode();
        dj["require"]("dojo.parser");
        dj.parser.parse(containerNode);
        this._context.attach(widget);
        widget.startup();
        widget.renderWidget();
        this._context._attachChildren(containerNode);
    }
```

So the 2 files do similar things, except that **ModifyRichTextCommand** runs the Dojo parser over the contents of the affected widget.  Why?  Are we supporting entering HTML with Dojo widgets in the **Smart Input** field?

First, this is completely Dojo specific and wouldn't work for any other toolkit.  Also, this just runs the Dojo parser, it doesn't try to load widget dependencies -- so it's open for failure.

My proposal is to remove this from ModifyRichTextCommand and just do what ModifyCommand does in this case.

**Comment by peller** [comment]
I think getContainerNode used to return widget.domNode for all widgets prior to 7aa9bf9.    Is it possible that this checkin changed the behavior and that this could have side effects elsewhere?

**Comment by jhpedemonte** [comment]
Prior to my commit 7aa9bf9ff116d88a4357ccdfdeaaf6f3182aa53c, `getContainerNode` used to return `widget.domNode` for HTMLWidgets, all except for `input`, `img`, `hr`, `br`, and `script`.  Not sure how those were decided, but if any of those are added to the page, they would break in this code as well.

In that code, someone (I think it is was Jon) added a **FIXME** note about adding some sort of `isContainer` call and some way to figure out which children were allowed.  We already have this, so I made use of the `allowedChild` property.

In this case, it means that `getContainerNode` returns `null` for LABEL, since it isn't a container.

If we need to get the widget's **domNode**, then we can use a different API.  Or just directly access `widget.domNode`.

Either way, I still think the code in ModifyRichTextCommand is wrong.

**Comment by peller** [comment]
I didn't think container node meant widget container in the dijit.Container sense.

**Comment by JonFerraiolo** [comment]
@jhpedemonte - is this fixed? I couldn't reproduce the bug just now
