### ISSUE TITLE
Error when hitting 'Enter' key in new html file dialog

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#1086]
Select "New HTML Page", which brings up a dialog.  If you click on the **Create** button with the mouse, it works fine.  However, if you hit the **Enter key** on your keyboard, then the dialog disappears and you break into the debugger.  Might be related to Dojo 1.7 upgrade.

**Comment by peller** [comment]
looks like it's got some events firing after the dialog has been destroyed.  the exception itself is harmless.  there's nothing else on the stack.

**Comment by JonFerraiolo** [comment]
@childsb, @jonferraiolo

**Comment by peller** [comment]
@childsb

The dialog is getting closed twice, once by onClose() again by onSubmit()  This might have something to do with the unusual arrangement of having a widget inside the dialog call onClose to trigger a dialog close, rather than calling hide() directly.  I think what you want to do is let the submit close the dialog, and remove the call you're making to onClose, but I think this breaks the way the action is currently wired to the dialog. 

The exception has no side effects. There's nothing else on the stack.  It just tries to do the fade out animation twice, and the second time, it fails.

**Comment by jhpedemonte** [comment]
I fixed the error in `_checkValid()`.  However, now when I hit **Enter** key to create file, the file is created but **New File** dialog remains on screen.  Works correctly if I click **Create** button.  @peller, you were recently looking at the dialog dismissal -- do you have any idea what is going on here?

**Comment by jhpedemonte** [comment]
So dialog remains because when hitting enter, form is not submitted (it is when clicking on Create). @peller know of an easy way to get the Dialog reference and submit it?

**Comment by jhpedemonte** [comment]
Last commit:  I just simulated a click event on the Create button.  This ensures that, when hitting ENTER, the file is created and the dialog is dismissed.

This code should all go away when we redo dialogs (issue #?).
