### ISSUE TITLE
M3 -> M4 migration scripts

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1123]
@jhpedemonte, @waynevicknair, @childsb, @billreed63, @peller

Assigning to @waynevicknair by default, but given that the big change from M3->M4 is with themes and theme sets, @billreed63 will have to be involved.

@peller: will the changes to AMD require anything in the M3->M4 migration script?

**Comment by peller** [comment]
@billreed63 suggested we might need to migrate the dojo-theme-editor.html templates to pick up the AMD-style declarations.  I suppose our stock themes would get fixed by reference, but any cloned themes would have a copy of the old dojo-theme-editor code with non-AMD declarations, right?  It's possible we could put some sort of sniffing code in to load old themes in synch mode.  Is it even worth doing this migrations?  How many cloned themes are there?

**Comment by waynevicknair** [comment]
dropped scripts into 'internal' repository on commit 0e2554595a68661fabcaa088e2f6687b6e61360e
