### ISSUE TITLE
Source editor comes up clipping off first 2 chars

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1242]
@waynevicknair

Using lab9 server. Seeing this with both Win/FF8 and Win/Chrome.
- New HTML File
- immediately go into split view

Result: leftmost characters are clipped. See http://i42.tinypic.com/24gzk.png

**Comment by peller** [comment]
yeah, it's a bug with the line number ruler.  It's not actually clipped.  The scrollbar just isn't all the way to the left.  Need to see if I can recreate it without Maqetta.  Easiest workaround is to remove the line number ruler.

UPDATE: the bug was unrelated to the line number ruler.  The bizarre logic we have in switchingEditorView which creates and destroys the editor a number of times, plus some timeouts make this very hard to track down, but somehow we got in a situation in textView where clientWidth was negative (the source pane was width 0 with a margin) because the page layout had not yet been recomputed when the editor was initialized.  The logic to set the horizontal scroll (pixelX) fails in this case to establish a position of 0.

**Comment by peller** [comment]
problem still exists in standalone editors (e.g. when opening js and css files)

**Comment by peller** [comment]
I'm not sure why this regressed, but the workaround was suspect to begin with.

**Comment by peller** [comment]
@JonFerraiolo: The bug causing this appears to have been fixed on the Orion trunk.  Integration with their I20111218-2230 build corrects the problem: ca5afc8592348c493435864450c405adac8280aa   Should we merge this for M4?

**Comment by JonFerraiolo** [comment]
At first when I saw the number of diffs, I felt no way should we include these changes, but when I studied the code, it looks like these are important bug fixes. I'll assume it will be reasonably easy to back out the merge if we see fatal problems, and therefore I'll say yes let's merge in the fixes.
