### ISSUE TITLE
Exception dragging any widget on to the canvas

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#1244]
regression seems to occur for me at a0c0ee74d35672999670d3a9a3d3d79627bed311

```

davinci/ve/metadata:175Uncaught TypeError: Cannot read property '$providedTypes' of undefined
getLibraryForTypedavinci/ve/metadata:175
metadata.queryDescriptordavinci/ve/metadata:623
declare.constructordavinci/ve/tools/CreateTool:25
adojo/_base/declare:325
declare.onDragStart.dojo.create.classNamedavinci/ve/palette/Palette:437
runFactorydojo.js:980
execModuledojo.js:1106
contextRequiredojo.js:698
reqdojo.js:124
declare.onDragStartdavinci/ve/palette/Palette:440
declare._createItem.node.tooltip.Tooltip.labeldavinci/ve/palette/Palette:423
hitchdojo/_base/lang:155
hitchdojo/_base/lang:155
target.(anonymous function)dojo/aspect:181
dojo.declare.onMouseMovedavinci/ui/dnd/DragManager:96
hitch
```

**Comment by peller** [comment]
``` js
                    var lib = libraries[name];
                    if (lib.$wm.$providedTypes[type]) {
```

`name` is "maqetta", `lib.$wm` is undefined

**Comment by jhpedemonte** [comment]
I can't reproduce this.

I understand why it would be failing -- "maqetta" is a non-widget library and therefore `$wm` wouldn't be set.

However, when dragging widgets from palette, `name` should never be `maqetta`.  `name` will be the library ID for whichever widget is being dragged.  Since "maqetta" has no widget in the palette, it won't go down that path.

So while we could put a check here, I think it's much more important to figure out why you are getting "maqetta" as the `name` here.  I have yet to see this issue.

**Comment by jhpedemonte** [comment]
cc @JonFerraiolo

**Comment by jhpedemonte** [comment]
Oh, I see.  I misunderstood the failure case.  It's not that the Palette is saying the user is trying to drop a widget from the library "maqetta" (which can't be the case).  Rather, this bit of code is looping over all libraries looking for a type.

I was able to reproduce by downloading the latest build.  Not sure why it doesn't show up when I'm running from source.

**Comment by peller** [comment]
FWIW, I'm seeing it from source.

**Comment by jhpedemonte** [comment]
The reason I wasn't seeing it from source is that the order of the libraries is different for me.  The issue occurs when the function is called looking for the **html.body** widget.  In my case, the **html** library comes before the **maqetta** lib.  In the failing case, **maqetta** lib comes first and runs into the null value.
