### ISSUE TITLE
preview mobile pages exception in dojo

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#1249]
When I attempt to preview a mobile page I get the following exception from dojo
Uncaught Error: Tried to register widget with id==general but that id is already registered

I have track this down to dojox.mobile does not like the amd format for modules

this code works:

``` html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
    <head>
        <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,minimum-scale=1,user-scalable=no"/>
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <title>Heading</title>
        <link href="../themes/iphone/base.css" rel="stylesheet">
        <link href="../themes/iphone/TabBar.css" rel="stylesheet">
        <link href="../themes/common/domButtons.css" rel="stylesheet">

<script type="text/javascript" src="../../../dojo/dojo.js"  data-dojo-config="'async':false,'parseOnLoad':true"></script>


        <script language="JavaScript" type="text/javascript">
             dojo.require("dojox.mobile");          // This is a mobile app.
            //dojo.require("dojox.mobile.deviceTheme");
            dojo.require("dojox.mobile.parser");    // This mobile app supports running on desktop browsers
            dojo.require("dojox.mobile.compat");    // This mobile app uses declarative programming with fast mobile parser
            dojo.require("dojox.mobile.TabBar"); 

        </script>
    </head>
    <body style="visibility:hidden;">
        <div id="general" dojoType="dojox.mobile.View" selected="true">
            <h1 dojoType="dojox.mobile.Heading" back="Settings" moveTo="settings">General</h1>
        </div>


    </body>
</html>

```

while this code does not:

``` html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
    <head>
        <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,minimum-scale=1,user-scalable=no"/>
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <title>Heading</title>
        <link href="../themes/iphone/base.css" rel="stylesheet">
        <link href="../themes/iphone/TabBar.css" rel="stylesheet">
        <link href="../themes/common/domButtons.css" rel="stylesheet">

<script type="text/javascript" src="../../../dojo/dojo.js"  data-dojo-config="'async':false,'parseOnLoad':true"></script>
<script type="text/javascript">
require(["dijit/dijit"]);
require(["dojox/mobile"]);
require(["dojox/mobile/parser"]);
//require(["dojox/mobile/deviceTheme"]);
require(["dojox/mobile/compat"]);
require(["dojox/mobile/TabBar"]); 
</script>

    </head>
    <body style="visibility:hidden;">
        <div id="general" dojoType="dojox.mobile.View" selected="true">
            <h1 dojoType="dojox.mobile.Heading" back="Settings" moveTo="settings">General</h1>
        </div>


    </body>
</html>

```

**Comment by billreed63** [comment]
The issue seems to be the 

```
require(["dijit/dijit"]);
```

if I comment out that line in the mobile all is well

**Comment by peller** [comment]
@JonFerraiolo @jhpedemonte

So it boils down to a conflict between the two parsers, dojo/parser and dojox/mobile/parser.  Introducing require(["dojo/parser"]) into one of the dojox.mobile tests produces the same error.  Not surprising, since each parser runs if config.parserOnLoad is truthy, and they can't instantiate the same widgets.

I introduced the dijit/dijit and dojo/parser requires recently (7ece3f90) which likely caused the regression.  dijit/dijit, an optimized layer for Dijits, includes dojo/parser, but that's not really the problem.  With AMD in Dojo 1.7, we now need to explicitly include dojo/parser.  The code that autoloaded dojo/parser is deprecated with the old synchronous Dojo loader.  While we could try to use one parser for dijit and another for mobile, that's not trivial to do, and there's nothing to prevent both types of widget from coexisting, so using metadata dependencies doesn't seem to work either.

The easiest way around this, which I recommend for M4, is to remove the dojox/mobile/parser reference.  We won't get the slimmest possible dojo/mobile profile, but we can document how to manually change the require to achieve it.  In the future, we could also make some sort of Dojo preference for which parser to use.
