### ISSUE TITLE
Add theme set selection to New File dialog

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#1259]

**Comment by billreed63** [comment]
@JonFerraiolo The new HTMLFIleOptions appears to be more complex than I excepted.

1) what is displayed when the user clicks on the pencil? 
   a) The theme switching dialog
   b) The theme set management dialog

2) If the user choices a mobile composition style, do we only show theme sets and mobile themes in the themes or theme set dialog? Same question for other composition styles?

3) If the user choices mobile, iphone, custom.css what do we set the other devices to in the themeMap?

I think we need to simplify the functionality of this dialog:
- When the user clicks on the pencil the get the theme set management dialog (add/edit/delete theme sets)
- The user can select from theme sets or themes that support that composition style 
- If the user choice a theme instead of a theme set it applies to all devices (if they pick android, they get themeMap=[.*, android]

**Comment by JonFerraiolo** [comment]
> 1) what is displayed when the user clicks on the pencil? 
>  a) The theme switching dialog
>  b) The theme set management dialog

Exact same dialog user would see when they click on the "switch theme" button

> 2) If the user choices a mobile composition style, do we only show theme sets and mobile themes in the themes or theme set dialog? Same question for other composition styles?

Exact same dialog user would see when they click on the "switch theme" button :-)

> 3) If the user choices mobile, iphone, custom.css what do we set the other devices to in the themeMap?

The theme switching dialog allows the user to choose custom.css as the theme for all devices or for a specific device, doesn't it?
So, when in the theme switching dialog, (Case A) if the user chooses custom.css for all devices, then custom.css should apply to all devices.
However (Case B), if the user chooses custom.css only for iphone, then custom.css should only apply to iphone and no other devices should be affected.
When returning to the New HTML File dialog, I'm not 100% sure what should show for these two cases because I've had some memory decay.
But if I'm remembering all of this correctly, for Case A, then show custom.css in New HTML File dialog, but for Case B, show "(device-specific)" or whatever. 
There is also a Case C where the user chooses one of the theme sets they he has created. For this case, the New HTML File dialog should show the theme set.

> I think we need to simplify the functionality of this dialog:
> - When the user clicks on the pencil the get the theme set management dialog (add/edit/delete theme sets)
> - The user can select from theme sets or themes that support that composition style 
> - If the user choice a theme instead of a theme set it applies to all devices (if they pick android, they get themeMap=[.*, android]

How about my proposal above?

**Comment by billreed63** [comment]
The code is done. If any bugs are found open new issues for them to insure all bugs are fixed
