### ISSUE TITLE
New Folder parent folder is not editable

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#1289]
Textbox control looks like it should be editable.  The contents are not context sensitive and always seem to point to the top of the project, e.g. ./project1 (should not have the "./")  How would I create nested folders?

**Comment by JonFerraiolo** [comment]
@peller, I'm not sure what this bug is about. Are you talking about the New Folder command on the top menu bar or the New Folder command on context menu of File palette or the New Folder button on New HTML File dialog, or something else? And which textbox control in particular is not editable? The parent folder textbox on the New HTML File dialog is editable when I tried it just now.

**Comment by peller** [comment]
You raise a good point... we have at least one too many new folder commands!  But as far as I can tell, all three point to the same dialog code, and for all three I am able to select text but not alter the contents of the parent folder textbox.  Note that from New HTML File you must first click on the New Folder button associated with the turndown knob and tree to see this.  I'm testing in Chrome.

**Comment by childsb** [comment]
@peller Issue #1280 is related to this, and i checked in fix d5400287fa9075619cb991e5e7c2d611d94cc027 .

This allows user to select a folder in the explorer tree and the "parent folder" in the "new folder dialog" is properly populated.  This is true for both locations of the "New Folder" dialog.

The read only of the parent is intentional (to save cluttering with a Tree control) and I didn't want users just free hand typing something possibly invalid.

The above fix should now allow full nested folders.  If we want to redesign the "new folder dialog" with a tree control / similar to new file I think we should push that off to M5.

**Comment by peller** [comment]
Yes, now with your fixes the parent is now populated to something other than the root, which makes it possible to create nested folders.  That's good.

If the parent is read only, the data shouldn't be rendered in a (readonly) textbox.  It should be plain text IMO... just put it in a div?  I think this part should still be fixed.  It's just frustrating to use an editable UI which makes the user think they can edit, but no indication that it's read only except that they can't type.  I don't think the whole tree control thing is necessary.  The current dialog otherwise seems fine for now.

The only other nitpick is that if I select a folder in a dialog and hit new folder, I'd expect the new folder to get nested in the selected folder.  I just checked one Mac application and it works this way, but maybe there's no standard on this.

**Comment by JonFerraiolo** [comment]
It would be better if the readonly textbox was styling somehow to indicate it is readonly. We should solicit UI expert guidance on this, but OK for M4 to leave as is or do something simple such as set disabled='true' on the textbox so that its rendering is consistent with its actual behavior. But this is lower priority than almost everything else in the bug base.

**Comment by peller** [comment]
yeah, like take away the border!  Just use a div.  It's static text.  I really don't think we should leave this as-is for M4.  The current UI is sure to frustrate users.

**Comment by JonFerraiolo** [comment]
Also see #1376

**Comment by childsb** [comment]
This should be resolved from last milestone's re-write of the New File Dialog.

Currently parent folder is read-only drop down with a list of currently selected folder and a history of past selected folders.

**Comment by peller** [comment]
yes, but there's also the New Folder dialog
