### ISSUE TITLE
Calendar inline edit: only show today's date

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#129]
Inline edit for calendar now shows a complete date string, such as:

Sun Dec 19 2010 00:00:00 GMT-0800 (Pacific Standard Time)

We should show 2010-12-19 instead because the Calendar widget only deals with
dates and not times and because we want to show the user an example date that
the browser will be able to parse reliably.

Implementing this might be more difficult that you would think because I18N is
a four-letter word. What I would do is leverage all of Adam's hard work in Dojo
in this area and generate the date string for inline edit as follows:

dojo.require("dojo.date.locale");
...
var currentDate = new Date();
var datestring = dojo.date.locale.format(currentDate, {selector:"date",
datePattern:"yyyy-MM-dd"});

You could also achieve the equivalent of yyyy-MM-dd without bringing in
dojo.date.locale, but you would need a utility to ensure there were leading
zeroes on the month and day fields.

**Comment by peller** [comment]
no need for i18n here... the timestamp format is culturally-independent.  Instead of dojo.date.locale.format, use the simpler dojo.date.stamp.toISOString, or perhaps just call ES5 date.toISOString().substring(0,10)  We need to make sure that the properties panel does the same to serialize and consume the ISO format.

**Comment by billreed63** [comment]
Calendar no longer supports inline edit, user now uses the Widget Specific - Value input box
