### ISSUE TITLE
focus box clipped by viewport

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#1325]
go into split view (horizontal bar) and make the design view very short... shorter than a calendar widget.  Now drag a calendar widget on to the page.  Note that the focus box has the bottom to align with the bottom of the view, not the bottom of the widget.  The bottom resize handle is in the middle of the widget.  The focus box should go off screen.  The code that makes the focus box fit in view should only work for 100%x100% widgets, I think.

**Comment by JonFerraiolo** [comment]
I'm not sure about what's the right approach here, I'd have to play around with it a bit, but here go some thoughts. 

Down the road, we will probably used a fixed size for BODY (eg 1024x768) instead of our current "scroll to infinity and beyond" approach. In that case, we should back off selection in case it would extend beyond the 1024x768 bounds.

For the current scenario, however, things might not be so simple. We don't actually have a particular BODY size, and instead the 100%/100% makes the BODY group to fit available space, except when you have too many widgets, when BODY is bigger than available space. For the current situation, to fix this bug it might be easier and better to register a resize event handler on the inner iframe (assuming browsers let you do that) and call updateFocus() with the resize events.

**Comment by peller** [comment]
I'm not sure I see the issue here.  I was just speculating about what code was causing this bug.  This is for the non 100%x100% case.  The widget extends off screen.  The focus box should not be bound by the visible viewport, but should extend out of view, and the nobs should align with the actual widget, whether in view or not.

**Comment by JonFerraiolo** [comment]
I dug in and here's the deal. I had added logic to Focus.js to prevent (really ugly) scrollbars from appearing in mobile UIs whenever Views were selected. My logic checked to see if the selection was bigger than the viewport, and if so, pulled the selection so it was no bigger than the viewport. But as pointed out in this issue, there was a side effect when selecting a widget that extended off the bottom or right.

I found a fix (f71a8e5). Instead of using BODY.offsetWidget/Height, instead use HTML.scrollWidth/Height.
