### ISSUE TITLE
'undefined' error in path when not authenticated

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#1329]
Log in to lab9, create a file called file1.html, save it.

Clear cache/restart browser and reenter lab9.  The workbench will attempt to load but fail with errors like:

```
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
http://lab9.austin.ibm.com:50010/maqetta/user/undefined/ws/workspace/project1/file1.html
```

rather than give some visual indication that the user needs to log in or bouncing the user to an authentication page.  note the 'undefined' in the url, which implies some earlier error which probably should have halted execution and notified the user.

**Comment by jhpedemonte** [comment]
Well, this worked fine for me for the base build, but not internal.  There, when reloading the page, I get an error in Workbench and only the header of the page shows up.  There is no content in `<div id="mainBody">`.

The issue comes about due to the code in `davinci.Workbench.run()`:

```
run: function() {
    this._initKeys();

    this._baseTitle = dojo.doc.title;

    this._initializeWorkbenchState();

    var perspective= davinci.Runtime.initialPerspective || "davinci.ui.main";
    this.showPerspective(perspective);
```

Basically, the `mainBody` seems to be generated in `showPerspective()`.  However, `_initializeWorkbenchState()` tries to create an editor for the file that was left open when leaving the app last time.  But there is no mainBody, so there is no place to put the new editor.

Not sure why I would be running into this now.

**Comment by jhpedemonte** [comment]
Hmm, M3 works fine, and that's because `_initializeWorkbenchState()` used to happen much later in `run()`.  For some reason, it was moved up before `showPerspective()`, causing this issue.

**Comment by jhpedemonte** [comment]
Brad had made a change earlier which moved `_initializeWorkbenchState()`, leading to the issues I was seeing.  I put it back in its correct place.

**Comment by jhpedemonte** [comment]
Well, now that I fixed my error, I cannot recreate @peller's error (on a local build).
