### ISSUE TITLE
"Clipboard permision denied" when cut/copy in source editor

### ISSUE THREAD

**Issue by childsb** [maqetta/maqetta#1400]
1) open sample1.html
2) select some text
3) use apple-x to cut.  you will see msg "Permision denied clipboard" under firefox
4) same error when you paste

it does look like the copy/paste still happens though.

**Comment by peller** [comment]
I don't see this error.

**Comment by JonFerraiolo** [comment]
I assume this bug is with the source editor. I remember from the distant past that there are (or maybe there were) security issues with cut/copy/paste on Firefox but I can't recollect the details. Maybe the exception only happens when Firebug is running? I searched about:config and the web for reminders on this issue, but no bells rang. If we can't remember, we should probably contact the Orion guys to see if they remember.

**Comment by peller** [comment]
I remember.  There was a way to programmatically hook up to the clipboard, which had all sorts of "Netscape" security restrictions, but IIUC we're talking about the OS keyboard accelerators here, which should be a native function and not trigger any JS.

**Comment by jhpedemonte** [comment]
I see this as well.  In Firefox, doing a cut of the text brings up Firebug and the debugger stops at the "offending line" in **textView.js** (orion).  So this isn't an issue if the user doesn't have Firebug installed.

This should be moved to the Orion folks for them to handle.  Removing M4 milestone.

**Comment by JonFerraiolo** [comment]
Assigned to @peller for M5 with Priority-High so that he is reminded to talk with Orion guys soon (rather than noticing this issue again a few months from now)

**Comment by peller** [comment]
Ok, there's an important step missing from the description.  You must not only be running in Firefox, and running with Firebug, but you must ask it to break on throwing an exception.  The exception in this case is caught, immediately, exactly because the Javascript handler is known to fail on Firefox without special steps taken to configure permissions.

``` js
/*
* Try execCommand first, it works on firefox with clipboard permission,
* chrome 5, safari 4.
*/
this._ignoreCopy = true;
try {
   result = document.execCommand("copy", false, null);
} catch (e) {}
```

and, as @childsb points out, the clipboard operation succeeds anyway using the system clipboard operation. There's no bug here IMO, and nothing to report to the Orion team.

**Comment by jhpedemonte** [comment]
Good point.  Closing.
