### ISSUE TITLE
Click-select on widget in source view doesn't select widget

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1435]
@peller 

Discovered using Mac/Chrome. Haven't tested other browser yet.
- New HTML File
- Add Button, Calendar, ColorPalette widgets
- Go to split view
- Try clicking on markup associated with any of the above widgets

Result=> None of the widgets get selected

**Comment by waynevicknair** [comment]
yikes! i'll dig in to this one tomorrow.

**Comment by jhpedemonte** [comment]
Wayne and I talked about this and batted around some possible fixes.  But they all impact the core of the Maqetta model.  As such, they're too risky for M4.  Pushing this to M5 and keeping priority high.

**Comment by jhpedemonte** [comment]
This issue seems to be causes by the temporary IDs which are added in our Model, but not used in the persisted source or in the Orion editor.  It seems to me that the best thing would be to **get rid of the temp IDs** altogether and instead use another syntax (XPath-like) to reference individual nodes.

**Comment by jhpedemonte** [comment]
(continuing from previous comment)

One way of uniquely referencing an element in DOM (or in our model) is to use CSS selector syntax.  One issue with this approach is that it results in the use of a lot of `:nth-child()` references.

A more compact string representation can be found in Firebug.  Inspect an element and then (in Firebug) hover over the element representation in the bar right underneath the **HTML** tab.  It'll show a string that looks like this:

```
/html/body/ol[6]/li[2]/a
```

In this case, the 3rd element (`ol[6]`) means that of all the `ol` elements which are a direct decedent of `body`, take the sixth one.  This results in a more compact and easier to read representation, but it requires it's own parser/selector.

**Comment by JonFerraiolo** [comment]
And why are temp IDs causing trouble? I don't know the code in this area, but my first thought is that it shouldn't be difficult to skip over non-persist attributes when doing the offset computations.

Note that we have a general mechanism for non-persisting attributes. Has anyone checked to see if we use it for other things than temp IDs?

**Comment by waynevicknair** [comment]
"noPersist" is only ever used in the context of "id" attributes, specifically in HTMLModel.js, _Widget.js, Context.js, and widget.js. however, it does not account for the total offset drift i am seeing at runtime.

**Comment by JonFerraiolo** [comment]
Pushed to M6 - too late to attempt this

**Comment by JonFerraiolo** [comment]
-> @jhpedemonte (so this doesn't fall through cracks)

**Comment by aerwin** [comment]
Assign to @aerwin

**Comment by aerwin** [comment]
@jhpedemonte @JonFerraiolo 

I'm brand new to this code, but in my debugging I didn't see where the temp ID's had anything to do with it. As far as I could tell, the issue was that offsets in the text editor were not being mapped back to offsets in the model. This is fixed with b51206cdd92f10b0534c213e58ba5109be4cc8ea .
