### ISSUE TITLE
Make sure sprites are used for toolbar images

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#1480]
In 8d5304a567f56e430519f45bfe8f4ed0f682203c I had to resort to using !important to apply individual gif rules over the sprite normally used by Maqetta toolbars.  All of those images should be placed in the sprite and the !important rules should go away.  It looks like Comment.css needs a lot of clean up as well.  Is all that CSS used?

**Comment by jhpedemonte** [comment]
The tool I used to create the initial [sprite image](https://github.com/maqetta/maqetta/blob/master/maqetta.core.client/WebContent/davinci/img/sprite.png) is the [CSS Sprite Generator](http://spritegen.website-performance.org/).

Since the **Comments** view is part of Review & Commenting, we should have a separate sprite image -- this allows us to load the R&C code on demand.

@JonFerraiolo

**Comment by JonFerraiolo** [comment]
The images in question are in maqetta-core-client/WebContent/davinci/review/resources/img/*. What we are doing is keeping all of the individual image files around in our repository, but creating a sprite.png file that holds all of the images together in a single image file. The runtime product only references sprite.png. 

One downside of our current approach (where we keep the separate image files and also have sprite.png) is that if we find the need to add another image, we have to add that image into the img/\* folder and also modify sprite.png. Would be good long-term is we could automate this better, but certainly not a priority for short-term.

**Comment by peller** [comment]
I take the view that our ui should settle down and that this isn't worth automating.

**Comment by doronrosenberg** [comment]
There are quite a few images that are either not used or don't exist.  I will comment out the ones that don't exist.
