### ISSUE TITLE
Property values not updated when switching theme

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#1516]
Running **Properties part 5** test, section "Multiple option changes using Background dialog on a read/write and read/only themes":

After **switching theme** back to "claro" (from "myclaro"), **none of the values** in the Properties view were **updated** (I had Button selected before switching themes).  Therefore, when following test and selecting SampleBanner.jpg again, nothing happened since that was the original value in the property field (there must be code in Properties view that only runs code if new property value is different than what was in property earlier).

@JonFerraiolo

**Comment by JonFerraiolo** [comment]
I'm pretty sure this is a dupe but I haven't found the other similar bug yet.

**Comment by aerwin** [comment]
I've also noticed in the "CSS cascade features" section of "Properties palette basic tests (part 4)" that when I follow Step 6 (to switch to "mytheme" that I have to open and close the HTML file to get Step 7 to work.

**Comment by JonFerraiolo** [comment]
I'm closing this. It looks like this issue has become a non-issue because we now deselect-all when changing themes. As a result, when you change themes, nothing is selected, so the Properties palette shows nothing, but when you then (re-)select a widget after the change theme operation (with it's deselect-all processing), the properties palette does reflect the new theme values (noticeable after opening up the cascade panel).
