### ISSUE TITLE
Need button to delete annotations

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#1519]
There is no way (that I could find) to delete annotations (text, circle, rectangle, arrow) in review & commenting.

@JonFerraiolo

**Comment by jhpedemonte** [comment]
-> M6

**Comment by JonFerraiolo** [comment]
Moving temporarily back to M5. Seems like a big usability issue. Reassigning to me to assess difficulty and risk with attempting to do something simple, such as allowing BS/DEL keys to delete currently selected annotation.

@aerwin

**Comment by JonFerraiolo** [comment]
Above commit made it so that either DEL or BS key can be used to delete an annotation. That way, Mac guys are able to delete annotations, too.

There are still keyboard focus problems. The DEL and BS keys only work sometimes because keyboard focus usually is off in the Comments palette instead of on the canvas. You sometimes have to click on the annotation a second time to put keyboard focus onto the canvas so the DEL and BS work. But fixing that is too risky, so pushing to M6.

There are also UI questions about whether we need to offer an icon somewhere, or action bar around selected annotation, so that people have an icon to use instead of just keyboard. Note that keyboard isn't an option for tablets. @jmockler

**Comment by JonFerraiolo** [comment]
Pushed back to M6

**Comment by JonFerraiolo** [comment]
-> M7 Prio High

**Comment by JonFerraiolo** [comment]
-> @aerwin

**Comment by aerwin** [comment]
@JonFerraiolo 
- BTW, I don't think any of this is working now (not even the DEL or BS key). Using Chrome on Mac, if I select the annotation (and focus is clearly in the editor), then if I hit DEL I get the browser dialog asking me if I'm sure I want to navigate away from the page.

@JonFerraiolo @jmockler 

> There are also UI questions about whether we need to offer an icon somewhere, or action bar around selected annotation, so that people have an icon to use instead of just keyboard. Note that keyboard isn't an option for tablets.  

Thoughts here? I'm guessing with the new UI design settling as it is that there should be an X button on the main toolbar with a keyboard shortcut of DEL? This would give consistency with how things are deleted from the visual page editor.

> There are still keyboard focus problems. The DEL and BS keys only work sometimes because keyboard focus usually is off in the Comments palette instead of on the canvas. You sometimes have to click on the annotation a second time to put keyboard focus onto the canvas so the DEL and BS work. But fixing that is too risky, so pushing to M6.

Hopefully, this would be resolved by adding the action to the main toolbar via `review.plugin.js` and using `keySequence` of DEL. (Though see #2997 that global DEL doesn't seem to be working.)

**Comment by aerwin** [comment]
--> Closing with above commit.

Some notes:
- Added button to CommentForm's toolbar to delete annotation. Decided to add button there (as opposed to my last proposal) since it only makes sense to delete an annotation when adding/editing a comment.
- Added logic to properly enable/disable new button
- Did some clean up with main toolbar that appears above review editor
  - got rid of extraneous separator (resulting from table actions not being filtered out based on editor)
  - made visible the review message telling user they're looking at a live application
- Etc.
