### ISSUE TITLE
Server error if try to delete new, unsaved file

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#1535]
1. Create new HTML file
2. Find file in Files palette and try to delete it and get page that says:

> Problem connecting to the Maqetta Server...
> Return to Maqetta Login
> 
> Error description:
> 
> Error: Unable to load cmd/deleteResource?path=.%2Fproject1%2Ffile1.html status:400

Environment:
Chrome, local install (windows)
Version: Preview 4
Date: Jan 10, 2012 2:58:23 PM
Build: 3c236b1c2ec48a5...

**Comment by childsb** [comment]
The problem is on Windows--

When we create files on the server, we skip over writing if the content length = 0.

For some reason, just getting a URLConnection on windows then not writing anything would cause the JVM to lock the file in the thread.  This resulted in any file.delete() to fail (and leave the file on the file system).

I changed the code to write 0 bytes and set content length to 0 for empty files.  This resolved the file lock.

**Comment by aerwin** [comment]
Confirm fixed in latest build.
