### ISSUE TITLE
Error while undoing delete from source of dojox.mobile widget

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#1555]
1. New HTML Page, iPhone.
2. Drop a dojox.mobile.View into silhouette, then a Heading into the view and a ToolBarButton onto the Heading.
3. Split view to show source.
4. In source, select and delete the ToolBarButton source.
5. Click **undo** button.

Delete of ToolBarButton is not undone and I get an error in the console:

```
this.dijitWidget.domNode is null        davinci Line 53006
```

**Comment by peller** [comment]
note that undo is not hooked up to the source editor, so you're trying to undo the addition of the toolbarbutton widget (that is, you're deleting it again) which no longer exists.

**Comment by waynevicknair** [comment]
i assume you're dropping a TabBarButton on a TabBar because you get an invalid drop target message if you try to drop a ToolBarButton onto a mobile Heading. either way, i was able to reproduce this. however, @peller is correct about the "undo" wiring. this may be a UI bug because the "undo" is not disabled in the case where it is not connected.

**Comment by jhpedemonte** [comment]
OK, closing as duplicate of #343.
