### ISSUE TITLE
Don't add functions to dojox.mobile object

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#1558]
... or to any other object that isn't ours.  It's bad practice and can lead to issues.

In `Context.js._configDojoxMobile()`, there are 2 functions added to the `dojox.mobile` object. 

Move them to `Context` (or somewhere else) and just pass in the `dojox.mobile` instance.  If you only need to run some code **before** a `dojox.mobile` function runs, use [dojo.aspect](http://davidwalsh.name/dojo-aspect).

@peller

**Comment by peller** [comment]
I don't think it's bad practice at all.  In fact, re-assigning a method to run code first is _exactly_ what dojo.aspect does.

**Comment by billreed63** [comment]
This code was added my Adam so I am reassigning this issue to him. But I agree with Adam that I don not think this is bad practice..

**Comment by jhpedemonte** [comment]
Closing after discussion with Adam.

**Comment by peller** [comment]
So it was necessary, at the time.  These two methods actually do get called from dojox.mobile code, we're just modifying the behavior.  In fact, one of these methods (configDeviceTheme) is an empty stub there specifically so that we can get a callback, so that we _must_ put the code in dojox.mobile.  It's a little messy looking, but in the end, everything is still encapsulated in the dojox.mobile object.  Better if we didn't have to do this at all.

@billreed63, I seem to recall us getting some functionality added to dojox.mobile.  Is there anything here we don't need to do anymore?

**Comment by billreed63** [comment]
We got the functionality that remove the old css files from the head moved into dojox.mobile but @peller already removed that code from Context.js.

The rest of the code is needed, so we can dynamically change the dojox.mobile.themeMap  
The dojox.mobile.themeMap is defined and added to the dojox.mobile object and must be created before the deviceTheme object is created. This is done with javascript, but in page designer we do not run the page javascript so this code accomplishing the same result just post page load.
