### ISSUE TITLE
States don't work with sketch tools

### ISSUE THREAD

**Issue by ccmitchellusa** [maqetta/maqetta#1597]
Reported on P4 - All browsers

Create html page, low res sketch
Draw shapes on initial "Normal" state
Create new state, "Foo"
Draw shapes with new Foo state selected
Select Normal state
shapes drawn in Normal state still appear, but sometimes their position changes.

Also, cut/paste/copy of shapes does not seem to be working...not sure if related to the multiple states issue

This problem makes the sketch tools of limited use in mockups.

**Comment by JonFerraiolo** [comment]
Looks like we never tested shapes in combination with states. I took a quick look at why this is broken and haven't figured it out yet.

Note that the clipart widgets work with states OK, at least after a small amount of testing.

**Comment by jhpedemonte** [comment]
Follow-on commit by Jon: c211ea45476e22eb1e1b3331c5462c5f490654a0

**Comment by JonFerraiolo** [comment]
Reopening.

Not sure what I was seeing when I closed this bug. When I try simple things with shapes and states, things don't work:
- New HTML File (lo-fi sketch)
- Add a Text, Rectangle, Circle
- Define states aaa and bbb
- Make Rectangle and Circle invisible in Normal state
- Turn Rectangle on for state aaa, Circle on for bbb
- Cycle through the states

Result=> Rectangle will be a dot when state aaa is visible. Circle doesn't appear when state bbb is visible.

In tracing through the code, I believe there are some significant logic bugs with states. Widgets aren't told to redraw or resize themselves in custom states, and the shapes widgets need their resize() method called in order to get their dimensions set correctly.

**Comment by jhpedemonte** [comment]
Regarding commit 417055e4f5ebad10c3b950efba9d9359bbbd07d9, why isn't this an issue with other Dijit widgets?  Why do we only need to call `resize()` on Shapes?

**Comment by JonFerraiolo** [comment]
Good nose for smelly code! This requirement for shapes is due to an async timing issue with browsers and how they apply CSS style rules and the way I implemented shapes. I have a CSS rule that defines default values for SVG's CSS properties 'fill', 'stroke' and 'stroke-width', and then logic that actually builds the shape looks at the inherited value for these properties.  When the first shape loads, sometimes the CSS properties aren't in place, so the inherited values are wrong, so we need to trigger something (in this case resize()) so that the shapes can look once again at the inherited value for these properties.

Apparently, most or all of existing Dijit widgets don't have a similar timing issue due to the way they are currently constructed, but I can definitely see how there could be some other Dijit widget (other than shapes) where this issue would arise.
