### ISSUE TITLE
remove davinci.ui.Panel code and dependencies

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#1638]
@JonFerraiolo, @childsb, @jhpedemonte 

This code seems unnecessarily complex.  Replace with simple, static UI

**Comment by peller** [comment]
The four modules that seem to depend on this:

ui.plugin:
davinci/ui/ProjectPreferences

ve.plugin:
davinci/ve/prefs/HTMLEditPreferences

js.plugin:
davinci/js/ui/FormatOptions

davinci/ui/widgets/FileFieldDialog

If we can replace these with static or template-based UI, then we ought to be able to remove davinci/ui/Panel as well as davinci/workbench/PanelPreferencePane and the reference to davinci/ui/Panel in davinci/workbench/Preferences

@jhpedemonte, @childsb

**Comment by aerwin** [comment]
@peller

So, looking at this, I find the following modules with dependencies on `davinci.ui.Panel`. There's a fair number more than you reported initially:
- davinci.libraries.dojo.dojo.data.DataStoreBasedWidgetInput
- davinci.libraries.dojo.dojox.grid.DataGridInput
- davinci.libraries.html.html.HtmlSrcAttributeInput
- davinci.js.ui.FormatOptions -- dependency is that is requires Panel, but doesn't actually use it
- davinci.ui.widgets.FileFieldDialog
- davinci.ui.widgets.FolderSelection
- davinci.ui.widgets.OpenFileDialog
- davinci.workbench.PanelPreferencePane
- davinci.workbench.Preferences

There are two modules you mentioned as having a dependency (`davinci/ui/ProjectPreferences` & `davinci/ve/prefs/HTMLEditPreferences`) that don't appear to have a dependency. Am I missing something there?

Also, since this is perhaps a larger piece of work than you originally envisioned (9 modules I found compared to the 4 you found), do you still think removing `davinci.ui.Panel` is the best course?

**Comment by aerwin** [comment]
One additional note.... After latest pull, the `davinci.js.ui.FormatOptions` doesn't have any reference to Panel.

**Comment by aerwin** [comment]
@peller @jhpedemonte @JonFerraiolo @childsb 

Who knows about `davinci.libraries.dojo.dojo.data.DataStoreBasedWidgetInput`? I think it might be dead code. I only see it referenced in `EdgeToEdgeDataListInput`, but it doesn't appear `EdgeToEdgeDataListInput` uses it.

**Comment by peller** [comment]
try @billreed63   It does appear `EdgeToEdgeDataList` inherits from it `DataStoreBasedWidgetInput`, but you won't have to do anything specific to that file since there's no direct use of `davinci.ui.Panel` there.  So yeah, it does look like there were a few references in dojo_1_7 that I missed.  Perhaps they're all similar file/tree type UIs and can be replaced by some simple static Dialog definition?

**Comment by billreed63** [comment]
We have several store based widgets Tree, DataGrid, RoundRectDataList, EdgeToEdgeDataList, Carousel  I believe the dojo MVC also makes heavy use of stores, so when we support dojo MVC we will have even more widgets that use stores.  The idea behind the  ''' davinci.libraries.dojo.dojo.data.DataStoreBasedWidgetInput '''' was that it would be the base class that more specific widget class would inherit from to implement widget specific smart input. When I first created it I though I would use it for RoundRectDataList, EdgeToEdgeDataList and Carousel. I implemented EdgeToEdgeDataList first and found that I could just reuse that class unchanged for smart input for RoundRecDataList. I left the base class because we have not implemented smart input for Carousel yet. and DataGridInput still needs to be reviewed to see if it can be merged with DataStoreBasedWidgetInput, DataGridInput supports cross domain that would need to be added to  DataStoreBasedWidgetInput, it might also prove useful for dojo MVC support.

As for the ``davinci.ui.Panel`  it is used in when the user selects "Data file from workspace" and clicks on the folder icon. This will create a file selection dialog ````Panel.openDialog'''  The userr selects a file from their workspace to use as the data source for the store.

**Comment by aerwin** [comment]
Thanks, guys. I missed that `EdgeToEdgeDataList` inherits from `DataStoreBasedWidgetInput`. I've now modified `DataStoreBasedWidgetInput` to eliminate the dependency on panel.

@billreed63 @peller A couple other questions:
- `davinci.ui.widgets.FileFieldDialog` is only referenced by `davinci.ve.widgets.HTMLStringUtil`. `HTMLStringUtil` only creates `FileFieldDialog` in its `getEditor` function in the case where `metaType` equals `"file"`. Looking at the calls to  `HTMLStringUtil` throughout the codebase, I'm not seeing any obvious cases where that code path in `HTMLStringUtil` would be exercised (e.g., no cases where `"file"` type is used). Does anyone know differently?

And maybe more for @waynevicknair ...
-  I believe `davinci.js.ui.FormatOptions` is used to collect user preferences for JavaScript formatting. However, last I knew formatting of JS was broken and when I brought this up a couple weeks ago in the scrum there was some question whether some of the stuff in this package was dead code. Thoughts? I hate to spend time re-factoring this panel if either it won't be used or I can't test it.

**Comment by peller** [comment]
check with @childsb on HTMLStringUtil.  As always, extra points for eliminating dead code!

**Comment by JonFerraiolo** [comment]
I'm 99% sure that it's ok to remove FileFieldDialog references from HTMLStringUtil.js. The 'file' option doesn't appear to be used anymore. Probably older versions of the code used it for the background-image property before we added support for gradients. If 'file' were still used, there would be an entry for it in the big table at the top of ve/views/SwitchingStylingViews.js. Just to be sure, I put a breakpoint at line 121 of HTMLStringUtils.js and that breakpoint was never reached.

**Comment by peller** [comment]
This task is getting easier by the minute ;-)

**Comment by jhpedemonte** [comment]
Yes, the JS Formatter code is completely broken.  As far as I know, we've decided that this will be handled by Orion, if/when it supports that.
