### ISSUE TITLE
[AMD Regression] Startup exception duplicate ID

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1681]
At product startup (launched from Eclipse or build) the following exception appears in console:

```
dijit/registry:31Uncaught Error: Tried to register widget with id==davinci_ui_widgets_ProjectSelection_0 but that id is already registered
```

**Comment by peller** [comment]
@childsb 
`dojo.parser.parse()` get called many, many times.  Each of our custom templated widgets with 'widgetsInTemplate" turned on triggers a parse, and the entire page triggers a parse when the load is complete (onLoad).  The parse is supposed to replace the node with the dojoType attribute.  Some of our custom widgets don't seem to be doing this.  The rules for the custom widgets and their lifecycles are often unclear.

**Comment by JonFerraiolo** [comment]
@peller: I'm confused about what's going on with the original bug report and the relationship to the commit that fixes this bug.

When you say "Each of our custom templated widgets with 'widgetsInTemplate" turned on triggers a parse," do you mean that each custom templated widget triggers a parse of the subtree defined by the template, or does it trigger a full-document parse? 

If there is a problem with 'widgetsInTemplate' with triggering parse getting called many times, which changes in this commit addressed this multi-time parsing problem?

I did a grep of 'widgetsInTemplate' and found this:

```
de/DijitTemplatedGenerator.js:66:           this.value.js+='\twidgetsInTemplate:true\n' ;
de/widgets/NewDijit.js:12:      widgetsInTemplate: true,
ui/Download.js:18:      widgetsInTemplate: true,
ui/ErrorDialog.js:27:       widgetsInTemplate: true,
ui/NewProject.js:18:        widgetsInTemplate: true,
ui/NewTheme.js:21:      widgetsInTemplate: true,
ui/OpenThemeDialog.js:12:       widgetsInTemplate: true,
ui/Rename.js:11:        widgetsInTemplate: true,
ui/SaveAsWidgetForm.js:14:      widgetsInTemplate : true,
ui/UserLibraries.js:26:     widgetsInTemplate: true,
ui/widgets/NewFile.js:22:       widgetsInTemplate: true,
ui/widgets/NewFolder.js:25:     widgetsInTemplate: true,
ui/widgets/NewHTMLFileOptions.js:28:        widgetsInTemplate: true,
ui/widgets/OpenFile.js:24:      widgetsInTemplate: true,
ui/widgets/ProjectToolbar.js:30:        widgetsInTemplate: true,
ui/widgets/Views.js:11:     widgetsInTemplate: true,
ve/widgets/BackgroundDialog.js:21:      widgetsInTemplate: true,
```

**Comment by peller** [comment]
> When you say "Each of our custom templated widgets with 'widgetsInTemplate" turned on triggers a parse," do you mean that each custom templated widget triggers a parse of the subtree defined by the template, or does it trigger a full-document parse?

A parse of just the subtree, as you'd expect.  We've got a lot of them, which may or may not be a performance issue.  It's definitely not the fastest way to construct simple widgets.  If you look at something like ProjectToolbar/ProjectSelection, it's not clear we need custom widgets.  ProjectSelection is really just a ComboBox with a few lines of code used to instantiate it.

> If there is a problem with 'widgetsInTemplate' with triggering parse getting called many times, which changes in this commit addressed this multi-time parsing problem?

widgetsInTemplate isn't the problem.  It's the custom widgets referenced by the template which themselves aren't templates.  Widgets typically have code which constructs a replacement for `this.domNode`.  Because widgets like ProjectSelection and MultiInputDropDown leave the old domNode in place, the `dojoType` attribute persists even after the widget has been constructed by `postCreate()`.  Then, when the parser makes the full pass over the document, it sees `dojoType` and thinks it has to parse the widget and instantiate it again.  Manually removing the dojoType attribute seems to solve the problem.

I'm not sure why this is suddenly an issue, but like many things with custom widgets, if we don't do exactly as Dijit expects, we're likely to see breakage from one release to the next.  It's one reason why I think we should avoid custom widgets unless we are benefitting from the encapsulation enough to outweigh the complexity.

I guess we should make a pass through our custom widgets which are not `_TemplatedMixin`s and do not reconstruct this.domNode and see if we need to remove the dojoType attrubute.

**Comment by peller** [comment]
also, a footnote: the "new" way to make a Templated widget which runs the parser is to mix in _WidgetsInTemplateMixin instead of setting widgetsInTemplate:true.  This was part of the TemplatedMixin refactor to reduce code footprint.
