### ISSUE TITLE
Unused stores never get deleted from user HTML files

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1700]
@aerwin 
- New HTML File
- Add Button, Tree, Calendar
- Open up browser debugger showing DOM tree of user HTML doc. You'll see this inside of BODY: SPAN for Button, SPAN for ItemFileReadStore, SPAN for ForestStoreModel, SPAN for Tree, SPAN for Calendar. This is all OK
- Select Tree and "cut"
- Then issue a paste command and click to add Tree back in

Result=> Look at DOM tree of user HTML doc. You'll see 2 SPANs for ItemFileReadStore and 2 SPANs for ForestStoreModel.
- Save, close, reopen
- Show source view

Result=> If you scroll to right, you'll see that there are multiple ItemFileReadStore and ForestStoreModel in user HTML file that have been persisted across save and reopen

Probably same thing for other data-bound widgets, but I didn't check

**Comment by billreed63** [comment]
The issue with deleting data stores is that we need to insure that the store that is being deleted is only used by the widget that is being deleted. This is most likely not an issue with widgets that we place on the canvas, but if a user were to hand edit the source and add a widget that uses the same data store as another widget this could be an issue. This may also be more of an issues with MVC widgets.

**Comment by JonFerraiolo** [comment]
We need to clean up and remove unused data stores, one way or another.

In fact, it would be good to do a full document cleanup with such a traversal to deal with old files.

In terms of whether users can create HTML files with declarative data stores, and then refer to those declarative data stores in custom JavaScript, two approaches:
1. We could tell users "don't do that" - tell users that any declarative data stores will be deleted if not referenced by a declarative widget
2. We could allow users to put a flag (custom attribute) on a data store's markup saying "Maqetta, don't delete this one"
3. We could have Maqetta put a flag on a data store's markup saying "this was created by Maqetta, OK for Maqetta to delete this one"

With typical use of Maqetta, I expect that 99% of the time users will not create declarative data stores that are referred to only via custom JavaScript.

But my favorite option is #3. Seems safest.

**Comment by billreed63** [comment]
I have added code to the `davinci.ve.actions.DeleteAction.run()` that will call the widget helpers getRemoveCommand method, the method returns a command that will be added to the command stack instead of the default RemoveCommand that is part of DeleteAction.

What the `helper.getRemoveCommand(widget)` does is get the dataStore that is associated with the widget and creates a CompoundCommand adding a RemoveCommand for the widget and a RemoveCommand for the data store widget to the CompoundCommand. the CompoundCommand is returned for the `helper.getRemoveCommand(widget)` added to the command stack and executed.  Doing this allows undo/redo

By remove the data store at the same time as the widget is removed should ensure that no unused data stores are left behind.
