### ISSUE TITLE
States Testing -- element.style not available on CSS cascade for button background

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#1704]
Following the instructions in the "Changing properties in different states" section of the States Palette tests, and cannot change button to use element.style for background color despite the instructions advising me to do so:

> Note: For some of these cases below, the Properties palette will default to targeting the CSS style rule within a CSS style    >sheet. Instead, bring up CSS cascade and set the target to element.style. This might be something we fix in the future. We >should know that you can set fonts on the root node for button and can set width on the root for calendar.)

**Comment by aerwin** [comment]
Ok... reading thie instructions closer, the test actually calls for setting "font color" rather than the "background color" so maybe there's not a problem? Should element.style be available for "background color"?

**Comment by JonFerraiolo** [comment]
I'll investigate. I'm sure there are bugs in this area, and if not bugs, at least there are usability issues in this area.

But one thing I'll note is that for some widgets there are properties which cannot be set on element.style because that would result in a bad result. There is an explicit flag in our theme metadata for this. When I investigate this bug more deeply, I'll check into 'background-color' on Button.

**Comment by JonFerraiolo** [comment]
@billreed63 

OK, I investigated, and it's a feature, not a bug (said the engineer). The claro theme assigns background-color for dijit.form.Button to an inner node (accessible via CSS rules via this selector: .dijitButton .dijitButtonNode). Maqetta prevents the user from doing something that they really shouldn't do (i.e., assign background-color to root node of widget) because the background-color on the root node would be obscured by the inner node's background and the user would be confused because the background-color wouldn't appear to have changed (or worse, there would be one background partially overlapping another background). So instead the Properties palette posts a dialog that says:

```
This property change cannot be completed because the operation attempts to modify a read-only theme CSS file.

To change this property, one technique is to add a class to this widget (at top of Properties palette) and then open up the CSS Details pane to target a style rule within your app.css file, as described at Creating Style Rules with app.css.
```

There are various improvements to the Properties palette that we intend to do, such as show read-only computed values with different styling than values that can be changed, but users seem to be getting by with the Properties palette as is.

Pushing to M6

**Comment by JonFerraiolo** [comment]
-> M7 Med

**Comment by JonFerraiolo** [comment]
I closed bug with above commit. Actually, as @billreed63 pointed out above, the Claro theme puts background-color (and with dojo 1.8, color also) on an interior node, so we don't allow user to set these properties on element.style because they won't have effect. (An interior dijitReset class will kill the cascade of 'color' from element.style). I updated the test case to make sure the instructions don't tell testers to do something that won't work.

There are other bugs open for improving the UI around this case.
