### ISSUE TITLE
[AMD Regression] Background dialog for mobile theme editor shows File dialog on bring-up

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#1709]
1. Click button to bring up Background dialog to change global background in a cloned mobile theme
2. Close dialog
3. Bring up Background dialog again and fFle dialog incorrectly shown on top of Background dialog

**Comment by peller** [comment]
HTMLStringUtil's id generator was replaced in 2912c572b57eac8f85ba7e34a6a61e6131bb86aa and cb966196cd898ae3e2be4f63eb61257b4f621c4c with code that appears to collide with other widgets, so the FileFieldDialog hooks on to the button in the properties palette instead of some other button deeper in the hierarchy.

**Comment by peller** [comment]
Probably better to share a routine to generate ids, but not to couple it with the methods in HTMLStringUtils that seem to pull in so many dependencies.  Perhaps if that was broken out to a separate module instead, that would have broken the circular dep?  It also may be possible to structure this code such that ids don't need to be used at all.
