### ISSUE TITLE
Vertical Slider: left labels shift to right

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1716]
@billreed63 
- New HTML File
- Add Vertical Slider
- In dialog that comes up, click on one of the + icons and add a label column so that there are now 2 label columns. Make sure one of the label columns is 'left' and one is 'right'
- In either visual editor or Outline palette, select the left column labels and under widget-specific change value for 'Labels' (e.g., to 0,1,2)

Result=> Both label columns are now on right side of slider even though one of the label columns says 'left'

**Comment by aerwin** [comment]
Yes... this is one of the remaining issues I described in #816 (though I described it in a more obscure way there):

> need to add `refreshFromSource` to some other properties on rule labels (like `count` and `labels`), but `preProcessData` in > my helper for `HorizontalRuleLabels`/`VerticalRuleLabels` gets bypassed in that case

**Comment by aerwin** [comment]
I'll want to extend this issue to include all of the `refreshFromSource` issues recorded in #816 by @aerwin on Feb 6:

> - would be nice if a property marked as `refreshFromSource` gets changed that the widget gets re-selected
> - need to add `refreshFromSource` to some other properties on rule labels (like `count` and `labels`), but `preProcessData` in my helper for `HorizontalRuleLabels`/`VerticalRuleLabels` gets bypassed in that case
> - Outline
>   - Re-ordering slider children needs to do equivalent of `refreshFromSource`

**Comment by aerwin** [comment]
@jhpedemonte could you look at my proposed commit for this one and let me know what you think? I decided to try and take a different approach due to the problems `refreshFromSource` caused (described above) and added a `refreshParent` attribute instead.

Note this commit does _not_ address the outline re-ordering bullet from the problem description.

**Comment by aerwin** [comment]
@jhpedemonte @JonFerraiolo 

This second commit (50ffddbf4a68a0165f224065bf505c4772174bc4) contains changes to allow re-ordering slider children in the outline to work. This involved adding a helper function to handle adding children.

Since this changes the helper interface, I'd appreciate it if you could review.

(Also, any input on the first commit b919a9de8bab91ca292527d53a263a87fc96ee68 would be appreciated as well.)

**Comment by jhpedemonte** [comment]
Yes, I think in this case it's best to push this up from the property level to the widget level.  Something like this:

```
    {
        "name": "HorizontalRuleLabels",
        ...
        "refreshParentOnPropChange": true
        ...
    }
```

I can see this being quite useful in for other widgets, and prevents us from having to go to the "nuclear option" of the `refreshFromSource`.

---

I'm wondering about this part in your patch:

```
+      // Note we're executing the ModifyCommand directly as opposed to adding to it to the 
+      // command stack since we're not really changing anything on the parent and don't
+      // need to allow user to undo it.
```

To me, this implies that we are running _ModifyCommand_ once for modifying the child properties and then a 2nd time to modify the parent (and, implicitly, the children again).  This seems redundant.  Is there a way to only do this once?

**Comment by aerwin** [comment]
I'll make the change for _refreshParentOnPropChange_. Per our phone call earlier, I think that's a good suggestion.

As for _ModifyCommand_ being run twice... you could argue this is redundant. But, I believe it leads to the most straightforward code. I think the alternative would unnecessarily complicate the algorithms in the _execute_ and _undo_ functions (especially since this isn't the normal code path). And, since there's no noticeable impact on performance executing this code twice, it doesn't seem like we'd really be gaining anything. So, I'd vote for leaving it as is.
