### ISSUE TITLE
Can't set background of heading and button in mobile theme editor

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#1740]
1. New mobile theme
2. Select global background and change background color (works fine)
3. Select heading and change background color (no affect)
4. Select button and change background color (no affect)

NOTE: Changing font properties on heading and button seems to work fine

Environment: Chrome, local install on windows

**Comment by JonFerraiolo** [comment]
@billreed63 
Which theme did you clone? If you cloned Android, then what's going on is that the background-image property value is masking out the background-color value. The background-color value has actually changed, but the background-image is super-imposed with an opaque gradient. However, if you cloned Custom, there is also a gradient, but it uses rgba() color values so that the gradient is partially transparent, and allows background-color changes to shine through the gradient.

So, I think this bug is probably just that the product should warn the user if they attempt to change background-color if background-image has a value.

**Comment by aerwin** [comment]
I wasn't able to change background color for any of the mobile themes. Yes, a warning would be good. And, I think the test case instructions need to be augmented.

**Comment by JonFerraiolo** [comment]
@billreed63 and @childsb made fixes so this is working now. Closing.
