### ISSUE TITLE
Maintain require() dependencies in user files in a single require() call

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#1750]
We did a quick job converting dojo.require() usage 1:1 with require([]).  The new AMD syntax permits passing multiple dependencies to that call through the array, and it seems the loader may work better that way. In particular, multiple require calls may result in race conditions where individual modules get loaded before layers, preventing the layers from working optimally.

**Comment by jhpedemonte** [comment]
@peller, how much is this needed for M5?  OK to push to M6?

**Comment by peller** [comment]
@jhpedemonte, would help somewhat with performance in M5, but very important for M6 optimizations like #1586 and #27.  Might be risky to do now anyway.  How about M6->High?

**Comment by jhpedemonte** [comment]
-> M6/high

**Comment by jhpedemonte** [comment]
Committed preliminary fix to branch `1750-one-require-to-rule-them`.  @peller, check it out.

Some issues still remain:
1. I wasn't able to get this working while caching the HTMLElement for the `require` from the model.  When I had code that did that, if I opened the split view (to show VE and source), then source wouldn't update any more when setting text on cached element.  My initial thought was that a whole new model had been created, but the cached element seemed to be a child of `this._srcDocument`.  So not sure what's going on.
2. I'm using a "text to array to text" approach, but that requires that I use `eval` to create the array.  That's because the text is JavaScript, not JSON -- the elements in the array won't always use **double-quotes**.  One way around this might be to craft a more intricate RegExp, in order to pull in the elements that way (instead of eval/JSON.parse).  I should still be able to use `JSON.stringify` on output, though.
3. Right now, the DOM is updated one at a time for each incoming module, with a call to `require`.  Is there a way to batch these together?  I thought of using a timer to do the batching, but then that might lead to a situation where the `require` hasn't yet been called before the rest of the code tries to evaluate the widget (and dependencies haven't yet been pulled in).
   
   A solution might be to make use of the `require` callback and wire the rest of the code up with **promises**.
4. Pretty printing of the single `require`.  With the current code, everything goes on a single line.

**Comment by jhpedemonte** [comment]
5. Also unresolved is what to do about this line (which gets added when switching mobile themes):

``` javascript
require(["dojox/mobile"],function(dojoxMobile){dojoxMobile.themeMap=[["Android","",["themes/android/android.css"]],["BlackBerry","",["themes/android/android.css"]],["iPad","",["themes/android/android.css"]],["iPhone","",["themes/android/android.css"]],[".*","",["themes/android/android.css"]]];dojoxMobile.themeFiles = [];});
```

Options, for now:
- Keep it as its own line, below the "main" `require` array; or
- Find a way to get rid of that inline function.

**Comment by jhpedemonte** [comment]
With latest commits, issues [(2) and (4)](https://github.com/maqetta/maqetta/issues/1750#issuecomment-5199137) are now fixed.

**Comment by jhpedemonte** [comment]
What are the implications of outputting something like this:

``` javascript
require(["...",
    "dojox/mobile",
    "..."
]);
require(["dojox/mobile"],function(dojoxMobile){...});
```

Will this work correctly?

**Comment by jhpedemonte** [comment]
The last commit (e6052562d3a47c6b648400bc18bb0c6f0513a083) fixes [issue (5)](https://github.com/maqetta/maqetta/issues/1750#issuecomment-5208710) by doing what I [outlined above](https://github.com/maqetta/maqetta/issues/1750#issuecomment-5212195).

There's still some other _themeMap_ code that I need to change.  Also, some of the data store code does similar shenanigans.

**Comment by jhpedemonte** [comment]
Have another case, similar to the [dojox.mobile situation](https://github.com/maqetta/maqetta/issues/1750#issuecomment-5208710):

In **ItemFileReadStoreHelper.js**, the code adds a callback to a require statement, to look like this:

``` javascript
require(['dojox/io/xhrScriptPlugin'],function(xhrScriptPlugin){xhrScriptPlugin('URL');}
```

It's not so easy to do this in the one-require case, given that the module could be in any part of the array, and the arguments into the added function have to match up.

---

@peller, what do you think of something like this: add a generic callback with no arguments, in which we can add an inline require to call that function:

``` javascript
require([
  ...
  "dojox/io/xhrScriptPlugin",
  ...
],function(){
  require("dojox/io/xhrScriptPlugin")("URL");
});
```

**Comment by peller** [comment]
so this ought to work fine.  You could also make it the first module (always) in the require, then you'd be able to use a reference from the arg list.

Grouping the xhrScriptPlugin with the other requires would have the advantage that it could be picked up by an aggregator or loaded in a layer.  However, I'm concerned that it could be messy syntactically to maintain should the function body change or other similar code be added.  An alternative would be to just use a separate require and forego any aggregator or layer loader optimization for this particular module.

**Comment by jhpedemonte** [comment]
I merged the changes on the branch into **master**.  Only remaining issue is the one mentioned above, dealing with JSONP URLs for data widgets.

**Comment by jhpedemonte** [comment]
After fixing #2158, I know of no further issues as a result of the one-require changes.  Closing.
