### ISSUE TITLE
Support hash value for moveTo property

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1757]
@peller, @jhpedemonte 

dojox.mobile allows the moveTo property to be either an ID or an ID preceded by a "#" character. The difference is that if you use "#", then dojox.mobile will put the moveTo operations onto the browser history stack.

This issue is to investigate whether the "#" syntax works today and if not figure out how to support it.

**Comment by JonFerraiolo** [comment]
Pushing to M6.

**Comment by doronrosenberg** [comment]
@jhpedemonte @JonFerraiolo 

This does not work today in Maqetta because we are not requiring dojo.hash, which implements the hash functionality.  Adding it to the source of a maqetta generated file enables it correctly.

We would have to add that as a require in the oam.json files for all the mobile view types (View, SwapView and ScrollableView) if we want this.
