### ISSUE TITLE
Resize DIV and TabContainer inside doesn't resize

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#18]
As reported by @JonFerraiolo:

(Maybe piling too much on Adam - maybe Brad or Bill could look at this one)
- New HTML file
- Add a DIV
- Set size to w=h=300px
- Add a TabContainer inside the DIV. (TabContainer defaults to 100%/100%, so it
  fills the DIV)
- Save, close, reopen
- In Outline palette, select the DIV
- Pull on resize handles to make the DIV wider
  Result=> TabContainer does not resize
- Save, close, reopen
  Result=> TabContainer is now the right size

Maybe we aren't calling the resize method for children of DIV?

see bugzilla bug 7270

**Comment by peller** [comment]
This is Dijit working as designed.  Because the tabcontainer is not managed by
a parent widget, it has no way to know it was resized, so it does not resize
its children.  We would have to inject some code to call resize when the parent
div is resized.  Perhaps by hooking onresize on tabcontainer.domNode (does this
work cross browser?)  otherwise, checking whenever divs/spans/whatever are
resized for child dijits which have % sizes and call resize on them...

@JonFerraiolo replied:
I expect we are going to have this sort of problem with widgets from other
toolkits, too, and therefore need to have some general mechanism. How about all
containers always call a helper resize function on their children. The default
resize function recurses through children to call their resize function
(usually the default resize function). If a widget has its own special helper
resize function, then that can call the widget's resize method.

**Comment by JonFerraiolo** [comment]
Setting to M3, Priority-Med. The redraw/resize problems we have upon opening Sample1.html are embarrassing.

@jhpedemonte - Maybe this is a different case for the library APIs, but in this case it is the child listening to events on one of its ancestors?

@billreed63

**Comment by jhpedemonte** [comment]
This one is a bit tough.  If a user sizes the widgets inside of a container to a certain size and then sizes the container bigger, should the widgets inside resize as well?  I'm not sure that's always the case.

**Comment by JonFerraiolo** [comment]
What we want is WYSIWYG - Maqetta shows the same thing that will happen when the page ultimately runs in the browser. If the child resize based on the parent, then when the parent changes size, we need to resize the children. Of course, easy to say, maybe harder to pull off. We probably can't support all cases. Certainly, we can support width or height set to "auto" because the browser will resize things for us. For some Dojo widgets, our code might need to call resize() on children somehow.

**Comment by jhpedemonte** [comment]
I'm still not sure exactly what you want to accomplish here. For example, if I have a TabContainer in which I've put a couple of TextBox widgets, one on top of the other.  Later I realize that I want to add something on the right of those TextBoxes and I resize the TabContainer horizontally.  Should the width of the TextBoxes increase as well?  I don't think so.

And if we try to get into the business of guessing when children should be resized and when they shouldn't, we'll just get ourselves in trouble.

**Comment by JonFerraiolo** [comment]
I was thinking that, when an ancestor widget changes size, we add logic to invoke the resize() method on descendant widgets. I would expect this would be a library API or widget API because we would only want to do this for Dojo widgets and not for HTML widgets. Perhaps something like Dojo layout containers register themselves for notification whenever an ancestor changes size. Then the callback logic for the layout widget does some checks to see if it makes sense to invoke the resize() method on the layout widget. (For example, if the layout widget is absolutely positioned or has fixed width or height, then maybe don't call resize()). Obviously, I don't have a total vision for how this would work. We need to get into the debugger and study various scenarios to make sure we can find an approach that (a) addresses this bug and other similar bugs (b) has no adverse side effects
