### ISSUE TITLE
UI tweaks to palettes - bringing palettes to top for particular editors

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1814]
@jhpedemonte, @peller , @waynevicknair 

During today's phone call, we decided we needed to make the following changes to Maqetta's overall UI:
- Instead of Widgets, Files, Reviews at top left, it should be Files, Widgets, Reviews. (This is easily fixed: just cut the Files entry in ve.plugin.js and paste it above the Widgets entry)
- Add a mechanism to ve.plugin.js such that a particular editor can force certain palettes to come to the top. I think this isn't all that hard, either (famous last words). We have the following code in ve.plugin.js (and similar code in review.plugin.js):

```
    "davinci.editor": [
        {
            id: "HTMLPageEditor",
...
        },
        {
            id: "ThemeEditor",
...
        }
    ],
```

What I'm thinking is an optional property for each editor object, such as "palettesToTop", which holds an array of the IDs for various Views (e.g., `viewID: "davinci.ve.Palette",`) whose tab should be selected when switching to the given editor.

Then, to implement this, I'm pretty sure that _switchEditor() in Workbench.js gets called both when a new editor is opened and when switching to an already open editor by clicking on its tab. So maybe within _switchEditor() we determine the ID of the current editor, and then find its "palettesToTop", and then call the appropriate Dojo code to select the tab that corresponds to that particular palette.

**Comment by aerwin** [comment]
@JonFerraiolo 

It appears the File palette has already been moved to live within a different set of tabs, so I'll skip the first bullet and focus on the 2nd bullet.

Do we have any sort of a spec (even partial) on what palettes should get brought to the top for each editor?

**Comment by JonFerraiolo** [comment]
Here you go:
- Page editor: bring Widgets, Properties, States(Scenes) to the top
- Theme editor: bring Properties, States(Scenes) to the top
- Review editor: bring Reviews, Comments, States(Scenes) to the top

**Comment by aerwin** [comment]
At the scrum this morning, we debated whether we needed to do something more advanced than Jon's proposal. For example, maybe we want to do some persistence so if user has made Outline Palette active in Page Editor that when we come back to Page Editor we don't switch to make the Widgets palette active. But, the consensus was to keep it simple for M5 and revisit at a later date as we discuss simplifying the entire user interface.

In addition, I added to John's spec slightly to make it most editors (aside from Review Editor) would bring Files and Properties to the top because I didn't think there was any reason to keep the Review or Comments tabs active when switch to a css or js file
