### ISSUE TITLE
Changing State does not work in preview mode 

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#1835]
1) Create new html page (hi def)
2) DnD lable
3) Create state (two)
4) Change scene to two (the state you created
5) In outline palette hide the label (close the eye)
4) Select Label and change the onclick event in properties palette to state two 
6) Save and preview
7)click on the label...

Result the label is not hidden

**Comment by JonFerraiolo** [comment]
@jhpedemonte 
The problem with this bug appears to be that there are no dojo widgets on the page, so the SCRIPT tag for dojo isn't there, so `require` isn't there, so we never run the dojo parser, so we never run _preserveStates and _restoreStates. If I add any dojo widget to the page, then the label will properly appear/disappear (or at least it does so in my StatesCleanup1 branch).

Assigning to @peller because I'm pretty sure that with his fixes to States.js we will always have dojo's `require` available, so hopefully this bug will now be fixed.

**Comment by peller** [comment]
works now
