### ISSUE TITLE
Calendar in theme editor has number for month instead of word

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#1837]
Clone claro, notice when the theme editor opens the calendar widget has a 3 instead of march

**Comment by peller** [comment]
I suspect this is fallout from http://bugs.dojotoolkit.org/ticket/14169 which may not have been completely fixed on 1.7.2.  It's an issue for themeEditor because it uses the Calendar from a built layer called dijit-all, and 14169 restores the behavior where dijit-all resources are loaded from nls/dijit-all

**Comment by peller** [comment]
backed out 1.7.2: fd15157f77e9b5c4e1def2988b3c0bdb8fddc66d
