### ISSUE TITLE
Inefficient (bad?) theme code in Context._setSourceData

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#1845]
`Context._setSourceData()` has some theme code which is very odd, and also inefficient.  This theme code is invoked whenever the source is changed (user editing in source mode) or when doing the "refresh from source" path.
1. When invoking `_setSourceData()`, the function `themeChanged()` is always called.  It does a `model.find()` for a CSS import of _"themes/claro/claro.css"_ and **always fails** (even though the source does have an import for that CSS file).  This means that `_themeMetaCache` is set to `null` **every time the source is reset**.
2. Because `_themeMetaCache` is always set to `null`, this eventually leads to always calling `metadata.loadThemeMeta`, which again does a `model.find`, amongst other things.

Overall, this code needs to be rewritten -- there is **no reason to always load the Theme files when the user has only changed a bit of the source**.  We need to be smarter about this.

(Assigning to @peller for now, since this is performance-related.  But may need to be fixed by @billreed63)

**Comment by billreed63** [comment]
I am not sure who authored that code it has been around as long as I can remember, maybe @childsb knows. If I remove the `&& style.length` from line 638 it will prevent the code from refreshing the `_themeMetaCache` if the theme has not changed. But this does not prevent the CSS files from being reloaded. The CSS files are being loaded because the model is being rebuilt by `setSource` which is called any time a change is made in the source editor. To prevent the CSS files from being reloaded we would need to have the source editor update the same model that the VisualEditor is using.

**Comment by peller** [comment]
@billreed63 points out that even with this fix, the modeler is still loading the css files on changes.  The fix here may have just avoided a cached hit?  I think the remaining concerns are addressed in #1522 and #1863

**Comment by jhpedemonte** [comment]
OK, closing.  As Adam mentions, further work can take place in those other issues.
