### ISSUE TITLE
review files should be stored in the project directory

### ISSUE THREAD

**Issue by childsb** [maqetta/maqetta#1859]
project structure right now is:

project1/
project2/
project3/
.review/

the .review folder contains snapshots for all projects.  this is problematic for sharing projects (and reviews) over source control, or instances where projects aren't in the root folder (orion).  moving the .review/ folder should also simplify server logic.

this will be critical for GIT/orion support of R&C.

**Comment by JonFerraiolo** [comment]
@childsb - are you saying that .review folder should be inside of the project folders?

**Comment by childsb** [comment]
Yes.  A project should self contain any settings or configuration that move around with a project. 

The biggest reason is for proper source control handling. Without the .review folder inside the project, the reviews will be lost once a project leaves it's base Maqetta install.  

Thats not to say we ALWAYS want the review snapshots to tag along with the project, but in a lot of cases we do.  It would make things like exporting a Maqetta project as zip then re-importing it (with R&C intact) possible. 

Another example/reason from Orion--

If you checkout maqetta from GIT into orion, the file tree looks like

maqetta/maqetta.core.client
maqetta/maqetta.core.server

etc..

If the review snapshots are saved into the parent directory of a project, they end up in /maqetta/ (which is not-a-real-location on Orion, but the top level git repo).  And once we allow projects to exist at any folder depth, R&C would end up spewing snapshots in parent directories which wouldn't make sense.

**Comment by JonFerraiolo** [comment]
Yes, your explanation makes sense. 

What happens with .review folder now when you export as ZIP? I hope we aren't including it, and we should set the default to not include it even if we offer users an option to include it. It's likely to cause more trouble than it's worth. Note that Maqetta server 1 might be running a whole different version of Maqetta or include different widget libraries than Maqetta server 2. My guess is that exporting .review/\* is likely to bring along with it a whole ton of issues, at likely small gain to users.

**Comment by aerwin** [comment]
@childsb @JonFerraiolo 

I talked with @childsb and as part of other work he was doing for Orion in M6 - Sprint 1, he's done the important pieces of this item. Orion is not dependent on anything else related to this work item.

However, @childsb was not able to eliminate the .review directory entirely because of work I did in M5 under #360 so users could see both reviews they've created and reviews they've been invited to. The reason being that folks can be invited to a review who are not yet registered Maqetta users, and there's no other good place to store this information (e.g., the invitee may not have a user-specific directory yet).

We could keep this issue open as a lower priority design issue where we consider alternatives (perhaps storing dummy user information in user.xml and/or creating temporary dummy user directories). But, I'm not sure those alternatives have any real advantages. So, I'm inclined to just go ahead and close this issue.

Please let me know if you disagree,
