### ISSUE TITLE
Review editor leaves dangling "stay on this page" handler

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1867]
@aerwin, @childsb, @doronrosenberg 

Assigning to @waynevicknair but maybe one of the folks above might have cycles and want to snatch this bug and fix it.
- Create a review
- Open the HTML file for that review
- Add a comment, add an annotation while comment is open, but don't click Submit
- Close the review editor. You will see an "are you sure" prompt. Click OK/yes to close the review editor
- Click the back button on your browser

Result=> Browser dialog appears asking whether you want to leave this page or stay on this page

My guess is that there is a browser unload event handler in the review code that gets installed when a comment is open for editing. What I believe is the best behavior is that we leave the "leave or stay" prompt when a comment is opened, but remove that event handler once a comment is closed.

**Comment by aerwin** [comment]
@JonFerraiolo  @aerwin, @childsb,@doronrosenberg  @waynevicknair 

I can grab and take a look if no one's done anything on this one.

**Comment by aerwin** [comment]
@JonFerraiolo @waynevicknair 

`CommentView` contains the following `unload` handler to block navigation if the new comment form is showing:

``` javascript
   this.connect(dojo.global, "beforeunload", function(evt) {
            if (this._commentForm.isShowing == true) {
                return workbenchNls.fileHasUnsavedChanges;
            }
        });
```

What I'm seeing here is that the Comments tab is cleared (whether there's an unclosed comment or not) _only_ when the new editor is another review. So, in Jon's case there is no new editor and the comments view stays populated (meaning the unclosed new comment is still showing). So, then `commentForm.isShowing` is true when the unload handler is invoked.

So, it would seem to me the Comments view should always be cleared when switching to no editor or an editor of a different type. But, I see code in the  handler for the subscription to "/davinci/ui/editorSelected" that specifically blocks this:

``` javascript
            //Remove the comment nodes of the previous page
            if (!Runtime.currentEditor || Runtime.currentEditor.editorID != "davinci.review.CommentReviewEditor") { 
                return; 
            }
```

On the surface, the "easy" fix would be to remove this if statement. But, I want to make sure there wasn't some past design decision that caused that logic to be added in the first place.

Thoughts?

**Comment by JonFerraiolo** [comment]
@aerwin 
I don't actually follow _everything_ in your write-up above, but I think I can respond nevertheless. 

For better or worse, the current UI for adding a comment is basically modal because you go into an "edit comment" mode and only then can change the text content of a comment or add/modify/delete annotations associated with that comment. Unlike nearly everything else in Maqetta (page editor, theme editor, ...) where changes are instantly applied, commenting changes (including annotations) aren't applied until the user hits Submit. In M6 and later we will want to work with the UI folks on this ugly modal wart, but we are stuck with it for M5.

Because the rest of Maqetta has an auto-apply approach, no problem if the user navigates away from the browser page - we already POST'd their changes to the server, and their changes will appear the next time they go to the Maqetta URL. 

But we have a major potentiality for lost user data with review comments. So, IMO, we need to put an unload handler as short-term method for minimizing user data loss due to navigating away from Maqetta when a comment is open (and therefore not yet submitted).

What I propose:
- If a comment is open for editing, then we install an unload handler on the app that will present a meaningful prompt or dialog to user explaining that they have a comment open and all text data and annotations associated with that comment might be lost.
- If the user switches editors away from a review editor with a comment open, then we post a meaningful prompt or dialog to user explaining that they have a comment open and all text data and annotations associated with that comment might be lost.
- When the comment is closed (via Submit or Cancel), uninstall the unload handler.

**Comment by aerwin** [comment]
@JonFerraiolo @waynevicknair 

Quick follow-up... removing the if statement fixes Jon's scenario when there are no other active editors because when the null editor is null is clears out the comments:

``` javascript
    if (!editor) {
    this._resetCommentView();
    this._currentPage = null;
    this.states = null;
   }
```

But, when another "non-revew" editor is present (e.g., HTML page editor),  it does not clear the comments view and the same problem exists. So, some additional code changes would be needed if we decide the right behavior is to _always_ clear the comments view.

**Comment by aerwin** [comment]
Some high-level notes from a post-scrum discussion with myself, @JonFerraiolo, @peller, @waynevicknair:
- @peller concerned we have `beforeunload` handlers in both `Workbench` and `CommentView`. We agreed we should look into eventually combining them, but this isn't really important for the scenario at hand.
- We agreed we should clear out Comments tab whenever the user switches editors, _but_ we need to try and intercept the switch to put up a dialog allowing user to stop the switch if a comment is currently being edited. 
  *\* There's not currently an architected way to inject a warning message on editor swtching, but it was speculated we could try and architect something using the "editorClosing" event. I'll have to do some investigation in this area.

**Comment by aerwin** [comment]
Also, making this high priority given discussions about potential data loss, etc.

**Comment by peller** [comment]
The original scenario described seemed to have a lot to do with the beforeunload handler (we've since brought in other issues, like switching views and the state of the comments view, all important as well)  Regarding beforeunload, my concern isn't one of code style.  onbeforeunload will only work, I think, when it is assigned directly to window.  dojo.connect will not work as it does not handle return values, and the handlers do nothing but return a value for a prompt.  I do not see the beforeunload prompt in this scenario at all when I try on FF.  In fact, I do not see it under any scenario with dirty editors trying to move off the page.

**Comment by aerwin** [comment]
@peller That's interesting... you're right that the leaving page warning dialog does not come up in Firefox with the back button in Jon's scenario. I had been using Chrome which _does_ show the dialog. So, I'll have to look more closely at our unload handling to close all the holes here.

**Comment by aerwin** [comment]
@peller Turns out both `beforeunload` handlers (e.g., both the one in `Runtime` and the one in `CommentView`) get invoked even in Firefox. However, the reason no message appears in Firefox is that the handler in `CommentView` is missing the Mozilla/IE workaround that's present in 'Runtime'.

`Runtime` handler:

``` javascript
     window.onbeforeunload = function (e) {
            var shouldDisplay = Date.now() - window.davinciBackspaceKeyTime < 100;
            if (shouldDisplay) {
                var message = webContent.careful;
                // Mozilla/IE
                // Are you sure you want to navigate away from this page?
                // Careful! You will lose any unsaved work if you leave this page now.
                // Press OK to continue, or Cancel to stay on the current page.
                if (e = e || window.event) {
                    e.returnValue = message;
                }
                // Webkit
                // Careful! You will lose any unsaved work if you leave this page now.
                // [Leave this Page] [Stay on this Page]
                return message;
            }
        };
```

`CommentView` handler:

``` javascript
      this.connect(dojo.global, "beforeunload", function(evt) {
            if (this._commentForm.isShowing == true) {
                return workbenchNls.fileHasUnsavedChanges;
            }
        });
```

Adding the workaround to `CommentView` causes the message to appear in Firefox.

But, note a couple of interesting items:
- Firefox pays no attention to the message returned. It always displays the same "This page is asking you to confirm that you want to leave - data you have entered may not be saved." message.
- Chrome pays attention to the message returned and places it on the dialog. The last return value wins. (even if both return a message).

**Comment by peller** [comment]
The Mozilla documentation suggests that you should set the returnValue _and_ return the same string, though it isn't clear whether the return value is used.  Note that it's not a last one wins in the case of the return if you use dojo.connect.  It's not obvious from the docs that dojo.connect returns either of the values.

**Comment by aerwin** [comment]
@JonFerraiolo @peller @waynevicknair 

Hey, guys... As mentioned in the scrum this morning, I took a different approach than we discussed yesterday. But, in the end, I think it's better and cleaner.

To try and maximize test cycles, I've gone ahead and merged my changes with master. Please let me know if you have any comments on the code in the commit. Also, @JonFerraiolo since you opened issue to start with, if you could do some quick testing that would be awesome.
