### ISSUE TITLE
Press delete key in outline view, removes the entire outline widget

### ISSUE THREAD

**Issue by doronrosenberg** [maqetta/maqetta#1877]
Press delete key in outline view, removes the entire outline widget

**Comment by doronrosenberg** [comment]
To add some more data:

On windows, firefox/chrome, pressing delete after focusing a tab will delete the tab widget. 
On windows, firefox/chrome, pressing delete inside the outline widget deletes the tab widget.

On mac, I always get the "leave page"  dialog.

**Comment by peller** [comment]
dijit.StackController does seem to support deleting panes/tabs with the DELETE key.  We ought to disable that.  Ideally, we'd also make the Mac behave such that the key stroke went to the widget you clicked on (with focus) rather than to the browser chrome (which attempts to navigate away from the page).  @doronrosenberg, wondering if you might have any idea why the browser would treat focus/keystrokes differently here.

**Comment by doronrosenberg** [comment]
hmm, the only thing I can think of is we are somehow on Mac intercepting an event during capture phase.

Are you using a macbook pro? I wonder if the delete key on its keyboard is actually sending backspace?

**Comment by peller** [comment]
@doronrosenberg - yep, macbook pro, and I think you solved the mystery.  Does backspace cause the browser to go 'back' (and get that warning) on windows?  fn-delete causes the delete behavior you see (at least it did until f3395f0d920f2786627a2b80bb3158874ea1335e)
