### ISSUE TITLE
basic state switching not working

### ISSUE THREAD

**Issue by childsb** [maqetta/maqetta#1895]
1) new html file
2) add a dijit button
3) add a div
4) set background color of DIV to black (so you can see it)
5) add a new state HOPETHISWORKS
6) select the DIV, and set it invisible for HOPETHISWORKS state
7) select button, and under event change the onclick to change state to HOPETHISWORKS
8) preview in browser.  notice that the DIV isn't visible, and clicking the button doesn't do anything.

**Comment by JonFerraiolo** [comment]
States are working! The problem is that in the Maqetta page editor we include content.css which give min-height of 1em to DIV, but in preview, we don't include that same min-height setting, so the DIV isn't visible because it has no content, and height is auto, which becomes 0px in preview. There is a different bug for the content.css problem. I'll get it in a sec...

**Comment by JonFerraiolo** [comment]
The content.css bug is #505

**Comment by childsb** [comment]
oh that makes sense now!  sorry, i tried it 5 times in disbelief.  next time i'll use something other than a DIV.
