### ISSUE TITLE
Download workspace dialog has version 0.3 for maqetta

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#1906]
When I click on the icon to download the entire workspace the dialog that is displayed has the text 
"maqetta    0.3"

---

See [comment](https://github.com/maqetta/maqetta/issues/1906#issuecomment-4598687) by @jhpedemonte for more details.

**Comment by jhpedemonte** [comment]
Is this a dup of #1512?

If not, I need more details here. What do you mean?  What is expected?

**Comment by JonFerraiolo** [comment]
This wasn't assigned to anyone, so I assigned to @childsb so it wouldn't fall into cracks.

**Comment by JonFerraiolo** [comment]
Reopening. Had to revert the change. See commit 28d5ecc399 . Need help from @jhpedemonte on this one.

**Comment by jhpedemonte** [comment]
According to Bill, he opened this bug because the version for **maqetta** library was **0.3**, which contrasts with our current version of **M5**.

Personally, I think this should just be fixed by #1512, but I'll push this to M6 for now.

-> M6/low

**Comment by JonFerraiolo** [comment]
Note that the "maqetta library" means about 20 lines of JavaScript that strips out whitespace between DIVs and SPANs so that HTML pages display the same at runtime as they do in the page editor. This "maqetta library" is a whole different thing than "Maqetta the app" (which is now approaching the Preview 5 release).

I agree with Javier that one strong candidate for dealing with this issue is to simply not list this "maqetta library" in the downlaod dialog, as #1512 suggests. However, we also need to do some cleanups with "maqetta library". Currently, my favorite idea is that States.js should merge into Maqetta.js so we only pollute user workspaces with one Maqetta JavaScript file, not two.

**Comment by jhpedemonte** [comment]
"maqetta" lib is now hidden.  Closing.
