### ISSUE TITLE
Mobile_Theme_Editor tutorial: Instructions for changing font size don't work

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#1937]
The instructions say:

> 1. For the 'font-size' property, click on the "+" icon twice to change font size from 14px to 16px.

But, nothing happens when clicking the "+" icon. Is it supposed to? Or, must the user enter "14px" into the field before clicking the "+" icon?

**Comment by jhpedemonte** [comment]
@childsb, didn't you fix the regex dealing with this?  Causing issues, or something else?

**Comment by JonFerraiolo** [comment]
I think this issue is more about some of the shenanigans that @billreed63 and @jonferraiolo had to do with the mobile theme editor where we are intermixing Maqetta content with actual dojox.mobile widgets within the same frame. I think the shenanigans need some tweaking, but too late to attempt a fix for this release. Instead, I'll update the tutorial for M5 and create a new issue to try to get the global font-size to appear in Properties palette: #1938
