### ISSUE TITLE
Exception opening editor: TypeError: s is null from getStyle

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#1946]
@JonFerraiolo 

Seen on Firefox with build

Saw this when cloning a theme.  ThemeEditor came up empty with both loading symbols spinning and no lingering network activity.  Firefox popped up a message for this unhandled exception on the console.

```
TypeError: s is null
getStyle()dojo.j...b22dde8 (line 3880)
undefined = "[object HTMLSpanElement]"
undefined = ""position""
(undefined="[object HTMLSpanElement]", undefined=""position"")dojo.j...b22dde8 (line 1517)
(undefined="[object Object]")davinc...b22dde8 (line 22155)
(undefined="[object Object]")davinc...b22dde8 (line 22257)
(undefined="[object Object]", undefined="[object Object]")davinc...b22dde8 (line 22240)
(undefined="[object Object]", undefined="0", undefined="(void 0)")davinc...b22dde8 (line 45748)
(undefined="[object Object]", undefined="0", undefined="(void 0)")davinc...b22dde8 (line 45616)
(undefined="[object Object]")davinc...b22dde8 (line 45665)
(undefined="21")
```

In the debugger, the stack looked like this:

```
get(node=span.dijit, name="position")
style(node=span.dijit, name="position", _14e=undefined)
move(box=Object { l=6, t=6}, event=undefined)
_resize(box=Object { x=0, y=0, w=0, more...})
resize(box=Object { x=0, y=0, w=0, more...}, _122a=Object { domNode=span.dijit, id="Button_0", _params={...}, more...})
focus(state=Object { box={...}, op={...}, hasLayout=false, more...}, index=0, _2040=undefined)
updateFocus(_202f=Object { domNode=span.dijit, id="Button_0", _params={...}, more...}, index=0, _2030=undefined)
select(_2034=Object { domNode=span.dijit, id="Button_0", _params={...}, more...}, add=undefined, _2035=undefined)
(?)()
```

this seems to track back to this line in the VisualEditor constructor:

```
setTimeout(function() { visualEditor.getContext().select(visualEditor.getSelectedWidget()); }, 100); //FIXME: should call updateFocus
```

**Comment by jhpedemonte** [comment]
cc @billreed63

**Comment by JonFerraiolo** [comment]
What was going on before you cloned the theme? I'm wondering if you might have had a page editor or theme editor open earlier in the session, and the `this._selected` property in Focus.js might be stale. 

Incidentally, I have found countless exceptions when calling dojo.style and some other dojo functions (dojo.global?) because those functions assume the ownerDocument and ownerDocument.defaultView have values, but because of browser timing issues, sometimes those values aren't put on every DOM element immediately. I'm thinking we should have Maqetta front-ends (or replacements) for some of the Dojo utilities and the Maqetta versions makes sure we don't attempt to reference through an undefined.

**Comment by peller** [comment]
I'm thinking the timeout error isn't significant, and there must have been an exception in the main code as well which wasn't reported.  Hopefully 7f7062c310dd2514ccb2572d6fcbd74bc80199e4 will make it easier to spot.

**Comment by peller** [comment]
@JonFerraiolo not sure, but there's got to be more to this story.  I don't think the failure in the timeout itself would keep the editor from rendering.  Perhaps it was something more drastic, like the context being null.
