### ISSUE TITLE
Client-side inactive session logic

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1949]
@childsb, @peller, @jhpedemonte 

@billreed63 has pointed out a chicken-and-egg problem with RIAs that work with a server that times out after a period of N minutes. 

The chicken-and-egg problem is that the client really should include periodic heartbeat checks with the server to see if the server has timed out, and if, then immediately redirect user to appropriate UI for them to login in again, but if the client asks the server for something, the server will no longer timeout. For M5, we are dealing with this chicken-and-egg problem by checking all XHRs for failure via 401 or 403, and if so, then transition towards a login screen. But this approach usually means the user needs to try to change a document in order to trigger an XHR. It would be much better if we ended the client-side session when the session timer expires and not wait for the user to attempt to change a document (and then have that change fail).

@billreed63 points out that many sites, particularly banking sites, appear to have a client-side session timer that looks for N minutes of client-side inactivity. This seems like a good solution to me. What we could do is have the server timeout default to 60 minutes, but have the client timeout at a smaller value (e.g., 15 minutes). Then try to instrument the client to notice user activity, and restart the 15 minute timer whenever the user does anything "significant".

The question is what actions would be "significant" and how could we instrument the JavaScript to notice these actions? Here are some things we could check:
- Any mousedown, mouseup, or keypress events could constitute a significant user action
- Any communications with server could constitute a significant user action (XHRs would be easy to catch, other stuff might be impossible)
- Any command stack executions could constitute a significant user action
- Any "actions" (invoking things in the actions/ folders) could constitute a significant user action
- Any others?

**Comment by peller** [comment]
so unless we limit our timer to xhrs, we'd still need to implement a heartbeat, we'd just be tying it to something like mouse events, user actions, etc.?

The other approach seems to be to try to reauthenticate from within the app as needed.  I don't recall whether there were inherent problems with that approach or if we just opted to go with a simpler redirect.

**Comment by billreed63** [comment]
We could have the heartbeat inside the timer. get the season timeout value from the server and keep track of the last time we sent to the server, If we will timeout with the server before the next timer pop we could do a heartbeat.

**Comment by billreed63** [comment]
Good example http://www.erichynds.com/jquery/a-new-and-improved-jquery-idle-timeout-plugin/

**Comment by jhpedemonte** [comment]
So what are you thinking of doing here, Bill?  Could you detail your approach please?

**Comment by billreed63** [comment]
1) We get the server inactivity time out from the server by adding a command to the server to return the MaxInactiveInterval
2) Set timeout in the client to the MaxInactiveInterval - 1 minute , when this timer pops we let the server no we are still alive
3) We subscribe to the '/dojo/io/load' this dojo publish this message whenever a xhr with the server completes successfully. When we see this message we reset the timer in step two.
4) we set a user idle timer to the MaxInactiveInterval - 1.5minutes.  
5) We connect to "mousemove", "keydown",  "DOMMouseScroll", "mousewheel",  "mousedown"  when we catch one of these events we reset the timer in step 4
6) If the timer pop's in step 4 we display a message (div) that tells the user they will timeout in 30 seconds, and we update the div with a count down. If we get to 0 we logoff the user. If the user reacts to the message it fires an event in step 5 and we reset the timer in 4.

So the server will only be polled once when we start up to get the MaxInactiveInterval and then only if it has been MaxInactiveInterval  since the last time we have connected with the server and the user is still working with the client. 

Here is an example use case we want to address:

If the user is doing a review of a theme say a presentation and the admin of the server set the timeout to 10 min.. The user is moving the mouse around the screeen or just talking for 9.5 minutes.. we put up a warning in the client that they are about to timeout.. they say nuts! and move the mouse... We then want to tell the server we are still here don't  wack us

**Comment by billreed63** [comment]
Fixed by commit e0a35a376905c5eca5735ec47539d20b5c577345

**Comment by billreed63** [comment]
single user should never timeout. Also, I think there is a bug that we shipped with M5 where single users are timing out and are redirected to /maqetta/welcome instead of /maqetta
 is the redirect in the javascript? If so, then we probably need a conditional to check for single user.
