### ISSUE TITLE
Adding comment to review timestamp says "2 hours ago" for newly added comments

### ISSUE THREAD

**Issue by doronrosenberg** [maqetta/maqetta#1969]
Add a comment to review and the timestamp says "2 hours ago".  Firefox/Chrome on windows

**Comment by peller** [comment]
are times being stored in GMT?

**Comment by jhpedemonte** [comment]
-> M6/Med

**Comment by doronrosenberg** [comment]
I should be clear, I am in PST.

**Comment by doronrosenberg** [comment]
Still seeing at http://lab9.austin.ibm.com:50020/maqetta/

**Comment by peller** [comment]
yeah, "created" has its own logic, which is suspect.  It's sending the date in seconds since the epoch instead of iso format, but that shouldn't be a problem. Some other things are suspicious.  In particular, `org.davinci.server.review.Utils.getCurrentDateInGmt0` Why is it necessary to subtract an offset?  Pushing back to M6.

**Comment by peller** [comment]
@waynevicknair, please review
