### ISSUE TITLE
Joomla: Login redirect sequence going to home page

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#2000]
@JonFerraiolo @childsb 

someone invites you to a review, and you click on the link, it takes you right to the maqetta.org page.  Same for server timeouts.  You have to click the link to log in yourself.  You should be redirected to the login page.

**Comment by JonFerraiolo** [comment]
-> @jhpedemonte (so this doesn't fall through cracks)

**Comment by jhpedemonte** [comment]
@JonFerraiolo @childsb, either of you know the code in which to fix this?

**Comment by JonFerraiolo** [comment]
I think it's davinci.joomla/WebContent/welcome.html, which is just a redirect:

`window.location = "http://" + window.location.hostname + "/";`

Maybe we need to change it to:

`window.location = "http://" + window.location.hostname + "/login.php";`

and then we can have `http://maqetta.org/login.php` do a redirect to the joomla page with the login dialog:

```
http://maqetta.org/index.php?option=com_user&view=login&return=aW5kZXgucGhwP29wdGlvbj1jb21fY29udGVudCZ2aWV3PWFydGljbGUmaWQ9NTQ=
```

(I'm thinking we wouldn't want to hardcode this latter screen into our source code in case we decide to rearrange things on the web site.)

(Note: the funny `return` URL value is critical because it tells Joomla where to go after login is completed. WIthout it, after login, the user goes back to the maqetta.org home screen. With it, after login, user goes to the "Launch Maqetta" page.)

I tested this on maqetta.org by creating file http://maqetta.org/jontest.php.

**Comment by jhpedemonte** [comment]
Re-assigning to @JonFerraiolo, since he seems to know what he's doing!

**Comment by JonFerraiolo** [comment]
I have installed a login.php onto Maqetta.org. Needs to be copied to our staging/testing server.

I updated welcome.html with db85d7f079 

Now we need to test on staging server. Probably shouldn't close this issue until we have tested on maqetta.org.

**Comment by JonFerraiolo** [comment]
Didn't work. I looked into this some more and to my surprise discovered this code in pagedesigner.html:

```
                    var isRunningJoomla  = dojo.cookie("DAVINCI.JOOMLA");
                    if (isRunningJoomla) {
                        dojo.byId('davinci_logoff').href = "http://" + window.location.hostname + 
                            "/index.php?option=com_user&task=logout&return=Lw";
                    }
```

Blame found this commit: 84339ee9ed168e57c4e093bf67d2ce467c13a685

I'm not sure yet what to do about this. Maybe I should revert db85d7f and just change pagedesigner.html for the time being.

**Comment by JonFerraiolo** [comment]
After discussion with @childsb, we are likely to have totally different login/logoff behavior with M7, and any changes for M6 will be short-lived and introduce significant risk. I'm inclined to push this to M7 but before doing so, I will deploy a new build to the staging server and go through steps in this bug again.

**Comment by JonFerraiolo** [comment]
Verified that things are working as they did with M6 with new build on staging server.

Pushing to M7.

**Comment by jhpedemonte** [comment]
No longer relevant, as we are using Orion to handle authentication.
