### ISSUE TITLE
simplify Context.onContentChange autosave

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#2044]
right now, onContentChange creates a timer (0ms) to call _autoSave.   _autoSave is already on a timer to run periodically. Perhaps we can just set the dirty bit on the editor instead?

**Comment by JonFerraiolo** [comment]
I'll take this one. I've been into the _autoSave logic before.

**Comment by JonFerraiolo** [comment]
I investigated this and am closing this issue. Let's leave this one alone. What's going on is that there is an `_autoSave` function in Workbench.js that gets called in two separate places:
- Context.js calls `_autoSave()` immediately whenever a change happens to one of the user's HTML documents so that if a user adds a widget or moves a widget or changes a property, that operation is immediately persisted up on the server to prevent data loss (versus waiting up to 30 seconds for the next autosave to occur, which might never happen if user navigates away or disconnects his computer from network). I don't remember why there is a setTimeout() with length zero, but there probably was a reason, and in this particular case it seems harmless since the 30 second autosave logic is already doing an asynchronous save.
- Workbench.js calls `_autoSave()` every 30 seconds. This is a safety feature just in case there might be some changes to user HTML documents that don't go through the CommandStack. But this feature also covers our various others editors (JS, CSS, maybe theme editor). I'm pretty sure the text editors don't have any immediate save logic at this point, and I'm not sure about what happens with the theme editors.

So, there isn't a setTimeout within a setTimeout. Just two separate setTimeouts that end up invoking the same utility routine.

**Comment by peller** [comment]
Right, didn't mean to suggest there was a timeout within a timeout, just undesirable autosave logic which happens to be wrapped in a timeout for reasons we don't understand.  I believe there are cases where the workbench autosave timer does properly batch requests, such as typing in the editor, and it relies instead on the dirty bit.

I think a 30 second window is perfectly acceptable for catastrophic data loss, and we should handle the navigate/browser close option.  We should at least be batching these things to the server doesn't get pummelled, preferably using the same autosave logic or all operations, and using a dirty bit would prevent the need for the setTimeout, whatever it was, leading to cleaner code.  If 30 seconds is too long, we can make it shorter.

**Comment by peller** [comment]
@jhpedemonte

**Comment by JonFerraiolo** [comment]
I strongly disagree that "a 30 second window is perfectly acceptable for catastrophic data loss", especially since this isn't an act-of-nature kind of a situation (e.g., hurricane, earthquake) but instead a normal usage situation. In normal usage, people change a document, then immediately close their computers, unhook their network cables, go out of wireless range because they are using mass transit, or navigate to different pages. 

Also, even putting the data loss issue aside (which is sufficient argument for instant autosave), going forward, we want to support simultaneous authoring by multiple people just like Google Docs. That won't work with 30 second windows.

But batching of operations that happen in quick sequence with each other (e.g., within .5seconds of each other) like we do with keyboard events in the text editor is something to consider. However, remember that this instant autosave only happens when the command stack is flushed. That doesn't happen very often. It is uncommon for there to be a quick sequence of multiple different command stack flushes. We already do a batching with the command stack (i.e, CompoundCommand).

**Comment by JonFerraiolo** [comment]
Further, I think this worry about too much chatter is misplaced. Look at google suggest, which sends a new message to server with every key you type into a text field. It is now common practice in Ajax techniques to have a lot of chatter. 

Continuing on with my rant above, in typical usage with Maqetta, an active user using the visual editor to create UIs probably ends up doing roughly one command every 20 seconds. With the instant autosave, we are sending updates to server every 20 seconds, and in general sending roughly the same number of server messages as we would with the 30 second interval, except with instant autosave there is no data loss, whereas there are lots of data loss if we just had the 30 second interval. (And I know about the data loss - it used to bit me all of the time)

**Comment by peller** [comment]
I'll repeat: browsing away from the page, we can cover that programmatically.  If we're not, we should be doing this with `window.onBeforeUnload`  That's not catastrophic by any means.  Pulling out a network cable isn't something I think we should consider an everyday event, but when they plug it back in, our autosave should kick in. (Aha!  A bug?  #2048)

**Comment by peller** [comment]
From a standpoint of code quality, I think we should have a single autosave mechanism, and using the dirty bit/polling mechanism would avoid a kludgey setTimeout and direct call.  If the 30 second window is too long, it's adjustable.  Perhaps it should poll for the dirty bit every few seconds?

**Comment by jhpedemonte** [comment]
I agree with both of you!

I understand what Jon is saying about trying to make the autosave as instantaneous as possible, but I also agree with Adam, that there should a single bit of code that handles the auto-save logic for all editors.  As Adam suggests, we can have the check kick quite often (every 5 seconds? 2 secs?) -- this would then batch any changes together at that time.

If for nothing else than to make the code cleaner.
