### ISSUE TITLE
Eclipse Development Environment Suggestions

### ISSUE THREAD

**Issue by rbackhouse** [maqetta/maqetta#2072]
I have a couple of suggestions for making the Eclipse Development environment easier to use/setup.

1) Create an Eclipse targetplatform zip that contains the supported runtime maqetta depends on. 

The advantages to doing this are : 

a) You can move the thirdparty/binary dependencies (dojo, commons-io, fileupload etc) into the targetplatform and remove them from the git repo. 
b) Eclipse Runtime Versioning issues are better controlled as the project now controls the version used vs the developer who is using the runtime from the eclipse version they have downloaded.

A .target file can be provided within the repo that enables easy setup, Simply download the targetplatform zip (could be from the downloads section in github) and unzip. Open the .target file and use the "Set as Target Platform" link.

2) Create Eclipse Features and use the Feature based equinox launches instead of the bundle based ones.

The bundle based ones are notorious for becoming "modified" by simply opening via "Run Configurations" menu option. The feature based ones do not suffer this issue.

**Comment by jhpedemonte** [comment]
cc @childsb @peller @JonFerraiolo

**Comment by JonFerraiolo** [comment]
-> @childsb so this doesn't fall through cracks

**Comment by jhpedemonte** [comment]
-> M8

**Comment by JonFerraiolo** [comment]
-> @jhpedemonte M8 Prio-Med

**Comment by jhpedemonte** [comment]
A lot of this has been handled by the move to building on top of Orion.  Build and launch are done based on features.

For [target platform](https://github.com/maqetta/maqetta/wiki/Maqetta-with-Orion-Developer-Setup), the user can either download the last Maqetta release (or a nightly) or an Orion release.  That handles most 3rd party dependencies.

For Dojo and GridX, we've moved to using Git submodules.  Since these are updated regularly, I think that's the best solution, rather than pushing that off to a separate download (target platform).

@rbackhouse, anything left that we should take care of?

**Comment by rbackhouse** [comment]
No, I think all of it has been covered now. Thanks
