### ISSUE TITLE
In Source view, increase window width - design view starts peeking through

### ISSUE THREAD

**Issue by doronrosenberg** [maqetta/maqetta#2077]
Go into source view and increase the window width - the design view will start peeking through in the left.

**Comment by peller** [comment]
this is because the split view was implemented with BorderContainer, and the design view is in the center position, which gives it flexibility.  The other panels are defined to have fixed height/width.  I think this is a limitation of the BorderContainer approach unless perhaps we swap which regions.  As it is, this code is pretty fragile.

**Comment by peller** [comment]
-> M7

**Comment by JonFerraiolo** [comment]
I think the design/source/split logic is in PageEditor.js and isn't all that complicated. I believe we are using sizing tricks to make source view appear, whereas we should probably hide or remove the ContentPane for design view when source view is active.

I actually played around with PageEditor.js when chasing down something else, but didn't commit my changes. As I remember, there are some curious things about how it uses the 'center' region of BorderContainer. My thinking is that the center pane need to swap between source and design sometimes - when source-only, then it should contain source pane, when design-only, it should contain design pane. In split view, could be either one.

**Comment by peller** [comment]
Yes, in the bordercontainer layout, 'center' is defined as taking over free space, while the sides are fixed.  An arbitrary choice was made to make one of these center.  The bug could be fixed by dynamically swapping the region properties, if bordercontainer will allow it.  Otherwise, we'd probably have to re-construct the panels on the fly when a single panel is displayed, such that it is the 'center', or just remove the BorderContainer layout entirely for that case.  The original code sought to leave the instances alone.

**Comment by JonFerraiolo** [comment]
I played around and I found a way to swap source and design as the center pane. I don't remember exactly what I did, but I managed to get it working (without huge flashes). I'll look to see if I have a branch or stash with these changes.

_UPDATE_: sorry, I looked around and couldn't find any of my old code.
