### ISSUE TITLE
dojox.mobile.ComboBox popup menu not displayed

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#2079]
When a dojox.mobile.ComboBox is nested in a div element with absolute position the popup combo list is hidden

```
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8"/>
<title>Untitled</title>
<style>@import "themes/claro/claro.css";@import "lib/dojo/dojo/resources/dojo.css";@import "app.css";
</style>
<script type="text/javascript" src="maqetta/maqetta.js"></script>
<script type="text/javascript" data-dojo-config="'async':true,'parseOnLoad':true,'packages':[{'name':'clipart','location':'../../clipart'},{'name':'shapes','location':'../../shapes'},{'name':'jquery-ui','location':'../../jquery-ui'},{'name':'yui','location':'../../yui'}]" src="lib/dojo/dojo/dojo.js"></script>
<script type="text/javascript" src="maqetta/States.js"></script>
<script type="text/javascript">
require(["dijit/dijit"]);
require(["dojo/parser"]);
require(["dijit/form/DataList"]);
require(["dojox/mobile"]);
require(["dojox/mobile/deviceTheme"]);
require(["dojox/mobile/compat"]);
require(["dojox/mobile/ComboBox"]);</script>
</head>
<body class="claro" dvFlowLayout="true" data-davinci-ws="collapse" id="myapp">
 <select data-dojo-type="dijit.form.DataList" id="DataList_2" data-dojo-props="id:&quot;DataList_2&quot;">
   <option value="Item 1">
     Item 1</option>
   <option value="Item 2">
     Item 2</option>
   <option value="Item 3">
     Item 3</option>
 </select>
 <div style="background-color: white; z-index: 9999; position: absolute; left: 110px; top: 78px; width: 354px; height: 337px;">
  <input type="text" data-dojo-type="dojox.mobile.ComboBox" data-dojo-props="value:&quot;Item 1&quot;, list:&quot;DataList_2&quot;"></input>
</div>
 </body>
</html>
```

**Comment by billreed63** [comment]
When we change the position of the div to absolute we set the z-index to 9999, dojo creates the popup menu for the combobox and attaches the popup menu to the body with a z-index of 1000 so the popup menu is hidden by the div (note that the background-color of the div is set to white)

**Comment by JonFerraiolo** [comment]
Reassigning to me.

I changed my preference for z-index for absolute widgets from 9999 to 999, and now I see that the ComboBox appears above the DIV. I had set the default to 9999 because I wanted to be above all of the dojox.mobile widgets, but maybe I didn't think things through correclty and chose the wrong default value and instead should have picked a number under the z-index that dojox.mobile uses for popup. (And of course 999 has a very nice ring to it.)

A quick fix would be to change the default from 9999 to something under 1000. Note that there is an existing bug to re-evaluate the z-index approach: #1948

**Comment by JonFerraiolo** [comment]
I decided that a more robust solution wasn't feasible for M6, so I will be committing a bandaid fix soon which (for absolutely positioned widgets) will use 900 instead of 9999, and change StickyNote to 925, both of which will be less than the 1000 that is used for ComboBox. Yes, hacky and using inside knowledge of a particular library, but a more robust solution is too involved.
