### ISSUE TITLE
DataGrid throws exception on latest build

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#2105]
DataGrid throws exception when attemping to drop DataGrid on canvas. 

Stack

```
addJavaScriptModule(mid="dojox/io/xhrScriptPlugin", _2139=true, _213a=undefined)davinc...f0cbb2d (line 46952)
(?)(r=Object { type="javascript-module", format="amd", src="dojox/io/xhrScriptPlugin", more...})davinc...f0cbb2d (line 45537)
loadRequires(type="dojox.grid.DataGrid", _2053=true, _2054=undefined, _2055=undefined)davinc...f0cbb2d (line 45560)
_getCreateCommand(args=Object { parent={...}})DataGr...f0cbb2d (line 43)
_create(args=Object { parent={...}})DataGr...f0cbb2d (line 29)
(?)()davinc...f0cbb2d (line 21404)
_172()dojo.j...f0cbb2d (line 1711)
then(_17e=function(), _17f=undefined, _180=undefined)dojo.j...f0cbb2d (line 1771)
create(args=Object { target={...}, directTarget=null})davinc...f0cbb2d (line 21405)
onMouseUp(event=mouseup clientX=0, clientY=0)davinc...f0cbb2d (line 21264)
onMouseUp(event=mouseup clientX=0, clientY=0)davinc...f0cbb2d (line 46601)
(?)()dojo.j...f0cbb2d (line 4551)
```

**Comment by jhpedemonte** [comment]
This seems to have been exposed by the new GridX plugin.  There are 2 issues at play:
1. The GridX metadata references "dojo.data.ItemFileReadStore" in the "data" property and the metadata code makes the assumption that that widget belongs to the GridX library.  Then, when loading required resources, the code constructs a URL attempting to load that from GridX library.  _I think I have a fix for this, just need to test some more._
2. After fixing (1), I still get an error.  The issue seems to be that the code is trying to instantiate the DataGrid object before the widget files have finished loading.

---

The way to fix (2) is something that I mentioned to Adam: we need to use promises in `loadRequires()` so that subsequent code isn't loaded until we've finished loading the resources in that function.

@aerwin @peller

**Comment by jhpedemonte** [comment]
Actually, hold off on this.  It looks like I can drop a DataGrid just fine on **master**, but not on the **1750-one-require** branch.  Investigating now.

**Comment by jhpedemonte** [comment]
OK, I found my issue on the **1750-one-require** branch: I was setting `async: true` on the Dojo that is added to the VE iframe.  We weren't doing so on **master**, where things worked properly.

I assume that Dojo will eventually default to `async: true` for the loader, so we need to fix this.  Probably by doing what I [mentioned above](https://github.com/maqetta/maqetta/issues/2105#issuecomment-5364717).

---

Closing this bug, since I do not see this DataGrid exception on **master**.
