### ISSUE TITLE
ListItem - need a way to drag in items infront of label

### ISSUE THREAD

**Issue by doronrosenberg** [maqetta/maqetta#2118]
@JonFerraiolo @jhpedemonte 

This is probably a general feature - to show labels inside widgets as drag targets.  In ListItem I am not adding the label to children.

**Comment by jhpedemonte** [comment]
I don't understand.  ListItem supports several different internal components (see the image at top of [reference](https://dojotoolkit.org/reference-guide/1.7/dojox/mobile/ListItem.html)), one of which is the **"icon" property** -- it adds an image in front of the label.

But what would the user be dragging into the ListItem?

**Comment by JonFerraiolo** [comment]
@doronrosenberg  already implemented adding arbitrary widgets and elements inside of a ListItem. See closed issue #1799. The issue here is that if a ListItem current just has a text node, the solution for #1799 only allows adding the new widget after the existing text node. In some cases, users will want to add the new widget or element in front of the existing text node.

**Comment by jhpedemonte** [comment]
This has already been fixed, in M8 I believe.
