### ISSUE TITLE
Change project - widget palette doesn't show

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2146]
- Create new project. (When I saw this bug, my new project had the Eclipse support checkbox on, but I'm guessing that doesn't matter)
- New HTML File
- Add a dojo/dijit Button
- Go back to project1 (using combobox at top of Files palette)
- Go back to new project

Result=> Widget palette is empty even though an editor is open

**Comment by doronrosenberg** [comment]
@childsb 

Lets assume I have Project1:file1 and Project2:file2 after Jon's steps above.

So WorkBench.js:184 does:

```
var noSelect=state.editors[i] != state.activeEditor;
```

To determine if it should select a tab or not.  state being WorkBench._state.  In this case, the activeEditor is Project1:file1, while we are trying to load Project2:file2.

It seems the fix would be to set noSelect to false if activeEditor is not part of the currently loaded project.  Since I know nothing about how that works, does this sound ok?

**Comment by doronrosenberg** [comment]
Fixed by https://github.com/maqetta/maqetta/commit/1e9eba26f8d99e1f2f1480c74f4103958c5cd0da
