### ISSUE TITLE
DataGrid Smart Input: Specifying invalid JSON file causes Maqetta redirect to error page

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#2160]
1. Drop DataGrid onto page and see Smart Input Dialog come up
2. Choose "Data file from workspace" option
3. Bring up file dialog and choose a file without compliant JSON such as app.css [NOTE: In my case, I had previously uploaded a CSV file to the workspace to try and verify the CSVStore path.]
4. Click OK and see Maqetta redirect to:

```
Problem connecting to the Maqetta Server...
Return to Maqetta


Error description:

Unexpected identifier
```

In looking at the code, the `_getUpdateWidgetForUrlStoreCommand` function in `DataStoreBasedWidgetInput` creates an `ItemFileReadStore` pointing at the file and does a fetch. It looks like the `ItemFileReadStore` dies during processing the file, and Maqetta redirects before the onError function passed to the fetch call is executed.

The onError function's goal is to retry loading the data with a `CSVStore`, so aside from generally not handling "bad" files gracefully it would seem the CSV code path is broken as well.

**Comment by JonFerraiolo** [comment]
-> @jhpedemonte to assign to appropriate person

**Comment by doronrosenberg** [comment]
Yeah, this breaks CSV loading.  Perhaps we should have a checkbox for json/csv? This used to work

**Comment by doronrosenberg** [comment]
Workbench.js has handleIoError which is handling the IO error here.

**Comment by JonFerraiolo** [comment]
Obviously, we don't want handleIoError to kick in when user data files fail, only when the server fails to honor a command request.

**Comment by jhpedemonte** [comment]
I was hoping there was a way to query in `handleIOError` whether the original XHR request had an `onError` handler and if so, let it pass.  But that's not feasible, mainly because so many error handlers get added along the way, depending on how the XHR is invoked.

I'm thinking the best solution in this case is to filter/limit the cases in which `handleIOError` takes action.  Jon said it should only be invoked,

> only when the server fails to honor a command request.

If that is true, then we could easily check if the request's URL matches a server command path.  Right?

@peller

**Comment by jhpedemonte** [comment]
Another thought:  in this case, the var `reason` that is passed into `handleIoError` is an **Error** thrown by the dojo.xhr code, which tries to handle _app.css_ as a JSON file but fails.

However, we're only interested in I/O (network) errors here -- the above Error has nothing to do with I/O.  In `handleIoError`, should we ignore any invocation where `reason.status` is undefined?  Is there any other way to be sure that the error is I/O related?

And what about 404 errors?  I don't think we want to bring down the whole app if someone mistypes a URL.

This code catches way more than it should.  As in my previous comment, I think we need to **finely limit what errors are actually handled by `handleIoError`**.

**Comment by jhpedemonte** [comment]
One option: make this opt-in.  Provide an API allowing us to register **regex** for certain URLs.  Then if `deferred.ioArgs.url` (in handleIoError) matches any of the registered URLs, we call `Runtime.handleError`.

**Comment by peller** [comment]
opt-in sounds like the safest approach.  What do we need to catch besides .../cmd/\* ?

**Comment by jhpedemonte** [comment]
Side note: another thing I don't like is that `handleIoError` merely replaces the HTML on the page, leaving the JS context around.  In this case, it means that the CSV handler still fires and tries to do stuff, but fails, leading to an alert popup after the error "page" has been displayed.  Might be better to instead load a different page.

**Comment by jhpedemonte** [comment]
I just noticed that there is a major flaw in **DataStoreBasedWidgetInput.js** (and maybe other such helpers):  the objects for **ItemFileReadStore**, **CsvStore**, etc, are all being created in the context of the app, not within the context of the editor iframe.

In this case, it more or less works, because both the app and the iframe have loaded the same Dojo.  But this won't always be the case.

This would also be a workaround for this bug -- if ItemFileReadStore is loaded in the context of the editor iframe, then it will use the iframe's instance of dojo.xhr.  When the latter publishes the I/O error event, it won't fire the listener in the app context.

**Comment by jhpedemonte** [comment]
One function in **DataStoreBasedWidgetInput.js** was correct and was creating the data stores in the context of the page.  I cleaned up that code and fixed the other two instances.  Now I don't see the error any more, due to what I [mentioned above](https://github.com/maqetta/maqetta/issues/2160#issuecomment-5616174).

-> Closing as fixed.

**Comment by jhpedemonte** [comment]
I opened #2226 to track the issues with the `handleIoError` function.
