### ISSUE TITLE
Using shift key to contain polyline/arrow doesn't work correctly in flow

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#2169]
1. Add a bunch of widgets to a page in flow layout.
2. Start dragging a polyline or polyline arrow in the middle of the other widgets, such that as you add more segments to the line, the other widgets flow around, move.
3. With Shift key, start drawing new line segments at right angles.

Notice that when a new line segment forces the widgets to move (flow), the resulting line segment isn't actually constrained to a right angle.  Instead, it seems that it takes the point value **after** the widgets have flowed, resulting in non-90 degree angles.

**Comment by JonFerraiolo** [comment]
Closing as a "never fix" because I changed shapes to always come into a document using absolute positioning. It is still possible for a user to change a shape to position:static, and then this same problem would happen, but I don't see us ever prioritizing that scenario, so closing as a "never fix".
