### ISSUE TITLE
Need resizable modal dialog for reuse across Maqetta

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#2182]
@doronrosenberg @JonFerraiolo 

For the GridX wizard (and other parts of Maqetta like file dialogs, etc.), we have a need for resizable modal dialogs. Unfortunately, `dijit.Dialog` is not resizble. In addition, there is also an experimental `dojox.layout.FloatingPane` that's resizable, but not modal. So, we don't have anything readily available that satisfies both the modal and resizable requirements.

This task would be to explore possible options. For example, perhaps dijit.Dialog could somehow be extended. Or, perhaps we could create a new class based on FloatingPane that also creates a overlay div over the background to achieve modality. Or, perhaps there are other alternatives.

@JonFerraiolo suggested I create this and assign to @doronrosenberg . I'm also marking this is as High Priority for M6, so it gets discussed. But, priority can be debated and I'm guessing this would be more of an M7 thing.

**Comment by JonFerraiolo** [comment]
I also assigned related issues #286, #1165, #529, #319, #167 to @doronrosenberg . (It's likely there are some dupes in that list of bugs)

**Comment by JonFerraiolo** [comment]
It looks like Dojo doesn't offer anything that corresponds to a resizable-modal, but Dialog is auto-sizing, so what if the contents of the Dialog were placed inside of a DIV and that DIV was resizable? Then wouldn't the Dialog be resizable because it would resize itself based on the size of the containing DIV?

**Comment by doronrosenberg** [comment]
While its been a while, I remember we had a hard time adding and managing Underlays in BigSheets due to popup.js not providing access to the underlay management code.  Do subclassing Dialog is probably the best choice.

Probably do something similar for Maqetta.  Create Dialog class that allows:
- Passing in a title
- Passing in an array of objects for buttons at the bottom of the dialog: [{label: "", onClick: ""}, ...] with some options for built in buttons like OK/Cancel.  This allows us to manage button creation and thus making sure all dialogs place their buttons in the right place
- Resizable or not

As for resizing, putting a resizeHandle and marking the dialog as the target could work.  Probably 2-3 days of work to get this working and tested

**Comment by doronrosenberg** [comment]
While its been a while, I remember we had a hard time adding and managing Underlays in BigSheets due to popup.js not providing access to the underlay management code.  Do subclassing Dialog is probably the best choice.

Probably do something similar for Maqetta.  Create Dialog class that allows:
- Passing in a title
- Passing in an array of objects for buttons at the bottom of the dialog: [{label: "", onClick: ""}, ...] with some options for built in buttons like OK/Cancel.  This allows us to manage button creation and thus making sure all dialogs place their buttons in the right place
- Resizable or not

As for resizing, putting a resizeHandle and marking the dialog as the target could work.  Probably 2-3 days of work to get this working and tested

**Comment by aerwin** [comment]
One caveat in regard to being able to pass in an array of objects for buttons. It either needs to be made robust enough to handle more complicated scenarios (like the wizard below) or needs to be able to be overridden:

![R&C wizard](http://i.imgur.com/9DhxA.png)

**Comment by doronrosenberg** [comment]
We can handle that by not passing in any buttons, so the contents of the dialog would handle buttons.

**Comment by doronrosenberg** [comment]
New dialog image: http://imgur.com/ruP7y

I ended up not doing buttons as being json constructs but rather the dialog widget looks for a class name and moves that dom node into the actionbar - allows the current templates to be used and reduces the amount of new code we need

**Comment by doronrosenberg** [comment]
Fixed in rev b731265d00aeac3cd10e29fdfa113050c4c717af
