### ISSUE TITLE
Odd widget-placement issue with BorderContainer & ContentPane

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#2210]
1. Add an **AccordionContainer**.
2. Add a **BorderContainer** into _Pane 1_ of the accordion.  Accept defaults.
3. Add a **ContentPane** into the left-most pane of the BorderContainer.
4. Try to add a widget into the center-top or center-bottom panes of the BorderContainer.

I am unable to add a widget into those two regions (although center-center works fine) -- widgets are instead placed in the ContainerPane in the left-most pane of the BorderContainer.

Assigning to @JonFerraiolo for now, since you may have been around this code recently.

**Comment by JonFerraiolo** [comment]
I think the problem is that the last ContentPane added obscures the rest of the BorderContainer. ContentPane's default to 300x300, and the left region of the BC is very small (because the BC is inside of a 300x300 Accordion). When I select the CP and resize it so that it doesn't extend outside of its parent (which happens to be another CP), then I can drag/drop widgets into the center-top and center-bottom.

Reassigning to @jhpedemonte to decide if this can be closed, or reassign back if not.

**Comment by jhpedemonte** [comment]
Right, I understood what was going on.  However, I don't understand why -- why is the added ContentPane (a child of BorderContainer's left-most ContainerPane, itself a child of the BorderContainer DIV) getting precedence over the center-top and center-bottom ContentPanes?  And why isn't it an issue with the center-center ContentPane, even though it is also within the area of the added ContentPane?

Maybe this is just an HTML quirk and I'm not grokking.  Or maybe there's something wrong in our code.

**Comment by JonFerraiolo** [comment]
OK, I figured out what's going on. The DOM tree looks like this:

```
<div dojoType="dijit.layout.BorderContainer"">
  <div dojoType="dijit.layout.ContentPane" region="top">...</div>
  <div dojoType="dijit.layout.ContentPane" region="bottom">...</div>
  <div dojoType="dijit.layout.ContentPane" region="left">
      <div dojoType="dijit.layout.ContentPane" style="width:300px; height:300px;">...</div>
  </div>
  <div dojoType="dijit.layout.ContentPane" region="right">...</div>
  <div dojoType="dijit.layout.ContentPane" region="center">...</div>
</div>
```

Note that Dijit gives each of the ContentPane children of BorderContainer a z-index:2 (undoubtedly for a very good reason).

Because the region order is top, bottom, left, right, center, the left region (and all of its children) are "above" the top and bottom regions. However, the center region is "above" the left region. Therefore, is you attempt to drop into top or bottom, the inner ContentPane of the left region becomes the drop target, but it is possible to drop widgets into the center region.

**Comment by jhpedemonte** [comment]
OK, given the above, I'll close this as just a "browser quirk".
