### ISSUE TITLE
Mobile theme editor seems broken (JS errors and hang)

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#2228]
I see a couple other issues related to global background color, but I don't seem to be able to set anything. I've noticed a couple of big issues.
1. Browser hang when going to text props for any widget in theme editor (I'm using Chrome on Mac). I've had to Force Quit and restart several times now.

2 When trying to set background related props on any widget, I get the following JS error:

Uncaught TypeError: Cannot read property 'name' of undefined
_204a.modifyRule:50000/maqetta/app/davinci/davinci.js?5ff6aa4038cf97d6fc1aa6c8982fe9488805c1eb:46608
_ed1._modifyTheme:50000/maqetta/app/davinci/davinci.js?5ff6aa4038cf97d6fc1aa6c8982fe9488805c1eb:17550
_47.execute:50000/maqetta/app/davinci/ve/themeEditor/ThemeEditor.js?5ff6aa4038cf97d6fc1aa6c8982fe9488805c1eb:294
_1810.execute:50000/maqetta/app/davinci/davinci.js?5ff6aa4038cf97d6fc1aa6c8982fe9488805c1eb:31342
_2cc._propertiesChange:50000/maqetta/app/davinci/ve/themeEditor/ThemeEditor.js?5ff6aa4038cf97d6fc1aa6c8982fe9488805c1eb:3419
_383dojo.js:4551
_492.(anonymous function)dojo.js:6092
on.emitdojo.js:5349
on.emitdojo.js:5371
_396.emitdojo.js:4635
publishdojo.js:4685
_4b7.publishdojo.js:6255
_5b4._changeValue:50000/maqetta/app/davinci/davinci.js?5ff6aa4038cf97d6fc1aa6c8982fe9488805c1eb:6631
_5d1:50000/maqetta/app/davinci/davinci.js?5ff6aa4038cf97d6fc1aa6c8982fe9488805c1eb:6540
_5b4._onFieldChange:50000/maqetta/app/davinci/davinci.js?5ff6aa4038cf97d6fc1aa6c8982fe9488805c1eb:6594
_383dojo.js:4551
_492.(anonymous function)dojo.js:6092
_7c9._onChange:50000/maqetta/app/davinci/davinci.js?5ff6aa4038cf97d6fc1aa6c8982fe9488805c1eb:9097
_383dojo.js:4551
_492.(anonymous function)dojo.js:6092
(anonymous function):50000/maqetta/app/dijit/dijit.js?5ff6aa4038cf97d6fc1aa6c8982fe9488805c1eb:635
_383dojo.js:4555

**Comment by jhpedemonte** [comment]
I think this is what I ran into while running **Tests > Theme sets > Add new theme set**.  I'm not 100% sure, since the source was minified and I couldn't tell exactly where the debugger stopped:
- **Tests > Theme sets > Add new theme set**: Trying to change background color of "global widget" (I assume this means the **Global Background and Border** widget) throws error and background is not changed to desired value (becomes #efefef [grey] for some reason).
  - Same issue after cloning _custom_ theme.
  - Select **Global Styling** and try to set `font-weight` to **bold**.  Fails with error in console.
  - Get same error when trying to set Button to 200px using cloned claro (**Tests > Properties 4 > CSS Cascade feature**).
- This might also be same error I saw when trying to apply a **theme set** (**Tests > Theme sets > Applying theme sets**).

[Tested on Firefox 11 OS X]

---

Above was when running a **built release**.  I consistently got errors but no hangs.

Then, when running from source (latest code), I tried the same and now Firefox hung, displaying the dialog about a runaway script, asking if I wanted to end the script.

I clicked to debug the runaway script and the stack showed that I was in **Cascade._updateCascadeList()**.

**Comment by aerwin** [comment]
@billreed63 @jhpedemonte 

Got the latest '"external" GitHub-sources-only build' and installed it locally. I no longer see the exception or the hang when looking at font props, but I don't see any changes in props palette applied in the theme.

Using Chrome on Mac and cloned iphone theme.

**Comment by billreed63** [comment]
Related #2144

**Comment by jhpedemonte** [comment]
Still seeing some issues.  Testing on **Firefox 12/Mac**, on **lab9:50020/maqetta**:
- From **Tests > Theme sets > Add new theme set**, I cloned _claro_ and attempted to change the background color for the **Global Background and Border** widget.  While I did see the background change widget by widget, I constantly got the **Warning: Unresponsive Script** dialog in Firefox.  After clicking _continue_ a bunch of times, I had to give up and reload the page.
  - Before reloading, selected _debug script_ from the dialog and, sure enough, it broke in the **Cascade._updateCascadeList()**.  So there seem to be big performance issues with that function.
- Select **Global Styling** and trying to set `font-weight` to **bold** still fails.  In function `_onFieldChange()`:
  
  ```
  this._values[this._targetValueIndex] is undefined
  ```
