### ISSUE TITLE
DataGrid cannot be repositioned in absolute layout

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#2255]
1. Create new HTML file
2. change layout to absolute
3. Drop DataGrid onto canvas
4. Note you cannot move the DataGrid to a new location

In addition, if you do something like the following, when you drop DataGrid it's not placed correctly:
1. Create new HTML file
2. Drag a couple controls to canvas (e.g., Button and Calendar)
3. Change layout to absolute
4. Drop DataGrid onto canvas
5. Note DataGrid not placed where you dropped it (kind of placed further down on the page)

**Comment by JonFerraiolo** [comment]
@billreed63 

-> @JonFerraiolo M6 Prio-Med to investigate and see if there is a safe fix

**Comment by JonFerraiolo** [comment]
Similar problems with gridx in absolute mode. Of course, gridx is more important because we will be deprecating DataGrid.

When adding a gridx in absolute positioning, it looks like the position:absolute that Maqetta attempts to stuff into the widget gets overridden. If you restore position:absolute (eg in properties palette), gridx seems to work fine thereafter.

**Comment by JonFerraiolo** [comment]
Closing this. @aerwin has decommissioned DataGrid in favor of gridx. What's ironic is that I actually checked in fixes for DataGrid around absolute positioning in parallel with its decommissioning.
