### ISSUE TITLE
States Testing -- setting button font color on element.style not working

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#2260]
Going through the state testing ("Changing properties in different states" of StatesPalette/basic.html), I'm seeing a couple problems:
1. Instructions say to change button width, but there's no element.style available for button width (was sure this used to be there)
2. Changing font color of button on the element.style doesn't work (e.g., there's an element.style, but changing color to Red has no effect)

Awhile back,  I opened #1704 for background color of button, but I was sure I was previously able to set button width and font color.

**Comment by aerwin** [comment]
Apologies... guess instructions say to set calendar width, not button width. So, that part is just a dup of #1704.

The 2nd part (button font color) still seems like an issue.

**Comment by jhpedemonte** [comment]
cc @JonFerraiolo @billreed63

**Comment by JonFerraiolo** [comment]
-> @billreed63 @peller 

It looks like claro.css (since Dojo 1.6) has changed such that dijitButtonNode (an interior node) now explicitly sets color to black, whereas the version of claro.css that we have been using in user content is a pre-1.6 version of claro that allowed 'color' to inherit from the button's root node. This "bug" was introduced when we updated claro.css in davinci.dojo_1_7/WebContent/maqetta/themes

According to our existing conventions on how to deal with situations like this, we should change theme metadata to say that the node for 'color' is dijitButtonNode rather than the root node. I'm not sure what else to do....
