### ISSUE TITLE
"Only apply to current state" won't stay checked

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#2264]
1. Create new HTML file
2. Create a new state (say "test")
3. Drag/drop button onto canvas
4. Select Button
5. Open CSS cascade in props palette for font size
6. Change to 60px and check "Only apply to current state"
7. Deselect button
8. Reselect button (with "test" state selected) and see "Only apply to current state" is unchecked

**Comment by jhpedemonte** [comment]
cc @billreed63

**Comment by aerwin** [comment]
@JonFerraiolo Per scrum, this seemed to be more than just a stickiness issue (which I guess never happened).. but, bigger in that it didn't seem to apply the change to the current state.

**Comment by JonFerraiolo** [comment]
Returning to @aerwin - I wonder if the problem is the order in which you are doing the operations:

> Change to 60px and check "Only apply to current state"

The way the feature is designed, you have to check "Only apply to current state" and then change the value. The way the feature is designed now is that you click on the appropriate radio buttons to pick either element.style or a CSS rule to which the property change should apply, and you click on checkbox to say whether to apply the property change to the base state or a particular state, and then you change the property value, and when Maqetta processes the onchange event on the text field, it applies that change using the values of the radio buttons and "only apply to current state" checkbox as "context values" for that property change.

**Comment by aerwin** [comment]
@JonFerraiolo Yes, I think you're right. When I follow the order you suggest (and upon closer inspection the test case suggests), it works. So, I'll close. Though I do wonder if we have a UX issue we should think about addressing.

**Comment by JonFerraiolo** [comment]
@jmockler 

Regarding UX question, we need to rethink the whole UI with application states. I've run into numerous usability walls with the current UI. Just for starters, when you move a widget by dragging it around the screen, how does the user tell maqetta whether to change the base location (ie Normal) or only for current state? At the moment, the only hook we have for that is for the user to hold down the "s" keep while dragging. Besides being totally undiscoverable, this UI won't work for tablets (which have no keyboard). Latest UI mockups show a states strip along bottom of UI. If we go that route, then maybe we should have an toggle icon ('apply future operations to current state only') somewhere in that strip.
