### ISSUE TITLE
Weirdness with absolutely positioned div

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#2295]
Using FF on Mac...
- Create new HTML file
- Set layout to absolute
- Drag/drop a DIV onto page

![Screenshot](http://i.imgur.com/RWAtF.png)
- Drop Dojo button into DIV and end up with weird box

![Screenshot](http://i.imgur.com/DUKsU.png)
- Then, it seems like if I select the DIV in the outline it selects the right region, but the weird extra box stays around:

![Screenshot](http://i.imgur.com/1asY8.png)

**Comment by jhpedemonte** [comment]
cc @JonFerraiolo

**Comment by JonFerraiolo** [comment]
-> @JonFerraiolo Med maybe same problem as #2293

**Comment by JonFerraiolo** [comment]
This is a Firefox rendering bug with the 'outline' property. -> M7 @JonFerraiolo Prio-High to register a bug with the Mozilla folks.

You see, we have a CSS rule in content.css that puts a faint dotted gray outline around various container elements (DIV, SPAN, TD) in the page editor so that the user will be able to see those elements on the screen even if they have no content, no border and no background. Looks like we are using a feature that has bugs with the latest version of FF.

**Comment by JonFerraiolo** [comment]
@jhpedemonte @doronrosenberg FYI

**Comment by JonFerraiolo** [comment]
Restoring to M6 Prio-Med. Actually, this is pretty bad. Maybe we can think of a workaround. Best idea I have so far is to remove that rule in content.css for Firefox.

**Comment by doronrosenberg** [comment]
http://enotionz.net/2011/07/07/firefox-outline-overflow-fix seems to be the issue

**Comment by doronrosenberg** [comment]
Looks like adding overflow:hidden to the div "fixes" it

**Comment by doronrosenberg** [comment]
Not sure if we want to add that to the DIV.HtmlWidget declaration in content.css, could break other things
