### ISSUE TITLE
Login redirect for joomla build takes to maqetta.org login even if on staging server

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2313]
@childsb @jhpedemonte
- Post a Joomla build on a staging server
- Login to staging server, send review invitation to someone who is not logged into staging server
- Have that person click on review invitation

Result=> They get redirected to login page for maqetta.org and not the staging server

**Comment by aerwin** [comment]
I don't know if this is worse since the migration, but I'm just not able to get into Macwayne at all right now. I just keep getting redirected to maqetta.org when I click Launch Maqetta even after I logout/login again.

So, I'm going to raise this from Low to High. Also, this is assigned to me, but I don't have knowledge of Joomla nor am I set up in my dev environment for Joomla. @childsb any ideas?

**Comment by JonFerraiolo** [comment]
I'll take it.

**Comment by JonFerraiolo** [comment]
I believe I have fixed this two times. First, the login.php file on macwayne2 had a hard-coded redirect to maqetta.org. But I also did a revert with 97880952e7 which removes the change that caused login.php to be used in the first place.

Leaving this open pending testing with a new build on staging server.

**Comment by JonFerraiolo** [comment]
Verified this with new build on staging server. Closing.
