### ISSUE TITLE
Takes a few tries to switch projects

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#2322]
Noticed while doing migration testing on **macwayne2**.  Testing on Chrome 19/Mac.

When I try to switch between projects, it never works the first time.  It just reloads the previously set project.  Sometimes works if I try a 2nd time, but have also had to do 3 or 4 tries before it would actually switch.

**Comment by aerwin** [comment]
I saw this too... and even worse, after switching projects I can't open any files in the project I switched to:

SyntaxError
arguments: Array[1]
get message: function getter() { [native code] }
get stack: function getter() { [native code] }
set message: function setter() { [native code] }
set stack: function setter() { [native code] }
type: "unexpected_token"
**proto**: Error
:55556/maqetta/app/davinci/davinci.js?defb96fcb8e4aec1a5baae7b1458fbf03629aca4:4805Error opening editor for filename: ./project1/file1.html 
SyntaxError
_3c8.openEditor:55556/maqetta/app/davinci/davinci.js?defb96fcb8e4aec1a5baae7b1458fbf03629aca4:4805

**Comment by jhpedemonte** [comment]
I had no problems opening files once the switch actually happened.

**Comment by aerwin** [comment]
Don't know if it matters, but an Eclipse-enabled project I had created was my default when I logged in. I then switched to a regular project.

**Comment by aerwin** [comment]
More info... I just did/saw the following:
- Created a completely new project (called `newproject`) and HTML files appear to work there. 
- Tried to switch back to my problematic project (`project1`) and after several failed attempts, refreshed the browser page and was then finally able to switch back to `project1`
- Then in `project1` I saw that HTML files still fail to open
- Tried to switch back to `newproject` and was never able to (despite refreshing browser page and logging in/out)

**Comment by childsb** [comment]
ok so here's what seems to be happening:

1) the migration copied .theme files to .theme.bak, and somewhere.  
2) our theme logic isn't differentiating between userTheme.theme and userTheme.theme.bak.
3) HTML files that have a custom theme are erroring out on load because they are getting the .theme.bak file instead of the .theme
4) active editors with these custom theme files are making the project switch feel like its freezing when it's the visual editor locking up.

simple solution is probably not to create the .bak files during migration.

**Comment by jhpedemonte** [comment]
I did nothing with themes during migration (see commit e85d6505c4abe0ef139a152eba9f05d19a119b44).  So where did the **theme.bak** files come from?
