### ISSUE TITLE
Test plan for cut/paste widgets across page editors

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#2370]

**Comment by aerwin** [comment]
-> @aerwin

**Comment by aerwin** [comment]
Closing with above commit.

**Comment by riksoft** [comment]
cut/paste doesn't work in source page neither.

**Comment by JonFerraiolo** [comment]
A simple copy/paste across pdates in source editors worked for me just now, so it's not universally broken. Note that any changes in source editor pushes on fragile parts of the product. For example, if the resulting HTML source code doesn't have balanced start tags and end tags, the page will likely get corrupted.

**Comment by riksoft** [comment]
It would be nice to have the copy/cut/paste working because expecialli at the beginning it is very useful to copy examples from tutorials.
It is also useful for speeding up the GUI coding (in Eclipse or other editor) using maquetta only as an helper/reminder (especially at first maqetta can be a sort of cyber professor for learning how to code the GUI).
Sincerely, I don't think I'll ever use maqetta for a real work because I don't like to loose control on the code and because I don't like how it formats the code, but admittedly can be useful as a master and helper... if it only had cut and paste working.
