### ISSUE TITLE
HTML fieldset renders incorrectly (because of document.css)

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#2392]
Working through "&lt;fieldset&gt;and &lt;input&gt;" section of Widgets: HTML test case, the fieldset is not rendering correctly. Inspecting the element in the developer tools, it looks like document.css overrides the settings for fieldset to turn off the border:

![inspect element](http://i.imgur.com/j2jyL.png)

**Comment by aerwin** [comment]
So, final result of test scenario looks like:

![screenshot](http://i.imgur.com/R7dm2.png)

instead of:

![screenshot](http://i.imgur.com/XbtIW.png)

**Comment by jhpedemonte** [comment]
-> @JonFerraiolo

**Comment by JonFerraiolo** [comment]
Closing this. 

We had the same behavior in Preview 5 once the first Dojo widget was added. The first Dojo widget caused the claro theme and dojo.css to get added to the page. Now with Preview 6, we include document.css (pretty much equivalent to dojo.css) at document creation time. So, the only difference is in the case where a user doesn't use any Dojo widgets, which I suspect won't happen very often.

We have to include document.css for desktop UIs, otherwise the widgets will look wrong (in the minds of the designers of the claro theme). 

Regarding how this overrides the default styling that the browsers provide, well, we'll have to assume that the claro designers had a good reason for this. It probably has to do with fieldset used in combination with a particular Dojo widget scenario. We'll just have to deal with this from an education, documentation and support perspective. We could ask the Dojo folks to change document.css, but I really doubt they would indulge us because they would fear changes might mess up existing apps.

There is on open bug where the Properties palette isn't showing the cascade for the rules in document.css (#2378). If we showed the rules from document.css, it might help some users figure out how to work around it. (workaround: just setting border and margins on the fieldset element in properties palette)

**Comment by aerwin** [comment]
@JonFerraiolo Ok, then do we want to remove fieldset from the palette? It's really pretty worthless as it is now with the style overrides.

**Comment by aerwin** [comment]
Or, maybe in the metadata for fieldset, I initialize style to "border:2px groove threedface;" to compensate for dojo overriding fieldset globally?

**Comment by JonFerraiolo** [comment]
> in the metadata for fieldset, I initialize style to "border:2px groove threedface;"

yes, that sounds like a reasonable solution

**Comment by aerwin** [comment]
Closing with above commit.
