### ISSUE TITLE
404 for document.css when opening migrated theme

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#2400]
Opened up a theme migrated from an M5 workspace and got a 404 error trying to load:

```
http://hostname:55556/maqetta/user/username@company.com/ws/workspace/project1/themes/pink_iphone/document.css
```

@billreed63

**Comment by JonFerraiolo** [comment]
One possible solution is to install document.css into any custom desktop themes (but not mobile themes). But I wouldn't bother. Only problem is that document.css doesn't load and claro-based themes will have font sizes that are too big. (But maybe not if they were including dojo.css in their HTML files) (BTW - we already have such a harmless 404 error in M6 with mobile themes.)

I'm really skeptical about migrating old themes from M5->M6 because we have totally changed the way things work with the new delta theme approach. We should really abandon the old themes and tell people to redo them. But if users insist on trying to use M5 themes and they notice this problem, we can tell them how to install document.css into their custom theme folder.

**Comment by peller** [comment]
the error is harmless, right?

**Comment by JonFerraiolo** [comment]
yes, the 404 is harmless.

**Comment by JonFerraiolo** [comment]
Incidentally, I tried to edit one of my migrated themes from M5 and theme editor in some cases will generate an exception and in other cases no exceptions but changing properties doesn't actually do anything. Goes to show that migrated themes are really not all that viable.

**Comment by jhpedemonte** [comment]
So should we do anything for M6?  Load a dialog saying that the theme was created with a previous version and therefore may not work well with the current theme editor?

What about post-1.0?  We'll need to have a strategy for handling migration of themes -- we can't always tell users to recreate their themes for each new release.

**Comment by JonFerraiolo** [comment]
Closing this issue. I created a versioning/migration issue for M7: #2408

**Comment by JonFerraiolo** [comment]
Other related M7 bugs: #2378,#2381, #2377
