### ISSUE TITLE
Dojo Containers test case: "infinite" scrolling in FF

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#2421]
FF on mac using macwayne... following "Dojo Containers" section of "Widget palette basic tests":
1. New HTML file
2. Drag AccordionContainer onto canvas
3. Drag BorderContainer onto Canvas
4. Try to scroll to bottom of page to keep adding widgets and end up with "initinite" scroll

**Comment by jhpedemonte** [comment]
-> M7

**Comment by JonFerraiolo** [comment]
@peller 

Pushing to M7.

I was able to reproduce this, and in investigating, I'm pretty sure the issue is that BorderContainer keeps setting its height to be the px size of the whole canvas, and then you get into a loop because the canvas keeps growing, and BC keeps changing its size, etc. Might be triggered by our calling resize() at various points on widgets.

Multiple ways to address this one.

**Comment by peller** [comment]
@JonFerraiolo 

The issue is that we put 100%x100% on all of our BorderContainers.  This is only valid when it's the only item on the page.

**Comment by JonFerraiolo** [comment]
> The issue is that we put 100%x100% on all of our BorderContainers.

yes, that's right, we should only put 100%x100% if the BC is the only child of BODY or ContentPane.

**Comment by aerwin** [comment]
Thinking I should try and handle this (the not setting 100% on height if more than one child) as part of my approach for #2396...

**Comment by aerwin** [comment]
-> @aerwin (to be handled as part of #2396)...

**Comment by aerwin** [comment]
Closing as part of #2396 (commit fe8b89b562308460c15349e43e8d73cd629b55f6 )
