### ISSUE TITLE
Theme editor changes saved despite not saving

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#2453]
1. Clone claro theme
2. Select text box in theme editor and change a property (e.g., change font color to red)
3. Click X on theme editor to close (note message that continuing with cause changes to be lost)
4. Reopen theme editor and styling is same as before closing (e.g., font color of text box is red)

**Comment by billreed63** [comment]
the working copy of the css file is not being removed

**Comment by billreed63** [comment]
The theme editor and the page editor are not removing working copies of the CSS files when the editors are closed without saving. We need to be careful removing working copies of css files as they may be shared with other open editors that are changing the same file. The resource should be a singleton, but we currently do not have a way to tell if we are the last editor with a reference to the file.

1) we could remove the working copy of the CSS file when the editor closes and leave the dirtyResource flag set, hoping that and auto saving from the other editors that have the file open will restore the working copy. I have questions about this approach:

a) How often does auto save happen, is it only after a change in another editor? or on a timed bases

> auto save only happens on a model change, so if we close one editor but close the browser without exiting the editor tab we could loss changes.

b) How does the dirtyResouce get set for other editors, could one save a dirty CSS file unintentionally? 

> It looks like the dirtyResource stays set to true as long as someone has a reference to the singleton.

**Comment by billreed63** [comment]
@JonFerraiolo @childsb

**Comment by billreed63** [comment]
After spending a good bit of time understanding the Factory here is the plan of attack:

a) Ensure that all CSSFiles and HTMLFiles are created using `Factory.getModel()` the Factory keeps track of the number of references to a singleton for each unique file.
b) Ensure that destroy() is called for theme and page editor, witch will call `closeModel` for each file. `Factory.closeModel``` decrements the reference count when each singleton is return.
c) Move the code the remove the working copy of a file from the editor to`Factory.closeModel```` when the count for an instance of a singleton reaches zero we will remove the working copy of that file. We can do this bit of code here, because  when the user close the editor tab we check to see if the resource is dirty. If the resource is dirty a message is displayed to the user that changes will be lost if they do not save them. if the user clicks ok then we are free to remove the working copy on the last instance. <b>NOTE we need to ensure that the dirtyResource is set for any CSSFile or HTMLFile model change by any editor, and that we display the warning lost of data if we are switching themes and the resource is dirty </b>

**Comment by JonFerraiolo** [comment]
Plan sounds very good. 

Do we take care of the possibility that there might be workingcopy files for things that aren't currently open in an editor (where the user's project is in a bad state)? For example, maybe the user encounters a bug in Maqetta and the workbench.Settings file isn't correct or complete, or maybe the user confused Maqetta by running two browsers windows at the same time, or maybe they said `?resetWorkbenchState=1` I know that refreshing the browser will reopen editors listed in workbench.Settings, but do we have a robust approach for recovering when workingcopy files aren't listed in workbench.Settings?

**Comment by billreed63** [comment]
We also need to warn user before switching devices, as it changes the mobile css files

**Comment by billreed63** [comment]
@JonFerraiolo states that we throw an exception on saveAs

**Comment by billreed63** [comment]
ensure that the dirtyBit is correct when page is loaded

**Comment by billreed63** [comment]
fixed by above commits
