### ISSUE TITLE
Document.css appears to be missing in review editor

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#2462]
Doing R&C testing with @peller & @billreed63 this morning, and we all see incorrect rendering in the review editor (like document.css is missing). 

I created the review and when I open the same file in the page editor, it looks correct.

Review Editor:

![screen shot](http://i.imgur.com/he1EH.png)

Page Editor:

![screen shot](http://i.imgur.com/wGJHg.png)

**Comment by JonFerraiolo** [comment]
@aerwin, @peller & @billreed63 - thanks for doing the testing 

Question: were you using Sample1.html from a migrated workspace (i.e., an old workspace from Preview 5)? Any chance you could try again doing the same thing after create a new project?

**Comment by aerwin** [comment]
I had created a fresh project just before the testing.

**Comment by JonFerraiolo** [comment]
I figured out what's wrong. It's just the sample files (which don't have document.css for either reviews or preview-in-browser).  The sample files need to have an `@import "document.css";`. 

If you open Sample1.html and save it as Sample1a.html, the page editor fixes up the file and adds `@import "document.css";` to the HEAD, and then both preview-in-browser and reviews will now look correct. Basically, any user files from M5 need to be opened/saved in order to fix up document.css. (Actually, old user files probably will have dojo.css in them, which is basically the same as document.css.)

Not a M6 ship-stopper, and easy to fix for M7.

**Comment by billreed63** [comment]
fixed by #2694
