### ISSUE TITLE
tolerate dojox.mvc

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2465]
@peller @aerwin @doronrosenberg @jhpedemonte 

For M7, we'd really like to allow a user to enter dojox.mvc's `at(model, field)` syntax as the value for SmartInput (and maybe even some widget-specific properties), and for the Maqetta page editor to do something reasonable in response to this. 

If we are able to do anything in this area for M7, it will probably be only in particular constrained scenarios.

One idea is that if we can have the page editor have Dojo actually instantiate the "model" (similar to how an ItemFileReadStore widget in the page editor gets instantiated), then maybe the `at(model, field)` syntax will just trigger the dojox.mobile logic within the user iframe when we call the widget constructor within `createWidget()`.

Set as M7-High for now, but we haven't done a feasibility study yet.

**Comment by JonFerraiolo** [comment]
-> @aerwin for time being (might end up going elsewhere ultimately)

**Comment by aerwin** [comment]
The main goal for M7 is to tolerate dojox.mvc when leveraged via the Maqetta source editor. In later milestones, we'll want to explore enhanced smart input capabilities. I'll add some notes in a later post about how that smart input might work.

But, per scrum today, I mentioned that we already tolerate dojox.mvc. And, below I'll discuss the sample I now I have running in Maqetta. (I was actually about to hit submit on a more complicated write-up with more warnings, but I just heard back from one of the dojox.mvc developers this afternoon after I raised a couple of concerns. And, he just updated some samples for me in the [online docs](http://livedocs.dojotoolkit.org/dojox/mvc) that were out of date. The new info simplifies stuff for us a fair amount.)

### dojox.mvc running in Maqetta

All of the mvc related examples use some amount of custom JS, so I had to do a little bit of work to figure out how to do it entirely declaratively (so it would work in our page editor). Below, is a completely declarative example that I put together that previews in Maqetta. It is based on the 2nd [example](http://livedocs.dojotoolkit.org/dojox/mvc#examples) in the dojox.mvc pages.

```
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8"/>
<title>Untitled</title>
<script type="text/javascript" src="lib/dojo/dojo/dojo.js" data-dojo-config="'async':true,'parseOnLoad':true,'packages':[{'name':'shapes','location':'../../shapes'},{'name':'clipart','location':'../../clipart'},{'name':'gridx','location':'../gridx'},{'name':'maqettaSamples','location':'../../../samples'},{'name':'maqetta','location':'../../maqetta'},{'name':'dojo-src','location':'..'},{'name':'widgets','location':'../../widgets'}]"></script>
<style>@import "themes/claro/claro.css";@import "app.css";
</style>
<script type="text/javascript" src="app.js"></script>
<script type="text/javascript">
require([
  "dijit/dijit",
  "dojo/parser",
  "maqetta/space",
  "maqetta/AppStates",
  "dojo/Stateful",
  "dijit/form/TextBox",
  "dijit/form/Button",
  "dojox/mvc/Output"
]);
</script>
</head>
<body class="claro" data-maq-flow-layout="true" data-maq-ws="collapse" id="myapp" data-maq-appstates="{}">
    <script type="dojo/require">at: "dojox/mvc/at"</script>
    <span id="model" jsId="model" data-dojo-type="dojo.Stateful" data-dojo-props="First: 'John', Last: 'Doe', Email: 'jdoe@example.com'"></span>
    <span id="ctrl" data-dojo-type="dojox/mvc/EditModelRefController" data-dojo-props="sourceModel: model"></span>
    <div id="main">
        <div>
            <label for="firstId">First:</label>
            <input id="firstId" data-dojo-type="dijit/form/TextBox"
                data-dojo-props="value: at('widget:ctrl', 'First')"></input>
            <!-- Content in output below will always be in sync with value of textbox above -->
            <span data-dojo-type="dojox/mvc/Output"
                data-dojo-props="value: at('widget:ctrl', 'First')">
                (first name is: ${this.value})
            </span>
        </div>
        <div>
            <label for="lastnameInput">Last:</label>
            <input id="lastnameInput" data-dojo-type="dijit/form/TextBox"
                data-dojo-props="value: at('widget:ctrl', 'Last')"></input>
            <span data-dojo-type="dojox/mvc/Output"
                data-dojo-props="value: at('widget:ctrl', 'Last')">
                (last name is: ${this.value})
            </span>
        </div>
        <div class="row">
            <label for="emailInput">Email:</label>
            <input id="emailInput" data-dojo-type="dijit/form/TextBox"
                data-dojo-props="value: at('widget:ctrl', 'Email')"></input>
            <span data-dojo-type="dojox/mvc/Output"
                data-dojo-props="value: at('widget:ctrl', 'Email')">
                (email is: ${this.value})
            </span>
        </div>
        <br/>
        Model:
        <button id="reset" type="button" data-dojo-type="dijit/form/Button"
                data-dojo-props="onClick: function(){ require('dijit/registry').byId('ctrl').reset(); }">Reset</button>
        <button id="fromModel" type="button" data-dojo-type="dijit/form/Button"
                data-dojo-props="onClick: function(){ require('dijit/registry').byId('ctrl').set('First', 'Updated in Model'); }">Update First from Model</button>
        <button id="fromWidget" type="button" data-dojo-type="dijit/form/Button"
                data-dojo-props="onClick: function(){ require('dijit/registry').byId('firstId').set('value', 'Updated Widget'); }">Update First from Widget</button>
    </div>
</body>
</html>
```

When the HTML above is pasted into Maqetta, you see something like the screenshot below. When you preview the page from Maqetta, updating values in the text fields automatically updates the content of the labels (and, the buttons work as well).

![screenshot](http://i.imgur.com/tD6bz.png)

### Using dojox.mvc Declaratively

As alluded to earlier, the example from the web is not entirely declarative as it does some setup in the callback function invoked after the requires are loaded. However, adding a function like this in Maqetta does not work within the page editor (e.g., the JS doesn't run).

```
var model;
require([
    "dojo/parser",
    "dojo/Stateful",
    "dijit/form/TextBox",
    "dijit/form/Button",
    "dojox/mvc/Output",
    "dojox/mvc/at"
], function(parser, Stateful, TextBox, Button, Output, at){
    // For this test we can use a simple dojo/Stateful as our model
    model = new Stateful({First: "John", Last: "Doe", Email: "jdoe@example.com"});
    parser.parse();
});
```

You'll notice the big thing the JS above does is create an instance of `dojo.Stateful`. I was able to do that declaratively like so:

```
<span id="model" jsId="model" data-dojo-type="dojo.Stateful" data-dojo-props="First: 'John', Last: 'Doe', Email: 'jdoe@example.com'"></span>
```

It took me longer than I would have liked to figure out how to use `Stateful` declaratively because the attributes get set directly on the `Stateful`. So, using JSON within `dojo-data-props` like `{First: 'John', Last: 'Doe', Email: 'jdoe@example.com}` fails.

### Other Things to Note in the Declarative Mark-up

There are a couple of other things to note (aside from the `at` syntax) when we get to the point of implementing some smart input in support of dojox.mvc.

To enable `at`, a script block making use of the [new declarative require support in 1.8](http://livedocs.dojotoolkit.org/releasenotes/1.8#declarative-require) is needed like so:

```
<script type="dojo/require">at: "dojox/mvc/at"</script>
```

There's also one other block of importance (defining an `EditModelRefController` that consumes our `Stateful`):

```
<span id="ctrl" data-dojo-type="dojox/mvc/EditModelRefController" data-dojo-props="sourceModel: model"></span>
```

**Comment by aerwin** [comment]
Now, that I'm using `EditModelRefController` (the new insight from working with the dojox.mvc developer) I was able to get rid of the direct use of `dojo.Stateful` and put the data of interest in a `dojo.store.Memory`:

```
<span id="Memory_1" jsId="Memory_1" data-dojo-type="dojo.store.Memory" data="[{&quot;First&quot;: &quot;John&quot;, Last: &quot;Doe&quot;, &quot;Email&quot;: &quot;jdoe@example.com&quot;}]"></span>
```

This is more in line with what we'll want to do with a smart input solution. E.g., we already have code (like for Tree) that edits `dojo.store.Memory` on the back end.

**Comment by aerwin** [comment]
With the sample provided above that works in Maqetta, and the opening of issues #2772 & #2773 for future dojox.mvc work, I'm going to go ahead and close this issue.
