### ISSUE TITLE
No StackContainer in widget palette

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#2488]
There's no StackContainer in the widget palette (which I think would probably be kind of important if someone were going to mock-up a wizard).

I see it was commented out in the package.json file in the davinci.dojo_1_7 plugin:

```
/* Commenting out - crashes as currently defined because there is no dijit.layout.StackController widget
```

**Comment by JonFerraiolo** [comment]
Assigning to me for now. I'm working in this general area. (Also, I'll fess up to being the person who commented out StackContainer)

**Comment by JonFerraiolo** [comment]
-> @doronrosenberg - can you please take this one? I'm not sure what caused the crash (and the need to comment out StackContainer). I've been using StackContainer recently inside the page editor and I don't see much of a difference between TabContainer and StackContainer, and in fact I've swapped between the two very easily in the page editor itself.

But once we get StackContainer such that it drags/drops from widget palette onto canvas, the next question is what to do about it from a user perspective because a StackContainer needs sidecar JavaScript logic to switch between children. At a minimum, we need some sort of tutorial or other post (e.g., a developerWorks blog) to tell people how to make use of a StackContainer, and it would be best if the Maqetta UI would give users a hint that they need sidecar JavaScript logic.

**Comment by aerwin** [comment]
> At a minimum, we need some sort of tutorial or other post (e.g., a developerWorks blog) to tell people how to make use of a StackContainer, and it would be best if the Maqetta UI would give users a hint that they need sidecar JavaScript logic.

@doronrosenberg I could help with a blog post once StackContainer is enabled. In a lot of ways it would follow naturally from the recent one I wrote on [Adding Your Own JavaScript to Maqetta Prototypes](https://www.ibm.com/developerworks/mydeveloperworks/blogs/MaqettaAuthoring/entry/adding_custom_javascript3?lang=en) .

**Comment by JonFerraiolo** [comment]
A blog post would be wonderful.

**Comment by doronrosenberg** [comment]
So the idea would be to have a smart input that would point to said blog post?

**Comment by JonFerraiolo** [comment]
I'd really rather avoid the shipping product include hard-coded hyperlinks to articles on IBM developerWorks.

How about SmartInput that says something like this widget requires supplemental JavaScript, with a hyperlink that instead of going to developerWorks, instead goes to Google.com, with a search key for Maqetta+StackContainer+How+To.

**Comment by doronrosenberg** [comment]
@JonFerraiolo Actually if you add a stackcontroller to a stackcontainer it will generate buttons to change panes, so there really isn't a need for javascript.

**Comment by doronrosenberg** [comment]
Closing this, don't think we need to document javascript as its an optional thing.
