### ISSUE TITLE
Drag/drop rearrange 2 Trees, cannot reopen file

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2509]
- New HTML File
- Add 2 Tree widgets, make the content different so you can tell which tree is which
- Drag/drop the 2nd Tree in front of first Tree
- Save, close, reopen

=> Maqetta says unable to parse the file, go into source to fix. The reason is that the datastore for one of the trees is later in the file.

Really bad because you can't go into source to fix. See this other issue: #2508

**Comment by JonFerraiolo** [comment]
Maybe we need a new helper function or a new pubished event so that particular widgets can be notified (and then do cleanup) when certain things occur. In this case, I suspect that ReparentCommand is getting called, and maybe we have to make sure that the ItemFileReadStore and ForestStoreModel widgets gets moved in front of the Tree.

**Comment by jhpedemonte** [comment]
(This comment really belongs here:)

Remind me again: why don't we just put the stores at the top of the file, above everything else? How many bugs like these will we run into because we insist on putting the stores elsewhere?

**Comment by billreed63** [comment]
The reason we keep hitting this bug is that the helper's for each widget that use a store need to take that into account when processing that widget for create/cut/paste/delete. We need to abstract out processing create/cut/paste to a class that would be a base class for all the widgets that use the store and then we would stop seeing this problem. Putting the store at the top of the page when the widget is created would fix this problem for moving widget around the page but does not address delete or cut/paste to new page.
