### ISSUE TITLE
Dojo web builder: special handling for inaccessible server

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#2520]
if the maqetta server is behind a firewall or running on localhost or some other non-addressable URL, dojo web builder will fail, since the content is referenced by URL

Should probably skip the builder entirely for localhost. Is there a quick check we can do to see if a round trip is possible?  Perhaps there's a cheap REST call to DWB to verify?

Right now, if a request fails for any reason, the unbuilt zip will be sent to the client

**Comment by ghost** [comment]
Dojo web builder currently won't build maqetta pages even work on local build. This is because DWB is already configured to dojo version 1.7.2, while maqetta is still on 1.7.1. This is my free guess, because _base.\* packages are not in dojo web builder list and no DWB 1.7.1 download available (nor in the web site ...).
This is quite fucked up, because this can be such a great product ... but I guess it needs its time...

**Comment by peller** [comment]
@rubimazaki, Dojo 1.7.1 and 1.7.2 are fully compatible and interchangeable.  I've been able to use DWB manually with output from Maqetta Preview 6 just fine, but if it does fail, it often fails silently, so you may be encountering a DWB bug.

**Comment by peller** [comment]
-> M8

**Comment by peller** [comment]
As of a015f94b40bdd7bea2b26c1e71cad1a2454942ff, download will fail if DWB is unable to retrieve content rather than continue with an unbuilt zip.

@rubimazaki see #3460 for versioning improvements
