### ISSUE TITLE
Executed commands should publish granular data

### ISSUE THREAD

**Issue by doronrosenberg** [maqetta/maqetta#2538]
@jhpedemonte @JonFerraiolo

Currently Outline rebuilds the entire Tree each time a command is executed.

If we want to fix this, we need commands to publish some data about what they did.  Currently we have `context.widgetAddedOrDeleted` that gets called for any modifications, but no data is passed into it.

I think that the easiest solution would be to add the following to context.js:

```
widgetAdd(widget)
widgetRemove(widget)
widgetReparent(widget)
widgetModify(widget)
```

We could then attach to those methods and thus have granular data available to make smart changes rather than total rebuilds.  Or each of those could do a dojo.publish if that sounds better.

Thoughts?

**Comment by JonFerraiolo** [comment]
I like the direction proposed above. I think it's better to do direct function calls whenever possible and avoid pubsub when there is the possibility that a particular widget needs to listen for a particular event. Suppose 5 different widgets need to listen to widgetAdd. Then all 5 widgets would get called each time any widget was added, and those 5 widgets's subscribe function would need to check to make sure that the widget that was added was the same time as the subscribing widget. Much simpler, direct, and efficient if the commands call into Context (as proposed above). For widget-specific logic, the routine in Context can see if there is a corresponding helper function for the current widget type, and then call that helper function if it exists. Probably about 1000 times more efficient than the pubsub approach.

But we want to minimize bloat due to N (or NXM) different types of events and/or helpers. What I'm thinking is having a centralized `widgetChanged()` function where one of the parameters indicates the type of change (add vs remove vs ...). This would provide a convenient answer for the common scenario where a single handler function processes multiple different events. For example, in StatesView.js, any of the above widget events (add, remove, reparent, modify) might trigger an update-everything action. So, instead of N different event connections, there could be one event connection callback function that checks the 'type' to see if it is one of the types of interest.

**Comment by jhpedemonte** [comment]
Well, actually, I'd push to have more pub/sub, to keep the individual components loosely coupled.  I like Doron's proposal.

**Comment by JonFerraiolo** [comment]
But you understand my worry about using pubsub in this case? If you ever had a Button in any document within a session, and the Button helper is listening for "widget added", then with every widget added call the Button helper will get called, even if there are no Buttons in any currently open documents.

I guess what I'm saying is that we shouldn't use pubsub when the event is about a single widget instance, where a helper is more appropriate, but OK to use it for system-wide events. For example, use a helper to tell the Button helper class that a Button has been added, but if the Button helper class needs to be notified when other widget types are added, then yes pubsub makes sense then.

**Comment by jhpedemonte** [comment]
Yes, I agree with regards to Helpers.  But in your first comment you mentioned direct calls into Context, and I didn't agree with that.

**Comment by JonFerraiolo** [comment]
OK, I think we are in agreement on the most important part of the question, but now let's talk about the best strategy for a command to trigger things within the current open editor. Two obvious options are: (1) direct function calls to either editor.\* or context.\* to well-known function names, (2) publish on a topic, and then *Editor.js or Context.js listens to that topic. The former incurs less CPU overhead and is easier to debug, and the latter is better from a code decoupling perspective. We could also go with a hybrid approach where there is first a direct function call, and then the logic in that function call is free to publish an event.

You agree with the analysis?

I think these two approaches are both reasonable approaches. Personally, I prefer (1) where dojo.publish() events generally come out of Context.js (and things hanging off of it) and that we don't publish events from all over the place, but I'm OK with (2).
