### ISSUE TITLE
Size of certain dialogs too small

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#2547]
@doronrosenberg 

This might already be part of your list of clean-up items, but in Chrome/Mac I'm running into a few dialogs that are sized too small on launch such as:

![screenshot](http://i.imgur.com/YJobc.png)
![screenshot](http://i.imgur.com/gZluG.png)

**Comment by jhpedemonte** [comment]
I believe the **Upload Files** dialog was always that small.  Odd that the buttons are stacked, rather than side-by-side.

As for the layout dialog, that didn't used to have buttons.  It just acted on whatever the user chose from the drop down.

Lowering priority to Med.

@JonFerraiolo

**Comment by aerwin** [comment]
Guess I had opened it high because it's regression and looks really bad (e.g., I don't think we'd ship Release 1 with that going on). But, I understand it's not really a blocking functional issue.

**Comment by jhpedemonte** [comment]
I think we also want to replace the layout dialog with a drop down on the toolbar.  Hmm, #1149 is set for M8, though.

**Comment by JonFerraiolo** [comment]
> Hmm, #1149 is set for M8, though.

This is likely to get addressed in M7 due to general UI makeover issues. Also, I've already experimented and it's very easy to put arbitrary HTML (and arbitrary widgets) into a toolbar. All you need to do is wrap the arbitrary HTML/widgets inside of a Dijit because ToolBars accept any Dijit as content.
