### ISSUE TITLE
No dirty bit on new HTML file, but file disappears when close editor

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#2548]
1. Create new HTML file
2. Note no dirty bit
3. Close file by clicking X in page editor
4. No warning message is displayed that I'll lose the file, but the file disappears from the files palette

**Comment by jhpedemonte** [comment]
So you closed a new file that you hadn't added any content to?  Then the correct behavior is to not show a warning message.

@JonFerraiolo

**Comment by aerwin** [comment]
that's fine, but then I don't think the file should disappear from the file palette (see Step 4)

**Comment by JonFerraiolo** [comment]
If you never save, then why would we keep the file around? The behavior described in this issue is the way things have worked from the very first release of the product - you know, we consider it a feature not a bug. If someone repeated the above steps 4 times, he would have 4 empty files in his workspace: file1.html, file2.html, file3.html, file4.html. 

One thing we might do is include some different visual styling for new files that have never been saved and will vanish if the editor is closed.

**Comment by aerwin** [comment]
> The behavior described in this issue is the way things have worked from the very first release of the product - 

Not true... in M6 (and I thought before), a new file had a dirty bit and you got a warning message when you tried to close it. If we're not going to show a warning message (e.g., we don't consider it dirty), I'm not sure we should delete the file. I don't think that's consistent with standard UI behavior/guidelines.

**Comment by aerwin** [comment]
I was about to add this was especially bad if user changed the file name (e.g, called it welcomePage.html instead of default file1.html). But, that looks to be properly handled with a dirty bit. So, guess we're just talking about a the edge case. And, I'm not too worried about that.

**Comment by aerwin** [comment]
I'll just go ahead and close based on my last comment.
