### ISSUE TITLE
dleadt - missing trailing slash goes to wrong url

### ISSUE THREAD

**Issue by childsb** [maqetta/maqetta#256]
With the release at http://dleadt.torolab.ibm.com:9080/davinci/, if the user
enters the URL http://dleadt.torolab.ibm.com:9080/davinci (without trailing
slash), the server redirects him to http://dleadt.torolab.ibm.com:9080/welcome,
which is a non-existent page. So, we need an IF statement or something, perhaps
server logic to change /davinci to /davinci/.

------- Comment #1 From Phil Berkland 2011-04-04 18:19 [reply] -------
hopefully was fixed a while ago by redirecting to "./welcome" instead of
"welcome".

------- Comment #2 From Jon Ferraiolo 2011-05-03 12:48 [reply] -------
Reopening. I tried http://dleadt.torolab.ibm.com:9080/maqetta and it exhibits
the same behavior as described in this bug report.

bug: 7345

**Comment by JonFerraiolo** [comment]
If this bug still exists, it would be in the w3 project. Set to M4 just to make sure that if this bug still exists it will get addressed for M4.

The generalization of this bug is that we should carefully compare w3 project against latest maqetta.org server code to make sure all fixes are in the w3 project.
