### ISSUE TITLE
Video tag not working in preview on chrome

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#2570]
DnD HTML video and click preview

nothing in the preview browser on Chrome 21 win

**Comment by billreed63** [comment]
If I only have the video tag nothing is displayed if I add the embed tag after video it works in preview

**Comment by aerwin** [comment]
@billreed63 

Where did you get Chrome 21? On Windows, I just tried Chrome 19.0.1084.56 (which the About Chrome dialog tells me is the latest), and the video preview worked just fine.

**Comment by billreed63** [comment]
Yes windows. Windows always seems to be ahead of OSX

**Comment by aerwin** [comment]
Well, like I said: "On Windows, I just tried Chrome 19.0.1084.56 (which the About Chrome dialog tells me is the latest), and the video preview worked just fine."

**Comment by billreed63** [comment]
Well, like I said: it was Chrome 21.0.1171.0 dev-m

**Comment by aerwin** [comment]
So, maybe you're on a dev stream rather than release stream or something?

**Comment by billreed63** [comment]
I think I am on the dev channel https://www.google.com/chrome/eula.html?extra=devchannel

**Comment by aerwin** [comment]
Ok, so that makes sense how you have a Version 21 then... since you're on dev channel, I'm inclined not to do any debugging on this issue for now. I'm guessing Google must have broken the video tag in their dev stream and surely would fix it by the time Version 21 comes out in the stable product stream. Once Version 21 comes out on the product channel we can verify whether there is a problem or not.

**Comment by aerwin** [comment]
@billreed63 

We're up to 21.0.1180.77 on Windows on the main release channel, so I thought I'd try this again... as far as I can tell, video is working fine. So, closing. Please reopen if you disagree.
