### ISSUE TITLE
Table cell smart input doesn't gracefully handle widgets in cell

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#2572]
1. Drop HTML table onto page
2. Drop widget into cell (e.g., Button)
3. Double-click on cell with Button
4. Smart input for table cell comes up showing markup of the widgets in the cell:

![screenshot](http://i.imgur.com/mjPgc.png)

**Comment by JonFerraiolo** [comment]
@billreed63 

This behavior is actually by design. Although extremely geeky, it does provide users with a way to do hand-editing of the content. For example, suppose you have a DIV with innerHTML of `<b>Careful:</b> this is dangerous`. You see, at the moment we don't have ability to select text nodes, only widgets (which always correspond to an element node). Other than using source pane, we don't have a way to deal with "mixed content" (i.e., text nodes combined with element nodes).

Any better ideas about how to deal with this from a UI perspective?

**Comment by aerwin** [comment]
@JonFerraiolo , I don't have any particularly brilliant ideas... my initial thought had been to try and disable smart input if the cell contains Dojo widgets (e.g. isHtmlWidget = false for any of the children in the cell). But, maybe that's confusing too -- e.g., user would wonder why smart input isn't coming up and would have to delete all of the Dojo widgets in order to be able to revert to some simple text for the cell.

So, guess we'll just close as working as designed for now.
