### ISSUE TITLE
Update release notes to discuss non-breaking white space and HTML tables

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2577]
(M7/Med - there will be cases for this out in the field, but I expect it won't be that common)

If a user added a TABLE widget to Preview 6 or earlier, and there were empty cells in the TABLE, the old rules in content.css would ensure that the cells were at least 1em big (width and height). But with recent changes, the rules in content.css have been changed, so it is possible that columns or rows for migrated HTML files might have zero size.

We need to fix up existing HTML files to add zero-width non-breaking space (&#8288;) into existing user table cells that have no content.

**Comment by aerwin** [comment]
I think we should probably also add COLGROUP elements to any tables without them.

**Comment by aerwin** [comment]
-> Making Prio High (from med) and leaving in M7 (to be dealt with once we dive into migration work as a team)

**Comment by aerwin** [comment]
-> Update title from "Need to insert zero-width non-breaking space (&#8288;) into existing user table cells" to "Update release notes to discuss non-breaking white space and HTML tables"
-> Change tag to Docs

Per discussion at scrum, we decided just to update the release notes rather than try and do migration here.

**Comment by aerwin** [comment]
Closing with 6e51dac66bd0c569ae7f717b48f3881d93d057cb .
