### ISSUE TITLE
Need to deal with read-only themes in Cascade.js

### ISSUE THREAD

**Issue by childsb** [maqetta/maqetta#258]
If the current theme is read-only, then we can't change the theme CSS files
because the theme CSS files are read-only. The logic in Cascade.js needs to
deal with this. I'll take care of that, but first, Brad, answer this, and then
assign back to me:

Is there an API or property on a JavaScript object that indicates whether a
particular style sheet (or CSS file) is read-only?

bug: 7569

**Comment by JonFerraiolo** [comment]
@jhpedemonte 

Elevated to M2. After evaluating this bug, it's clear that users will run into this quite often and be totally confused. 

The way things work now, if a user selects a Dojo widget and attempts to change any properties whose value goes onto a subnode (which is really common with Dojo), then by default a theme CSS rule is chosen, and our default theme (claro) is read-only. Therefore, in a large percentage of cases, users will run into this bug.

Ideally, we shouldn't allow properties to be set on style rules within read-only themes by somehow disabling this option in the UI. However, such disabling is likely to be quite involved from a design and implementation perspective. For the more immediate term, OK if we post a new dialog telling the user they their attempted property change cannot be done because the operation attempts to change a CSS file within a read-only theme. (Once this dialog is there initially, I can tweak the wording.)

**Comment by childsb** [comment]
Added alert prompt in Cascade.js. Commit : bb9778b28ca8bea22eed

Side note - put some extra code in to make it easier to 'enhance' this.

**Comment by JonFerraiolo** [comment]
Hey Brad, Thanks for putting in error dialog, but when I was working on the more informative message, we need to provide a hyperlink in the error message that the user can click on, and alert() doesn't allow for rich text. I submitted a string of HTML markup to put in the dialog with commit 405af924950ad56e24d85c936b465963e3368be2 but I didn't know how to present a dialog to use that just had OK button and did not have the "do not show again" check box. Could you please help with that?

**Comment by childsb** [comment]
yesir, will do.

**Comment by childsb** [comment]
moved the error msg to a modal dialog that supports hyper links. commit 892f2969d9c1c21bd772
