### ISSUE TITLE
Rewrite _ToggleTreeNode

### ISSUE THREAD

**Issue by doronrosenberg** [maqetta/maqetta#2600]
davinci.ui.widgets._ToggleTreeNode is overriding way too many methods, it needs to be rewritten to be less invasive.

**Comment by jhpedemonte** [comment]
Do we still need it?  Can we use a "stock" Dijit instead?

**Comment by peller** [comment]
At least when it was created, subclassing was required to support the 'eyeball' functionality -- to hold the state, handle the event and state changes, and provide a different template than the normal row.  The companion Tree widget must also be subclassed, if only to create an instance of this new node type.

This widget was used throughout the product whenever a tree was needed, and was modified to support other functionality, rather than factoring out those functions into a separate class.  I tried to undo that and remove the all the dependencies besides the Outline View, but some of the dead or duplicate code still remains, and that makes it particularly fragile when we upgrade Dojo.  I'm not sure why we re-define `shouldShowElement()` or `setChildItems()`

There was a [long-standing Dijit bug](http://bugs.dojotoolkit.org/ticket/7513) which was closed recently when a third party widget was made available, but I'm not sure even that widget has exactly the right look.
