### ISSUE TITLE
With zazl previews, our hook function into dojo parser never called

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2784]
Our hook function into dojo.parser.parse in AppStates.js isn't getting called for preview-in-browser when zazl is turned on. To reproduce:
- Open Sample1.html
- Preview
- Open up debugger. In the script panel, look for _javascript module, then search for _preserveStates to find the hook function that intercepts/overrides dojo.parser.parse, and put a breakpoint into that hook function
- Browser refresh. 

Result=> Breakpoint not reached. 

Note: no problem with preview if you turn the zazl checkbox off in the preferences dialog

**Comment by rbackhouse** [comment]
It appears to work in chrome but not safari or firefox. I'll take a look

**Comment by rbackhouse** [comment]
I take that back. It works on all 3 browsers but only if I first load the file via the main maqetta page. If I just copy the preview URL to a freshly opened browser this path is not taken.

**Comment by rbackhouse** [comment]
It seems to be a timing issue. The hook is getting set sometimes after parseOnLoad has already been processed.

**Comment by peller** [comment]
I rewrote the hook routine in AppStates.js to be more AMD-compliant 347a7fd3658b3b4e6817d144bda6554e25fca320 hoping that would fix the problem, but it didn't.  @rbackhouse, it seems like Zazl's implementation of dojo/ready is firing before all the pending require statements are satisfied.

I put two breakpoints in AppStates.js: one at the aspect.around call in hook(), another at this line around 1221 which should call it:

`require(["dojo/parser"], hook);`

Once you step past that require["dojo/parser"] call, the stack unwinds and the dojo/ready called from dojo/parser fires and the document gets parsed, even though the require callback for hook is still outstanding.

(note that due to the way the code is referenced in the workbench and in user content, there are two copies of AppStates.js, one in maqetta.core.client/WebContent/davinci/maqetta and another in maqetta.core.server/WebContent/project/maqetta)

**Comment by rbackhouse** [comment]
@peller Zazl does not have an implementation of dojo/ready. dojo/ready is using the proprietary require API's "on" and "idle". The "on" API is passed a callback. 

Zazl considers the page "ready" once all the modules and their dependencies specified in the "require" have completed loading and that the "DOMContentLoaded" event has fired. The "on" callback is called when these requirements have been met.

Is there a reason why parseOnLoad has to be used ? Why can't the AppStates module manually call parse once it has added its hook code ?

**Comment by peller** [comment]
I think the idea was to have the AppStates code be transparent such that the page would work with or without it and generally not impact the logic the developer sees on the page or change the way Dojo is expected to work.

Could Zazl postpone when it considers the page "ready" until all pending require calls have fired?

**Comment by rbackhouse** [comment]
I don't think that would be possible. What defines a pending require? One can happen at any point within an application triggered by application code that happens way past the ready point. It seems we are trying to solve an application issues at the loader level. It could become a very slippery slope.

**Comment by peller** [comment]
Well, pretty much ready would just have to wait for any nested requires in requires the loader is already waiting for.  This is what dojo/ready does.  If code is loaded past the ready point, that is after all the initial requires and their nested requires have completed, I think that's clearly beyond the scope of dojo/ready.

**Comment by rbackhouse** [comment]
My big concern is that is will be very hard to support. I still don't I have a grasp of the root issue. I found some details that Rawld gave for how dojo/ready is working :

" The dojo/ready module executes callbacks under two conditions:

```
DOM content loaded is achieved.
All requested modules have arrived and been evaluated. "
```

This is what the Zazl loader is currently doing.

Also I still have trouble understanding what the problem is with calling the parser manually. This is seems like the simplest and least intrusive fix. There is alway going to be markup that needs parsing correct ? Instead of trying to hook into code that has potentially already loaded simply adding a dependency on the parser, adding hook code and then running the parse seems so much easier and less fragile.

**Comment by peller** [comment]
Not happy about the fix above.  Should still be able to use mobile parser at runtime.  Note that the call to hook wasn't right, so the mobile+states path probably hasn't been functional for a long time.
