### ISSUE TITLE
UI Refresh: Update palettes that show, come to front on editor, etc. on editor switches

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#2872]
@JonFerraiolo 

A long time ago for #1814 ("UI tweaks to palettes - bringing palettes to top for particular editors"),  we made it so different  palettes come to the front depending on what editor is brought to the front. We need to re-evaluate and clean up code in that area with the new UI refresh. 

For example, I just opened a review from the Reviews palette, but when the review was opened, the Review palette was hidden in favor of the Scenes palette.

I also notice the Scenes palette is always favored over the Files palette. But, personally, I'd expect folks to spend more time in the File palette when editing HTML files than in the Scenes palette. (But, maybe that ties more into remembering palette states at users use the UI -- which I thought we had a feature request open for at one time but can't find now.)

**Comment by aerwin** [comment]
@JonFerraiolo 

I was figuring I'd just be able to close this one based on the design going back to palettes on both left and right, but I'm still seeing some behavior we probably need to address.... Prior to any UI refresh this was roughly the design:

> Page editor: bring Widgets, Properties, States(Scenes) to the top
> Theme editor: bring Properties, States(Scenes) to the top
> Review editor: bring Reviews, Comments, States(Scenes) to the top

Now that Properties is by itself and Comments/Scenes are in the same tabbed pane, it probably needs to be something like:
- Page editor: bring Widgets, States(Scenes) to the top
- Theme editor: bring Properties, States(Scenes) to the top
- Review editor: bring Reviews, Comments

But, now "bring to top" gets interesting... For example:
- I notice when I open a review the left side palettes collapse (even if already open). So, even if we made the Reviews Palette be on top it would not be immediately visible. 
- the Comments palette is the most important thing for reviews, but the right hand palette stay collapsed when I bring up a review. Would we want to open up the right hand side?
- etc.

**Comment by JonFerraiolo** [comment]
@aerwin - yes, I was sloppy with my last-minute edits to the plugin files regarding which things come to top and which sides get expanded/collapsed. Could you please clean up after me? :-) Note that I added a new field in the *.plugin.js files for controlling which side palettes are expanded/collapsed for each particular type of editor.

Note that in general if a side is collapsed, then bringing a particular palette to top (in a collapsed state) won't be initially noticeable to the user, but it will matter if the user expands that side by clicking on a palette in a different section. For example, suppose Files is listed as "to top" but the left-side is collapsed initially. If the user clicks on the Outline tab to expand the left-side, then Files would show on the bottom.

There is one new wrinkle that I think we need for M7 that I hadn't gotten around to yet. I'd like to have certain palettes appear/disappear with certain editors. This is necessary because we need "Comments" to appear in top-right, but we really don't want Comments to appear when the page editor or theme editor is open. Do you think you could enhance our plugin file format to provide this sort of a feature?

I'd suggest:
- Page editor:
  - Visible palettes
    - Top/left: widgets/palette, outline
    - Bottom/left: files, reviews
    - Top/right: properties
    - Bottom/right: Scenes/states
  - To top: widgets/palette, files, states/scenes
  - Expand/collapse: Left-side expanded, right-side collapsed.
- Theme editor: 
  - Visible palettes
    - Top/left: none (if the product isn't viable without any palettes, then ok to leave widgets and outline visible)
    - Bottom/left: files, reviews
    - Top/right: properties
    - Bottom/right: Scenes/states
  - To top: files, states/scenes. (No need to mess with props - ok to let the previously open props section to be on selected) 
  - Expand/collapse: Left-side collapsed, right-side expanded.
- Review editor: 
  - Visible palettes
    - Top/left: none (if the product isn't viable without any palettes, then ok to leave widgets and outline visible)
    - Bottom/left: files, reviews
    - Top/right: comments
    - Bottom/right: Scenes/states
  - To top: reviews, comments, states/scenes. 
  - Left-side collapsed, right-side expanded. (I recommend we collapse the left-side palettes for review editors thinking that most of the time people will be reviewing a single file, and it's more important to offer a larger-size canvas than to open the left-side palettes)

Note that hiding the properties palettes might be a bit tricky because there one entry in the ve.plugin.js file for the properties palettes expands into 10 separate tabs. Somehow or other we will need to invent some sort of marker on the palettes which can be used for the hide/show logic.

**Comment by aerwin** [comment]
--> Updated title

Closing with above commit.
