### ISSUE TITLE
User, Preferences, and Help Menus Get Cut-off

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#2891]
Using Chrome on Mac...

The User, Preferences, and Help Menus each get cut-off the first time they are opened. They correct themselves the next time they are opened. 

![Screenshot](http://i.imgur.com/bKNT0.png)

![Screenshot](http://i.imgur.com/zoXjy.png)

![Screenshot](http://i.imgur.com/5ioHB.png)

Probably a Sev 3 problem, but seems like it would be nice to fix for M7 if possible (hence (High Prio).

**Comment by jhpedemonte** [comment]
-> @JonFerraiolo

**Comment by JonFerraiolo** [comment]
I think this is a dupe, but I'll research that later. I know what the problem is and how to fix it, and I'm pretty sure I put all of that info in the other bug report. Whatever, I'll take care of this.

**Comment by JonFerraiolo** [comment]
@aerwin @billreed63 @doronrosenberg @peller - any of you interested in grabbing this one? 

Here is the deal. The first time any of the 3 dropdowns gets activated, our logic (mostly Workbench.js) calls Dojo to open up the menu (which determines its (x,y) location), and then we dynamically populate the menu using the logic in function `_openMenu()` . The problem is that with the first call, the menu has no content, so it's width is zero, so Dojo puts the top/left of the menu at the current mouse location.

With subsequent calls, the menu has its contents from the previous call, so dojo computes the (x,y) location of the menu such that the menu will be fully visible on the screen.

One possible solution would be to pull out the logic from `_openMenu()` that builds the menu's content into a separate function (e.g., `_buildMenu()`), and then have `_createMenu()` (which is called once for each popup/dropdown menu defined in any of the *plugin.js files) call `_buildMenu()` for each menu. That way, each menu will have been built once before the first time that `_openMenu()` is called.

**Comment by peller** [comment]
-> @peller
