### ISSUE TITLE
Mobile device overlay not displayed on browser refresh

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#2897]
Create a new mobile iphone
add header
save page
Refresh browser

Note not the device overlay is missing

**Comment by jhpedemonte** [comment]
This is working for me on maqetta-test.

**Comment by billreed63** [comment]
the only time I am seeing it is when I have 4 files open in the editor and the debugger window open [update: bill said the debugger window didn't have to be open]

I have file1.html (iphone) mycustome(custome theme), myclaro (claro theme),  file2.html (android with mycustom theme)

Chrome/windows

**Comment by peller** [comment]
anyone able to reproduce this one reliably?  I have not seen it yet.  @billreed63, have you seen it since you originally reported it?

**Comment by billreed63** [comment]
I have not seen this with the latest code

**Comment by jhpedemonte** [comment]
Reopening -- I may have seen this issue:

Running through **_Tests > Widget Palette: Mobile Data Store Based > EdgeToEdgeDataList: Comma separated data**_.

Performed test, saved, closed file and reopened.  VE shows a simple list; no mobile device silhouette, no styling for contents.  As I was switching windows and doing other things, finally styling and silhouette kicked in (roughly 20 secs later).

Like Bill, I also had 4 or 5 files open.  Notice though that I didn't need to refresh page in order to see this file; just closed and reopened the file.

**Comment by peller** [comment]
Could it just be that some element of the device silhouette was slow to load?  (Admittedly, that's pretty slow, and it's all SVG, right?)

**Comment by jhpedemonte** [comment]
Could be.  But again, this was 20+ seconds later.

**Comment by billreed63** [comment]
I am working on #2961, as part of that I have seen this issue and have shuffled some code around that seems to have fixed this issue. @peller  I would not spend any time chasing this issue until I have finished #2961 to see if my change have fixed this issue...

**Comment by peller** [comment]
Still not seeing the issue, but there is network slowness that in some cases shows delays on the order of 10 seconds per HTTP request #2953
