### ISSUE TITLE
Gridx - datasource-url without using maqetta

### ISSUE THREAD

**Issue by Assa20** [maqetta/maqetta#2919]
Hi there,

i have to admit that i am just starting working with dojo and gridx. Things wirk quite fine, but i am desperately trying to add a data-source-url which provides json data to gridx. I cannot find any information about how to do this.

Do i need to work with xhr.get()? How do i define the store-Object with this external data source for gridx? Anybody any hints for me?

Thanks!

**Comment by aerwin** [comment]
--> aerwin

**Comment by aerwin** [comment]
Hi, thanks for your interest. In your case, it sounds like you don't want to use Maqetta.  However, especially being new to Dojo, I think you'd find a lot of value in Maqetta. In particular, we have a GridX Configuration Wizard, that makes it very easy to connect GridX to JSON data. I have a [blog post](https://www.ibm.com/developerworks/mydeveloperworks/blogs/MaqettaAuthoring/entry/maqetta_gridx_configuration_wizard12?lang=en) describing how to do it without writing any code.

Otherwise, I'd refer you to the [GridX information pages](https://github.com/evanhw/gridx for general GridX support) on GitHub for general GridX concerns. @evanhw or someone else on the GridX team ought to be able to help you out.

Also, generally speaking, GitHub issues are used to track bugs and problems. So, in the future, I'd recommend if you have general questions on Maqetta and how to use various functions and features that they should be posted to our [user forum](https://groups.google.com/forum/?fromgroups#!forum/maqetta-users). And, I thought other folks might be interested in your question, so I created a [forum entry on this topic](https://groups.google.com/forum/?fromgroups#!topic/maqetta-users/aUtFbaCxss0%5B1-25%5D) (without using your name).

**Comment by evanhw** [comment]
Thanks Tony!

Assa20,

[Create-the-Simplest-Gridx](https://github.com/evanhw/gridx/wiki/Create-the-Simplest-Gridx) maybe helpful,  we are working on more docs & tutorial being added to [gridx doc wiki](https://github.com/evanhw/gridx/wiki/_pages)

Not sure which kind of stores you are using, Gridx can work well with both the dojo.data and dojo.store, e.g. the url supported [IFS](http://livedocs.dojotoolkit.org/dojo/data/ItemFileReadStore)

And please also note the possible helpful ref links on [gridx git home](https://github.com/evanhw/gridx)

[gridx issues](https://github.com/evanhw/gridx/issues?direction=asc&sort=created&state=open) is a good place to report issues or feature requests for gridx.

Thanks!
