### ISSUE TITLE
Windows download: no single-user launch scripts

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3008]
@jhpedemonte 

(Prio-High just to research. Fixes might be lower priority)

I pulled down a recent build from lab9 and I only see the _server_ launch scripts and no _local_ (single-user) launch scripts. However, the nightly builds from http://maqetta.org/nightly have both the _server_ and _local_ launch scripts.

Is there a reason why the lab9 builds don't have _local_ launch scripts?

**Comment by jhpedemonte** [comment]
The Orion builds only come with "server" launch scripts -- no single user any more.

The nightly builds are still non-orion -- I haven't changed how they build yet due to the build issues we've been having lately.  Also, we currently have 6 builds output as part of the maq+orion builds instead of just the one "base" build we had before.
