### ISSUE TITLE
ThemeEditor - Disabled state changes on Button aren't saved

### ISSUE THREAD

**Issue by doronrosenberg** [maqetta/maqetta#3015]
Might be related/dupe of #3013
- Create a Claro clone.
- Click on Button
- Change font color to red
- See the change applies
- Switch to disabled
- Click on Button again
- Note that it shows green but the color value is the default
- Changing the color to red or anything else doesn't do anything and is lost one you click away.

**Comment by billreed63** [comment]
I updated the metadata, the selector seemed to have changed, this allows for the updating of the widget in the disabled state.

The issue noted where the button is displayed as green but the color in the background color is an interesting issue of the way the cascade works

once we create a delta rule for the button to green background that rule overrides the disabled rule because the disabled rule is still in the base css file and the override for the normal state is in the delta file. once the user creates the delta for the disabled all is well.  I am adding this bit of quirkiness to issue #226
