### ISSUE TITLE
Can't preview without saving changes

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#3104]
Has this always been the case? I didn't think so...
1. New HTML file
2. Drag widget onto canvas
3. Preview page
4. Close preview and note dirty bit gone from my file because it has been saved

This seems bad if I wanted to preview a set of changes before committing them in a save. I also don't appear to be able to undo at this point. So, there's a chance to really mess yourself up.

**Comment by JonFerraiolo** [comment]
-> @billreed63 

@jhpedemonte @peller @childsb 

> Has this always been the case?

Believe it or not, yes. Same thing with M6, for example. 

As I remember, there was a time many releases ago where we found the need to save HTML files before preview. I suspect we did this for reasons have to do with making sure that CSS file changes were flushed to disk (because in previous releases, CSS file changes were only changed in memory until a save operation occurred). @billreed63 - do we still need to force a save to ensure that preview uses the latest and greatest CSS files? (Don't forget about `app.css` - also, user might have changes `app.js`)

**Comment by JonFerraiolo** [comment]
I believe the save operation is the result of VisualEditor.js:469:

```
        // FIXME. Phil, is there a URL to the working copy of the current file that we can use
        // Right now I am doing an auto-save which is not right.
        // Either we should prompt user "You must save before you can preview in browser. OK to save?"
        // or we should preview the working copy instead of the permanent file.
        editor.save();
```

**Comment by jhpedemonte** [comment]
We need to save so that the updated information get saved on the server, which is from where we load the Preview file.  Only other option is to saving the _workingcopy_, but that could lead to issues.

Seems that the main thing to fix here is the **undo/redo stack**, so that it gets preserved across saves/preview.

-> M8 since this has been the case for many releases.  Also, you should change the summary & title if we are going to repurpose this bug to handle the undo/redo issue.

**Comment by aerwin** [comment]
--> Remove mention of "undo" in title
--> Opened #3124 for undo stack

**Comment by JonFerraiolo** [comment]
> Only other option is to saving the workingcopy, 

Note that workingcopy on the server is instantly updated whenever a change is made to the document. Therefore, we wouldn't need to save the workingcopy because it is already up to date. The ideal scenario would be if the server could deliver the working copy files in preview instead of the base files. I don't know if that is feasible.

**Comment by JonFerraiolo** [comment]
-> M7 just to see if it's as simple as removing one line of code.

@childsb @billreed63 - can you think of any issues with workingcopy files that force us to save whenever the user clicks on the preview button? I just tried commenting out the single line of code in VisualEditor.js that forces a save when a preview action occurs, and everything seems to work just fine - the file stays dirty, and preview shows the workingcopy file instead of the base file.
