### ISSUE TITLE
Exception when select ancestor... 

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#3145]
On FF/Win7 http://maqetta-app-test.austin.ibm.com/maqetta/
with the following html

```
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8"/>
<title>Untitled</title>
<script type="text/javascript" src="lib/dojo/dojo/dojo.js" data-dojo-config="'parseOnLoad':true,'packages':[{'name':'gridx','location':'../gridx'},{'name':'clipart','location':'../../clipart'},{'name':'maqettaSamples','location':'../../../samples'},{'name':'maqetta','location':'../../maqetta'},{'name':'shapes','location':'../../shapes'},{'name':'zazl','location':'../../zazl'},{'name':'widgets','location':'../../custom'}]"></script>
<script type="text/javascript">
require([
  "dijit/dijit",
  "dojo/parser",
  "maqetta/space",
  "maqetta/AppStates",
  "dijit/form/Button",
  "dijit/Calendar"
]);
</script>
<style>@import "themes/claro/document.css";@import "themes/claro/claro.css";@import "app.css";
</style>
<script type="text/javascript" src="app.js"></script>
</head>
<body class="claro" data-maq-flow-layout="false" data-maq-ws="collapse" id="myapp" data-maq-appstates="{}">
 <img src="samples/SampleBanner.jpg" style="position: absolute; z-index: 900; left: 41.5px; top: 87.5px;"></img>
 <a>
</a>
 <div style="height: 126px; background-color: red; width: 646px; position: absolute; z-index: 900; left: 60px; top: 6.5px;">
 <span><input type="button" data-dojo-type="dijit.form.Button" intermediateChanges="false" label="Button" iconClass="dijitNoIcon" style="position: absolute; z-index: 900; left: 501px; top: 166px;"></input>
   </span>
   <input data-dojo-type="dijit.Calendar" style="position: absolute; z-index: 900; left: 460px; top: 241.5px;"></input>
 </div>
 </body>
</html>

```

Select the Calendar, right click to get the context menu chose "Select ancestor..."

Note the following exception
this._selectAncestor is undefined

Line 37511

Chose ``<div.>` from the drop down, click ok 

the selection stays on the calendar instead of moving to the div

**Comment by JonFerraiolo** [comment]
Passing to @doronrosenberg, who is the expert on dialogs

The immediate cause of this exception is that ve/actions/SelectAncestorAction.js crashes because `selWidget` has no value. This regression is because the dialog contents are not parsed (and therefore dijit widgets aren't created).

There are multiple possible ways to fix this:
- Don't use Dijit, use HTML instead
- Find a way to tell the Dialog logic that it should parse the content
- Don't call Workbench.showMessage (which calls our Dialog logic), and instead create some dialog UI from scratch that properly invokes the parser

@doronrosenberg - please either fix or simply suggest a best approach and send back to me
