### ISSUE TITLE
Warning message in FF console when maqettta loads 

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#3188]
I see lots of these messages in the console on FF/Win7

Element referenced by ID/NAME in the global scope. Use W3C standard document.getElementById() instead.

var _19ea=mainBody.tabs.perspective[_19e8];

**Comment by JonFerraiolo** [comment]
FWIW - This is old, old code.

**Comment by JonFerraiolo** [comment]
-> @billreed63 

I think the fix is to simply do a `dojo.byId()` in front of each case where there is a FF message. For example, in Workbench.js:hideView(), put this line:

```
var mainBody = dojo.byId('mainBody');
```

just above this line:

```
        for (var position in mainBody.tabs.perspective) {
```

I see "naked" references to mainBody in `hideView()` and `_rearrangePalettes`. I'm not sure if there are other offending variables that Win/FF doesn't like (i.e., other than `mainBody`).

**Comment by JonFerraiolo** [comment]
But one thing I'll say: it's not very good to add a property such as `tabs` to a Element object. Should at least make it `_tabs` and probably `_maqTabs`. But that's for the future...

**Comment by billreed63** [comment]
The warnings are gone with the latest code and FF 15
