### ISSUE TITLE
Zazl does not filter bootstrap code with modified libs

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#3208]
@childsb

see #3171

**Comment by rbackhouse** [comment]
Here are some more details on the issue :

When a project has its lib setting modified. the Zazl code pulls from the Library objects configured from the plugins. The per project lib changes are not reflected in the Libary object and must be available somewhere else. I haven't figured where that is yet. the result is that if the lib settings are changed for dojo the filter does not locate the dojo.js script tag and zazl is not used for the page.

**Comment by rbackhouse** [comment]
After doing some investigation it turns out I can get hold of the user library changes made to a project by calling 

IUser.getLibs(projectname);

This pulls in the library configuration found in <project dir>/.settings/lib.settings.

I can then use the virtualRoot value for the corresponding library as the comparison for a matching path instead of Library.getDefaultRoot().

My only concern is that I will have to call IUser.getLibs(projectname); for each resource request as I have to ensure I pickup the latest values. I'm not sure if the maqetta code is only reloading the file when it has changed or if it get read each time the getLibs call is made.

**Comment by peller** [comment]
@rbackhouse ok to close this?

**Comment by rbackhouse** [comment]
Yes I think so
