### ISSUE TITLE
Orion Navigator: Open in Maqetta doesn't work

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#3262]
@childsb 

Using Chrome on Mac going to moketta and doing Orion Integration test case...
1. Go to Orion Navigator
2. Create a new folder
3. Create new subfolder
4. Select newest folder and choose Open in Maqetta --- nothing happens... a couple errors in console, but seem kind of irrelevant...

![GitHub Logo](http://i.imgur.com/WGRvr.png)

**Comment by aerwin** [comment]
Realized I created the folders starting at root rather than in a project (though test case doesn't really specify). When I tried within project, still didn't work.

**Comment by childsb** [comment]
Do you have pop up windows blocked from localhost?

This works for me, but on FF i get an error about "this site wants to do a local popup, is this ok" and i have to set allow always for this domain.

**Comment by aerwin** [comment]
Did you try Chrome going to moketta? That's my configuration. I don't see any warnings about pop-ups.

**Comment by aerwin** [comment]
Works for me in FF, so must be Chrome issue. And, perhaps specific to Chrome going to moketta.

**Comment by JonFerraiolo** [comment]
On Win/FF running on the moketta staging server, when I bring up the Orion user interface, I don't see any way to open an HTML file in Maqetta. What am I missing? Two problems I see:
- The Action menu doesn't show any entries about opening in Maqetta
- Even if the Action menu had an "Open in Maqetta" command, I don't see how to select a file in the Orion navigator so that you could invoke "Open in Maqetta" on the file. Clicking on a file name causes Orion to open the given file in the text editor.

**Comment by JonFerraiolo** [comment]
Oh, now I see how to do select with the Orion UI - click on the row, but not on the text. IMO, that's not a good way to go for the UI - way too obscure. If single-click will be used to bring up editor, then provide a checkbox or button to cause a select operation. @jhpedemonte: any opinions from a UI perspective?

**Comment by jhpedemonte** [comment]
Well, that's the Orion UI.  We can open up bugs with them.  But in general, yes, very obscure UI.

**Comment by jhpedemonte** [comment]
Fixed by commit 2bed0431788c16ead19f0c7ebb52f0959dfab6b4.

Just tested and it is working well for me.
