### ISSUE TITLE
Table context menu select column and select row images reversed, remove row off screen

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#3285]
![GitHub Logo](http://i.imgur.com/jPWQv.png)

**Comment by aerwin** [comment]
I didn't add the images, but I can clean up the CSS.

The context menu being too long is covered by another issue. I believe you opened that one so I won't look up the number.

**Comment by jhpedemonte** [comment]
@doronrosenberg @peller @JonFerraiolo 

Is there a way to ensure that the context menu comes up in bounds?  There's no reason the context menu **has** to start at the cursor.  Most apps work around this issue by moving the context menu up (or down) so that it fits.  That might be an easy fix for M7.

**Comment by JonFerraiolo** [comment]
I would strongly push for deferral to M8. Any fix would almost certainly change common code in Workbench.js that is used by dozens of different menus. Note that the table commands are also available on the toolbar, so if a user says on the forum, hey, I can't get to all of the context menu commands, then we can say use the toolbar icon instead.

**Comment by aerwin** [comment]
There should be a separate issue opened for any menu length/position bugs if we don't think the one @billreed63 opened awhile back is sufficient.

I'm going to use this one to fix the icons (which is the core of the bug report).

**Comment by aerwin** [comment]
Closing with above commit.
