### ISSUE TITLE
Migration: eclipse project, top level file does not render

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#3299]
I have an eclipse project called eclipseproj1 with file1.html (mobile app) located at the top (peer with WebContent)  Works in M6.  In M7, the file opens with no theming.

**Comment by jhpedemonte** [comment]
@childsb @aerwin @JonFerraiolo  Do we support this for Eclipse projects?

**Comment by JonFerraiolo** [comment]
Idealistically spekaing, I would say that this should be supported ultimately, but as a low-priority feature in the short-term. 

However, I expect that because we didn't bulletproof M6 and earlier to prevent or discourage files outside of WebContent/, there will be a number of users who have files in the same place as @peller. Therefore, we should investigate what's broken and make an assessment of whether a quick and safe fix is available. (I expect not, and that we will have to just say sorry for M7)

**Comment by peller** [comment]
no problem.  just figured I'd test an edge case.  Note that this worked in M6 and continues to work in M7, it's just a migration issue.

**Comment by jhpedemonte** [comment]
-> @peller

**Comment by peller** [comment]
seems to work now.  one of the later migration scripts must have resolved this problem.
