### ISSUE TITLE
Column width control for tables

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#331]
@billreed63

Our <table> element support is actually pretty good right now, but the one big
thing that users need is the ability to control column widths. Right now, all
columns are set to auto-sizing (the browser default). Often, the user needs to
set fixed widths (eg 100px or 10em) or percentages (e.g., 33%) when using
tables either for tabular information or (sorry, this is going to happen) for
layout.

Here is a proposal. 
- Add a Select Column command to the context menu when a table cell is
  selected. This in effect selects one of the <col> elements in the current
  table. (If the table doesn't have <col> elements, then add them as <col/>, one
  for each column.)
- When a column in selected, the canvas should put a selection highlight around
  the given column and the Properties palette should show <col> as the widget
  name.
- The user can set anything on the Properties palette, but our "dealing with
  tables" tutorial(s) should warn users that browsers only support a few CSS
  properties on <col> elements. (width, borders, backgrounds - that's about it, I
  think)

Looking at the list above, this is a non-trivial assignment that will touch
several sections of the code.

**Comment by JonFerraiolo** [comment]
Assigned to @aerwin

**Comment by aerwin** [comment]
@JonFerraiolo Per earlier discussion today, moving table feature requests in my name to M6.

**Comment by aerwin** [comment]
@JonFerraiolo @billreed63 @jhpedemonte 

This is intended to be a sort of a "speclet" in draft form to help organize my thoughts and (hopefully) spur discussion on this feature (both in terms of how we want to scope the work for M6 and in how we  eventually want things to work).

# Introduction/Assumptions

While this feature request was written specifically for setting of column widths, I've been considering this from the slightly broader perspective of column _editing_. So, in addition to width, this would encompass selection of what columns to include, order of columns, etc.

We currently have three grid-type widgets for which we plan to consider column editing:
- GridX (new to the untested widget section in Sprint 1 - M6)
- DataGrid
- HTML tables

I suspect this feature request was probably geared more toward HTML tables, but as a first stab here we will be focusing on GridX (with the hope the approach will be directly applicable to DataGrid and perhaps portions also applicable to HTML tables). 

# Smart Input for Grids

The current Smart Input dialog for DataGrid and GridX is used to specify the source of data for the underlying widget. 
- Comma separated data
  
  ![Data source - Comma separated data](http://i.imgur.com/cPksB.png)
- Data file from workspace
  
  ![Data source - Data file from workspace](http://i.imgur.com/AlRN8.png)
- Data from URL
  
  ![Data source - Data from URL](http://i.imgur.com/q3ZPd.png)

When **OK** is pressed on this dialog, a data store is created and associated with the widget. In addition, the _structure_ of the data (e.g., the column definitions) are calculated and associated with the widget.

# Column Editing

My initial proposal for column editing would leave the existing smart input for GridX/DataGrid in place. A menu option for **Edit Columns…** would be added to the context menu shown for the selected GridX: 

![Grid Menu](http://i.imgur.com/s8L7W.png)

**NOTE:** In order to add a new menu option, Maqetta architectural changes would need to be made to allow for widget libraries to supply custom actions. One way this could possibly be done is for a new `getActions` function to be added to the widget helper interface that returns an array of actions.

When clicked, the new menu option would launch a similar dialog to the following:

![Grid Column Editing](http://i.imgur.com/3Mv5d.png)

The dialog would have the following components:
- Some basic instructions for how to use the dialog (not shown)
- An instance of GridX acting as a preview of the widget selected in the Visual Editor. The GridX instance would be active and have GridX functionality enabled for column resizing, column selection, and column DnD. In the screen shot, I've resized all of the columns and moved the _State_ column so that it appears right next to the _ID_ column.
- A **Restore Defaults** button (not shown) that when clicked restores the structure (e.g., the original order and size of columns) to what it was when the data store was first associated with the grid.
- An **OK** button that when pressed uses GridX functionality to get the order of the columns, their sizes, etc. This information is then used to modify the structure of the underlying widget.
- A **Cancel** button which when clicked dismisses the dialog and makes no changed to the underlying widget.

## Advantages of Dialog over Direct Manipulation in VE

One might ask why we're not just allowing the user to do the things they can do in the new dialog via direct manipulation in the Visual Editor. While there are obviously certain advantages to direct manipulation, there are a few big reasons the dialog approach is preferable:
- GridX already has native support (via included plug-ins) for column resizing, column selection, and column DnD. And, it clearly makes sense to re-use this if at all possible rather than reinvent the wheel. In addition, the Visual Editor is not currently architected to delegate functionality that calls for user interaction to the underlying widget.
- GridX does not have contain child dijit's, so there's not really anything to add to the Visual Editor's model for setting of properties, etc. Something would need to be architected where dummy, proxy UI widgets of some kind could be created for the Visual Editor to work with.
- The dialog could be relatively easily extended in the future to use GridX functionality to allow the user to specify initial sorts, initial filters, etc. in addition to the basic column attributes.

# Tighter Integration of Data Store Set-up and Column Editing

## Selecting What Columns to Show

One drawback to the new dialog is that it doesn't facilitate selection of what columns should be made visible to the user. This becomes especially important when the data the grid shows comes from a file or URL. So, I think we will want to add a column chooser feature.

This could be done via a "slosh bucket" approach like the following:

![Column Selection Slosh Bucket](http://i.imgur.com/hgEl9.png)

One way to expose this would be to add a **Choose Columns…** button to the column editor dialog that launches a secondary dialog showing the slosh bucket.

## A Table Wizard??

The approach described to this point has some appealing qualities:
- The Data Store Smart Input is used all over the place, so leaving it alone means we keep a great deal of consistency across all data store-enabled widgets.
- Once the data store has been set-up via Smart Input, the user can go directly to the column editor/chooser at any time without needing to worry about data store set-up again.

However, you could also argue:
- column editing/choosing should be available as part of what the user sees when they launch smart input on a grid (e.g., a Maqetta user conditioned to double-click to bring up smart input rather than look for separate menu item)
- When first creating the grid, column choosing is fundamental to initial set-up.

So, if those arguments carry the most weight with the team, we might eventually want to create a Table Wizard to replace existing smart input. The wizard could have the following steps:
- Data store selection (e.g., a panel containing the contents of the current Smart Input dialog)
- Column choosing (e.g., a panel showing the "slosh bucket" of available and selected columns)
- Column editing (e.g., a panel with the grid preview for column resizing. etc.)

# GridX Configuration: Going Beyond Data and Column Setup

While perhaps going a bit beyond the scope of the feature request, there are some other GridX considerations that should probably be discussed while we're on the topic of smart input, supporting dialogs, and wizards. In short, the widget-specific properties section of the Properties Palette is not sufficient for what needs to be done to fully configure GridX. And, I think we'll either need to add a **Manage features…** option to the GridX context menu or add additional intermediate steps to the eventual table wizard flow.

Most notably, GridX functionality (e.g., column selection, pagination, etc., etc.) is not determined by individual attributes, but instead is determined by an array of plugin modules that are specified at construction time. So, while it would be natural to present the user with a setting like "Enable column selection" there isn't an _enableColumnSelection_ attribute. So, our current approach for widget-specific properties in the Properties Palette doesn't really work for GridX.

Below is the list of available plugins:
- FormatSort
- Focus
- VScroller
- VirtualVScroller
- ColumnResizer
- SingleSort
- NestedSort
- ColumnLock
- SelectRow
- SelectColumn
- SelectCell
- ExtendedSelectRow
- ExtendedSelectColumn
- ExtendedSelectCell
- MoveRow
- MoveColumn
- DndRow
- DndColumn
- AutoScroll
- Pagination
- PaginationBar
- PaginationBarDD
- Filter
- FilterBar
- CellWidget
- Edit
- RowHeader
- IndirectSelect
- Persist
- Exporter
- ExportCSV
- ExportTable
- Printer
- Menu
- Dod
- TitleBar
- Tree
- RowLock
- ToolBar
- SummaryBar

In addition, there is some further customizations that can be done for several of the plugins via attributes set on GridX. But, obviosuly, it only makes sense to enable editing of those attributes if the associated plugin has been turned on. This again is not something the widget-specific part of the Properties Palette is setup for. Here is a list of those attributes and their associated plugins:
- General (no plug-in required)
  - autoWidth 
  - autoHeight
- Header
  - headerDefaultColumnWidth
- VScroller
  - vScrollerLazy
  - vScrollerLazyTimeout
  - vScrollerBuffSize
- ColumnResizer
  - columnResizerMinWidth
  - columnResizerDetectWidth
- Tree
  - treeNested
- ColumnLock
  - columnLockCount
- Dod
  - dodUseAnimation
  - dodDuration
  - dodDefaultShow
  - dodShowExpando
- Sort
  - sortPreSort
- filterBar
  - filterBarMaxRuleCount 
  - filterBarCloseFilterBarButton
  - filterBarDefineFilterButton
  - filterBarTooltipDelay
  - filterBarRuleCountToConfirmClearFilter
- Pagination
  - paginationInitialPage
  - paginationInitialPageSize
- PaginationBar
  - paginationBarVisibleSteppers
  - paginationBarSizeSeparator
  - paginationBarPosition
  - paginationBarSizes
  - paginationBarDescription
  - paginationBarSizeSwitch
  - paginationBarStepper
  - paginationBarGotoButton
- RowHeader
  - rowHeaderWidth
- SelectRow
  - selectRowTriggerOnCell
  - selectRowMultiple
- SelectColumn
  - selectColumnMultiple
- SelectCell
  - selectCellMultiple
- MoveCell
  - moveCellCopy

**Comment by aerwin** [comment]
On April 20, a group of us (@peller @JonFerraiolo @jhpedemonte @billreed63) met to discuss the proposal I posted earlier that day (see above). There was a lot of really good discussion, but the big conclusion from that meeting was that we should go ahead and pursue a wizard approach for GridX Configuration consisting of 3 panels:
- Data source configuration
- Column selection (via slosh bucket)
- Grid preview with column resizing/reordering

With the 9c14d3d8ba394744bc7e6f9f82dca6a4fa01f0ac commit above, a fairly robust GridX Configuration Wizard is now in place. However, there are a few caveats:
- misc bugs/clean-up items still need to be be addressed (see #2152)
- modification of column attributes via editable fields in a pseudo-properties palette is not yet implemented (see #2155)
- managing of GridX plug-ins (which we had all agreed could be implemented later) -- see #2153

So, I'm going to close this ticket and follow-on work will be completed under the separate GitHub items listed described above.
