### ISSUE TITLE
Cut/Paste of a TabContainer that has a child Tree throws exception

### ISSUE THREAD

**Issue by doronrosenberg** [maqetta/maqetta#3328]
@JonFerraiolo @jhpedemonte @aerwin @childsb (I forget who worked on Tree)
- dnd a TabContainer
- dnd a Tree into the first tab
- Cut the TabContainer
- Paste it

```
TreeHelper.Reparent error processing tree.
http://app.moketta.org/maqetta/app/metadata/dojo/1.8/dijit/TreeHelper.js?@revision@
Line 46
```

**Comment by doronrosenberg** [comment]
I'll take a gander tomorrow

**Comment by doronrosenberg** [comment]
My guess is this is datastore related - when I first ran into the issue messing around I reloaded and it loaded a page without a store, but that was after some undo/redoing after the exception

**Comment by doronrosenberg** [comment]
@jhpedemonte Are we creating the Tree before its container has been created perhaps?  The Tree and Model have different parents when TreeHelper::create is called during the paste, even though they were copied with the same parent?

Looks like TreeHelper is moving the model/store and then someone else is creating them as well, so we end up with 2 models and 2 stores.  Easier way to reproduce is have a div that contains the Tree and cut/paste the div.

**Comment by aerwin** [comment]
@doronrosenberg I don't know the reparent code real well, but why is there a create in TreeHelper? With cut/copy/paste, TreeCreateTool would be invoked. So, if both are being invoked it would seem to explain some of the behavior you describe.

**Comment by doronrosenberg** [comment]
@aerwin @JonFerraiolo @jhpedemonte 

Interestingly enough, dnd is not calling reparentcommand - its doing a add and then a remove command (which seems wrong, shouldn't that be a remove first?).  Seems that is the reason why TreeHelper::create has to call its reparent() method each time, to handle that dnd case.  Which then breaks paste.

Is there a reason why we can't simply use reparent command when manually dnding widget?

**Comment by doronrosenberg** [comment]
Looks like the code is all `SelectTool::onExtentChange`.  Looks like its generic code to deal with selection moving/copying.  It would seem possible to handle non-copies as reparents, but might be a bit late in the game for such a change perhaps.  I'll try to create a patch and see how dangerous it will be.

**Comment by doronrosenberg** [comment]
Here is a diff of my patch, seems to fix the issue: http://pastebin.com/YfMqKz5Z

**Comment by jhpedemonte** [comment]
Yes, that's a pretty big change this late in the game, given that it'll affect every widget.  The stuff in **SelectTool** is particularly finicky at times.

We'll commit this quickly at start of M8, giving us enough time to test.  @JonFerraiolo

**Comment by doronrosenberg** [comment]
@jhpedemonte @JonFerraiolo This one is important

**Comment by JonFerraiolo** [comment]
Top on my list too. I need to spend an hour or two tracing through all of the code that ends up going through that part of onExtentChange(). I'll try to do that soon.

**Comment by doronrosenberg** [comment]
@JonFerraiolo do you want me to wait for you to trace before I check in the fix?

**Comment by JonFerraiolo** [comment]
Until I study things, probably best to commit to a branch. I hope to find time today.

**Comment by JonFerraiolo** [comment]
I did a first pass review of the patch you created and I see one thing that worries me. In one test case, I had 2 DIVs and a Button in one of the DIVs. Then I dragged the Button from the first DIV and dropped into second DIV (a reparent operation).

The problem I saw when tracing through that operation is that:
- We call `createWidget()` at SelectTool.js:459
- In the proposed patch, instead of calling `AddCommand()` we would call `ReparentCommand()`, which means AddCommand() would not be called
- Looking at AddCommand.js and ReparentCommand.js and tracing through the code, I see that they aren't substitutes for each other. In particular, AddCommand.js calls widget.attach() (which in turn my call the create helper for the particular widget), but ReparentCommand.js does not.

Therefore, I'm pretty sure we would end up with a `createWidget()` followed by a `ReparentCommand()` which my analysis does not call all of the mop-up code that must get called after doing a `createWidget()`.

I'm not sure what adjustments to propose instead. I'm still studying things. In particular, I'm very hesitant to beef up ReparentCommand(). Maybe we can avoid the `createWidget` call in the case when all we need to do is reparent.

**Comment by doronrosenberg** [comment]
Perhaps we should remove and then add widgets in SelectTool instead of add and then remove?

**Comment by doronrosenberg** [comment]
The cleanest way would be to have a CreateTool method that gets called whenever we relocate a widget in the VE (copy/paste, dnd) similar to _getCreateCommand() or addPasteCreateCommand().  Something we can inject any additional commands into that gets executed once paste/dnd is finished.
