### ISSUE TITLE
Browsers don't save user/pass info for maqetta.org

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#3375]
@JonFerraiolo @jhpedemonte @childsb 

Opening for M7.0.1 for discussion...

Per e-mail conversation...

Me:

> > I've noticed that Chrome doesn't offer to save my password... suppose I should have noticed this during development but with all of the re-registration we were doing as builds changed and such I didn't think about it much.
> > 
> > Are we doing something that would prevent browsers from wanting to save passwords?

@JonFerraiolo 

> I looked at the code in LoginWindow.html and LoginWindow.js and I don't see anything funny. Clearly something is wrong, but nothing leaped out at me.

**Comment by JonFerraiolo** [comment]
I may have found the reason at http://www.sencha.com/forum/showthread.php?6450-Saved-user-credentials-and-dynamic-forms-possible&p=257337&viewfull=1#post257337

```
I figured that it's not possible to have a JavaScript injected form and password auto-completion at the same time. The password auto-completion takes place before the JavaScript can generate the form.
```

It might be that the parent container has display:none when the page is first loaded.

**Comment by JonFerraiolo** [comment]
Nope, I played with things, and couldn't get either username or password to get saved across sessions.

@doronrosenberg - any knowledge in this area?

**Comment by doronrosenberg** [comment]
Oh boy, fun stuff.  Patch that fixes it for me is http://pastebin.com/Aa8Np5ca

**Comment by JonFerraiolo** [comment]
@doronrosenberg - Thanks a bunch!

Assigned to me. I'll merge in the patch, test on our target browsers and then commit.

**Comment by peller** [comment]
Is the LoginWindow descended from Orion code?  If so, can we share the patch or find a way to share code with Orion?

**Comment by JonFerraiolo** [comment]
> Is the LoginWindow descended from Orion code? If so, can we share the patch or find a way to share code with Orion?

@childsb Do you know the history for LoginWindow.*?

**Comment by childsb** [comment]
Yes I did copy LoginWindow.\* from Orion.  I'm sure they'd like your password saving changes pushed back ((probably best to open a bug on them w/the solution))

**Comment by JonFerraiolo** [comment]
Commit above should be good for 7.0.1. Leaving this open until I can verify in builds.

Note that Firefox seems to be in good shape - login is preserved across sessions, and Firefox offers to save your password. But with WebKit, we only preserve the login (via the use of a cookie). To get WebKit to work completely, we would need to make some server changes.

Some notes learned along the way:
- Firefox will save form data (and offer to save your password) if you simply put an ID on the FORM element and have a submit button
- WebKit will only save form data (and offer to save your password) if you have a FORM with an 'action' with method=GET (the default) and that action actually happens and the form fields that you want to preserve have 'name' attributes. (In other words, form data is only saved with a form submit using a GET.) I actually changed LoginWindow.js to do all of this, but what happens is that the Maqetta server doesn't strip off the URL parameters, and the URL bar says `http://localhost:8018/maqetta/?login=uuuu&password=pppp`, which besides putting the user's login and password in the URL bar when Maqetta runs, also causes RSOD because when the client-side code constructs a base path for various URL requests, we don't strip off the URL parameters.

**Comment by peller** [comment]
is #2348 the same as the url parameters problem?

Also, I suggest leaving this open until a ticket is logged with orion

**Comment by JonFerraiolo** [comment]
> is #2348 the same as the url parameters problem?

I believe so

**Comment by JonFerraiolo** [comment]
verified on *standard and *hosted, still need to check on the internal hosted build

**Comment by JonFerraiolo** [comment]
verified on internal build, closing
