### ISSUE TITLE
Orion user id's are not consistent

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#3406]
@childsb @JonFerraiolo 

Spinning this off from #3355 based on @JonFerraiolo 's statement:

> For example, on staging server, there are two users, let's call them USER1 and USER2. When the invite goes out, USER1 is B and USER2 is G. But then when USER1 attempts to add an annotation, now he is C, which isn't either B or G, so his own annotations are filtered.

I don't know how to make this happen, but seems bad if that's truly the case. #3355 will be used to code around one of the known side effects, but that does not address this core issue of inconsistent user id's.

**Comment by jhpedemonte** [comment]
One possibility, previously mentioned by Jon:  we are confusing **user IDs** and **project directories**.  Both are handled by Orion and specified as A, B, C, ... GA, GB, ...  So it's conceivable that we're mixing them up at some point.

For the purposes of Review code, it would be best if our Maqetta code only worked in **email addresses**, then when necessary made the conversion to Orion names.

This is particularly important since we allow specifying a user who has not yet registered and therefore does not have an Orion ID yet.

**Comment by JonFerraiolo** [comment]
Note that with #3355, in the logic to show/hide annotations, we will be avoiding possible server-side user identity issues by fixing the client-side code to only use email addresses and not user IDs. @aerwin
