### ISSUE TITLE
AssertionError in DavinciCommandServlet ("resetPasswor")

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#3435]
```
2012-09-15 13:23:21.121 [qtp1301257077-318] WARN  o.e.jetty.servlet.ServletHandler - Error for /maqetta/cmd/resetPasswor
java.lang.AssertionError: commandDescriptor is null or is Put in Get processing
    at org.maqetta.server.DavinciCommandServlet.doGet(DavinciCommandServlet.java:42) ~[na:na]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:735) ~[javax.servlet_3.0.0.v201112011016.jar:na]
    at org.maqetta.server.DavinciCommandServlet.service(DavinciCommandServlet.java:105) ~[na:na]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) ~[javax.servlet_3.0.0.v201112011016.jar:na]
    at org.eclipse.equinox.http.registry.internal.ServletManager$ServletWrapper.service(ServletManager.java:180) ~[na:na]
```

@maqetta/committers

**Comment by jhpedemonte** [comment]
Notice the `/maqetta/cmd/resetPasswor`, missing a 'd'.  Do we have an incorrect call somewhere, or did someone mess with the URL?

**Comment by jhpedemonte** [comment]
Hmm, see several instances of this over the past few days:

```
maqetta.log-20120916:2012-09-15 13:23:21.121 [qtp1301257077-318] WARN  o.e.jetty.servlet.ServletHandler - Error for /maqetta/cmd/resetPasswor
maqetta.log-20120916:2012-09-15 21:05:15.939 [qtp1546250801-362] WARN  o.e.jetty.servlet.ServletHandler - Error for /maqetta/cmd/resetPasswor
maqetta.log-20120917:2012-09-16 04:39:03.199 [qtp1546250801-662] WARN  o.e.jetty.servlet.ServletHandler - Error for /maqetta/cmd/resetPasswor
maqetta.log-20120917:2012-09-16 10:47:07.421 [qtp1546250801-1013] WARN  o.e.jetty.servlet.ServletHandler - Error for /maqetta/cmd/resetPasswor
maqetta.log-20120919:2012-09-18 06:34:38.384 [qtp254232091-1392] WARN  o.e.jetty.servlet.ServletHandler - Error for /maqetta/cmd/resetPasswor
maqetta.log-20120919:2012-09-18 15:47:50.534 [qtp254232091-2106] WARN  o.e.jetty.servlet.ServletHandler - Error for /maqetta/cmd/resetPasswor
maqetta.log-20120919:2012-09-18 22:42:46.964 [qtp254232091-2619] WARN  o.e.jetty.servlet.ServletHandler - Error for /maqetta/cmd/resetPasswor
maqetta.log-20120920:2012-09-19 07:01:58.889 [qtp1359920664-41] WARN  o.e.jetty.servlet.ServletHandler - Error for /maqetta/cmd/resetPasswor
```

**Comment by JonFerraiolo** [comment]
I haven't found anything wrong yet.

One thing to consider: Is it possible that the Jetty log system is truncating `/maqetta/cmd/resetPasswor` because there is an arbitrary 25-char limit? If there is truncation going on, then maybe the URL requests are OK, but something else is amiss.

@jhpedemonte and @JonFerraiolo searched the sources and didn't find any misspellings where the code uses `resetPasswor` instead of `resetPassword`. 

@JonFerraiolo verified that he was able to reset his password on maqetta.org.

There are 3 places in DavinciCommandServer.java where we post the error message shown above: in doGet, doPut and doPost. Since we are doing POST commands to reset passwords, you would think that the we go into the doPost command, but if somehow or other a GET or PUT command was executed, then that would raise the error.

Assuming though that we do indeed send POST commands (and that's all I saw in LoginWindow.js), the error message gets generated if the following conditional fails:

```
        if (commandDescriptor == null || commandDescriptor.isPut()) {
            throw new java.lang.AssertionError(new String("commandDescriptor is null or is Put in Post processing"));
        }
```

`commandDescriptor` is null if the URL was empty, but it looks like in most cases the URL will be `http://maqetta.org/maqetta/cmd/resetPassword'. 

The check `commandDescriptor.isPut()` appears to be attempting to verify that this was a PUT command and not GET or POST. I looked over the code around `isPut` and nothing leaped out at me.

**Comment by jhpedemonte** [comment]
>  arbitrary 25-char limit

No, there are other messages with longer text, so that's not it.

These errors always come from `doGet`, meaning that this is a GET request.  However, as Jon mentioned, we only ever do POST requests to reset the password.  So not sure where this is coming from.

**Comment by JonFerraiolo** [comment]
-> @jhpedemonte

**Comment by jhpedemonte** [comment]
Haven't seen this in a while.  Also, we are now using Orion's password reset.  Closing.
