### ISSUE TITLE
Table columns unselected when property is changed

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#3498]
Using Chrome on Mac...

I think this must be a fairly recent regression...
1. New HTML file
2. Add HTML table to canvas
3. Select a column
4. Using props palette, change background color and note column is unselected

Cells and rows seem to stay selected when their props are changed, so seems column specific.

**Comment by JonFerraiolo** [comment]
Debugging suggestion: try to put a breakpoint in Context.js's select() and deselect() methods. My first guess is that someone is calling select() and that logic isn't dealing with column selection properly.

**Comment by billreed63** [comment]
-> M9
@JonFerraiolo @jhpedemonte

**Comment by billreed63** [comment]
When we change the background color on a `<col>` the styleChangeCommand triggers `context.onContentChanged` that calls `context.deselectInvisible` which uses this code

```
// Assume that if all offset values are zero, then widget has display:none somewhere in ancestor DOM hierarchy
if(domNode.offsetLeft==0 && domNode.offsetTop==0 && domNode.offsetWidth==0 && domNode.offsetHeight==0){
    this.deselect(widget);
}
```

the offsets for the `<col>` are all 0 so the widget is deselected.
So it would appear that this bit of code for determining viability does not work for `<col>`

**Comment by JonFerraiolo** [comment]
Two ideas come to mind: (1) instead of checking offset_, traverse up through the domNodes until reaching the parent to see if this widget or any ancestor has display:none (which we are doing in a more complicated way in States.js:getEffectiveDisplayValue() where it does its calculations base on a particular state, not necessarily the current state), (2) check for offset_ except for html.col, and for that instead check the offset\* values for its nearest ancestor table element.

Option (1) seems more general purpose, but might break other things.
