### ISSUE TITLE
Source editor -- Uncaught TypeError: Object [object HTMLHtmlElement] has no method 'selectChild' 

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#3514]
Using Chrome on Mac and local server running from Eclipse...
1. New HTML file
2. Refresh browser to get rid of any potential lingering effects of #3513
3. Switch to source view
4. Add div (e.g., paste something like `<div>HELLO</div>` into the body)
5. Switch to Design view and try to select div and see following exception in console (and no selection change):

```
Uncaught TypeError: Object [object HTMLHtmlElement] has no method 'selectChild' Context.js:2017
declare.select Context.js:2017
declare.onMouseUp SelectTool.js:268
declare.onMouseUp Context.js:2341
(anonymous function) lang.js:373
```

**Comment by JonFerraiolo** [comment]
Caused by this commit: 8a3627d2151462129f1b2b72acf91054d6e530c7

The actual problem as reported by @aerwin has to do with the mouse event and selection code producing an exception. The cause of that exception is upstream logic in (in _processWidgets() in Context.js?) that for some reason no longer ends up parsing the new DIV element that was just typed into the source pane. As a result, this DIV doesn't get converted into a dvWidget. So, when attempting to click-select, bad things happen because the page editor logic assumes that all HTML elements in the document have been converted into dvWidgets.

**Comment by peller** [comment]
Do you think there error is new, or just the error reporting?  Are there side-effects?

**Comment by aerwin** [comment]
Yes, I think new. And, yes, side effects (as mentioned above), can't select the new widget added via source.

**Comment by JonFerraiolo** [comment]
Yes, definitely new. See above for the commit that caused the regression.

**Comment by peller** [comment]
ok, all I was missing was the stack trace with _processWidgets(). see it now.
