### ISSUE TITLE
Unable to change hieght/widget on mobile TextArea

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#3532]
Create mobile htkp
DnD
view, header, RoundRec and mobile TextArea change width to 100% and height to 150px

The width seems to change ok on the element the first time but when I attempt to change the height I get the read only theme error box. Note that in the cascade the element is missing.

**Comment by billreed63** [comment]
@aerwin  I think what I was seeing on maqetta.org was it was taking so long for some of the css files to load in the model that maybe the request was timing out and the model was not building so we were defaulting to the root element.
I have no idea why it was working for you locally.. 

The updated metadata works for me locally, So I guess the question is will this fix be deployed before the article?

**Comment by aerwin** [comment]
@billreed63 

Thanks, Bill... 

> I have no idea why it was working for you locally..

I'm guessing it worked locally because the css files would have loaded much faster? On the positive side, 7.0.2 should be out well before the article and files should load much faster on maqetta.org.

> So I guess the question is will this fix be deployed before the article?

How risky is the fix to the metadata?

@JonFerraiolo @peller @jhpedemonte 

Would you guys entertain a low-risk metadata change (assuming that's what it is) for 7.0.2? I think this (and #3512) are kind of major black eyes irregardless of the article.
