### ISSUE TITLE
maqetta.core.client and other projects not getting JAR'd

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3577]
I downloaded the latest build on my old Windows XP machine to test out local install. After waiting FOREVER for the download, I ran the windows launch script and noticed that it took a really long time for the `osgi>` prompt to appear. Then I looked at the `plugins` folder and there is no JAR for maqetta.core.client (and probably some others), instead an expanded folder.

By having a zillion loose files instead of a JAR, downloads and program startup are slowed down by a major amount. Apparently, the old Windows XP file system is an order of magnitude slower at file system actions that a modern-day Mac.

**Comment by jhpedemonte** [comment]
Hmm, I'd removed the code (commit 20564c6f8f6f46a3f02700f40a27f7e0d549865f) that specifically set some plugins to be jarred (instead of being "exploded" by default) since that code didn't really have the performance impact that was intended (perf issue was caused by something else).

But you're saying that you see a noticeable difference when starting up the server on a WinXP system?  Can you please compare against a [nightly build](http://maqetta.org/nightly/) from Nov 12 (before my commit)?

**Comment by JonFerraiolo** [comment]
I compared the Nov 12 nightly build (Jar'd) with the Nov 26 nightly build (not Jar'd).

Nov 12:
- Download size: 97M
- Un-tar time: 4 min
- Launch script time: 1:00 min

Nov 26:
- Download size: 105M
- Un-zip time: 24 min
- Launch script time: 2:08 min

I'm not sure why the launch times differ, maybe Java's ability to pull data out of a JAR is faster than the operating system loading a file. I'm pretty sure the Un-zip time is due to having to deal with zillions of separate file versus a handful of JARs.

**Comment by jhpedemonte** [comment]
It looks like you are comparing a non-hosted build (Nov 12) against a hosted one (Nov 26).  Just to be sure, could you compare against the same type of build?

**Comment by JonFerraiolo** [comment]
Oh sorry, I pulled the download size by looking at the nightly folder on the web, and misrecorded the download size (now updated in my earlier comment above). I did actually pull down and run my timing tests against the non-hosted version for both Nov 12 and Nov 26.
