### ISSUE TITLE
Reviewers should see all files they have been requested to review in the review panel

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#360]
@billreed63, @jhpedemonte, @EldonReturn

Relates to some comments found on this wiki page: 
https://github.com/maqetta/maqetta/wiki/Review-Commenting-Usability-and-URL-Redirects

When the user looks in the review panel they should see a list of all the pages
that other users have asked them to review, currently only the page owner see
this. How does the user get to a page he has been asked to review if he deletes
his email with the line?

**Comment by aerwin** [comment]
@jhpedemonte @JonFerraiolo 

Per #1898, this one needs to get put into M6 as a high priority feature request. Previously, it has no priority or milestone specified.

**Comment by aerwin** [comment]
Also, once both types of reviews appear in the tree, @JonFerraiolo had some styling suggestions (per #1898):

> We probably should have different visual styling for reviews that the user created and reviews that other people created. We should have separate CSS classes for these two cases so we can fool around with visual styling of these two cases. My initial thought is that reviews that the user owns should be boldface and other reviews should use normal text styling.

**Comment by JonFerraiolo** [comment]
Javier and I have concluded that we need to fix this for M5. R/C won't be usable without this.

**Comment by waynevicknair** [comment]
reviewers get a 'comments.xml' that contains all their comments from all reviews in the '.reviews/snapshot' directory. the comment element does **not** contain a back-reference to the version (review) it is associated with. the association is made by a forward reference to the comment ID from the version object.

**Comment by JonFerraiolo** [comment]
-> @aerwin

**Comment by jhpedemonte** [comment]
Testing this now.

I created a review -- saw that it was bolded (as belonging to me) and I was able to add comments and so was Bill.

@billreed63  created a review and invited me.  Rather than opening the link in the email, I just **refreshed** my instance.  This causes Bill's review to appear alongside mine.  His review was displayed in italics, which is good.

However, when I opened his review, I saw a **login screen** within the editor tab.  This is #1979.  Closing/reopening review editor and refreshing Maqetta did not fix this issue.

Also, (still in state where I refreshed in order to get new review, rather than following link in email) when hovering over reviews, both of them showed me as the owner, but one was created by Bill.

---

Later, I did follow the link in the email.  Now, Bill's review loaded correctly.  I still see my review listed, but when I hover over each review, now both show Bill as the owner.

In this state (having followed email link), I can open my review just fine -- I **don't** see a login screen inside the tab.  However, when I tried to add a comment, I was redirected to the server error page:

## 

##    ![error](http://i.imgur.com/JHvLs.png)

**Comment by JonFerraiolo** [comment]
Logging as fixed by 4524033d55 . If we see detailed bugs around this, let's log new bugs.
