### ISSUE TITLE
Adding widgets into dojos.mobile.ListItem no longer working correctly

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#3605]
Found this as part of the `addChild()` rewrite:  adding widgets into **dojox.mobile.ListItem** no longer works correctly.

It seems that maybe in Dojo 1.7, ListItem made use of a non-standard `box` property.  For Dojo 1.8, the code is now using the Dijit-standard `containerNode`.

This means that some of the code in **ListItemHelper.js** is now incorrect.  Can probably just remove it and revert to using code in **DijitWidget**.

Note: also broken in M7.

@JonFerraiolo

**Comment by jhpedemonte** [comment]
Commit e39b9d4599e77f957e94d5146e9e1985fe5be489 takes care of most of the issues.  However, the first time you add a child into a ListItem, it appears below the label and is not visible.

The problem is that the label in the ListItem is represented as a DIV which is displayed as `block`, pushing any other DOM elements below it.

When this is run in Preview, the label DIV has a style of `display: inline`, which makes the other child widgets appear correctly.  Not sure how best to fix this one.

@peller

**Comment by jhpedemonte** [comment]
-> @JonFerraiolo

**Comment by JonFerraiolo** [comment]
I THINK THIS IS WRONG:

---

What's going on is that for some reason ListItem.js appears to check if there are any element children of the LI node for the ListItem. If so, then the text content is injected as a TextNode; if not, then the text content is wrapped inside of a DIV. I'm not entirely sure about this (still need more research), but it makes sense if you want the LI to auto-size its height based on the content.

If my theory is correct, then one possible fix is to create a variation of metadata property `refreshParentOnPropChange` which is the backwards variation. With current `refreshParentOnPropChange`, if you change a particular child (e.g., a TD) then we will sometimes force a recreation of an ancestor (e.g., the TABLE). But that works only when we know the inner element's widget type. The inverse of this would be to put a property on the ancestor (e.g., the TABLE) which says if any descendants change, then recreate the given ancestor. (Probably < 10 lines of code to make this happen.)

---

INSTEAD:

Looking at ListItem.js, the Dojo code always tries to have a DIV with class ListItemLabel. If there is only one child node of the LI, it sets display:block, else display:inline.

My theory is now that the crux of the problem is that our SmartInput for the *List widgets is stuffing the text value into the LI item instead of into the ListItemLabel child element.

@billreed63

**Comment by jhpedemonte** [comment]
But the code that chooses between _block_ and _inline_ is in the constructor for ListItem, right?  Therefore, I think your first proposition is correct: when adding the first child widget to ListItem, we need to refresh ListItem itself, so that it can properly set `display: inline`.
