### ISSUE TITLE
Infinite loop if editable=true when changing widget properties on RoundRectList

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3606]
(UPDATED TO SHOW THAT `editable` property needs to be on)

@peller @billreed63 

Assigning to @jhpedemonte for now because he is looking into helpers for ListItem-related widgets.

If I have set the `editable` property to true on a RoundRectList, I am seeing an infinite loop with these operations:
- New mobile app
- Add RoundRectList, accept defaults
- Go to widget-specific properties 
- Set `editable` to true
- Change value of 'transition' property

Result=> Program hangs at this spot in DijitWidget.js:91:

```
        do{
            widget = require("davinci/ve/widget").getEnclosingWidget(this.dijitWidget.domNode.parentNode);
        }while(widget && widget.dijitWidget && widget.dijitWidget.declaredClass.split(".").pop().charAt(0) == "_");
```

Two problems here:
- The declaredClass on RoundRectList's node._dvWidget.dijitWidget is `"dojox.mobile._EditableListMixin"` which has an underscore as the first character. (Why is the declaredClass `_EditableListMixin` instead of `RoundRectList`?)
- The infinite loop happens even after commenting out the underscore check part of the conditional because `getEnclosingWidget()` on a RoundRectList widget keeps returning itself.

**Comment by JonFerraiolo** [comment]
One option is to remove the editable property for M8, which I will do right now...

**Comment by jhpedemonte** [comment]
`declaredClass` is `_EditableListMixin` because when you set the **editable** property, the RoundRectList mixes in the _EditableListMixin object, replacing RoundRectList's `declaredClass` property.  Seems like it might be a small bug in the code.  @peller?

---

The reason this is an infinite loop is because it is always checking against `this.dijitWidget.domNode.parentNode` -- that never changes in the loop!  Should use `widget` instead of `this.dijitWidget`.

Also, I don't understand the check for underscore, especially against the `declaredClass`.  `getEnclosingWidget` should only return Maqetta-managed widgets and we don't offer any widgets that start with an underscore.  This change was initially made in June 2010; a lot has changed since then.

I think we can probably scrap all of `DijitWidget.getParent` and just default to `_Widget.getParent` -- the latter uses `this.domNode` and DijitWidget sets that to `dijitWidget.domNode` in the constructor, so it should just work.

**Comment by jhpedemonte** [comment]
Locally, I reverted your commit and commented out `DijitWidget.getParent`.  Went through scenario, and when changing the `transition` property, I get the error:

```
Uncaught Error: Tried to register widget with id==ul_1 but that id is already registered
```

Going through the code, it seems that when destroying the RoundRectList (as it is being regenerated after changing `transition` prop), it goes through `_EditableListMixin.destroy` where the call `this.inherited()` **does not** invoke `_WidgetBase.destroy`, which removes the Dijit widget's ID from the registry.

Since it's a mixin, not sure how `this.inherited` works.  `_EditableListMixin` is defined as a Dojo "class" (using `declare`), with no ancestor objects -- maybe that's why `this.inherited` failed.  Maybe _EditableListMixin should just be specified as a simple object?

@peller, any idea?

**Comment by jhpedemonte** [comment]
Oh, look, that issue has already been brought up by us:  http://bugs.dojotoolkit.org/ticket/16105

---

So to fix this issue correctly:
1. Revert Jon's temporary commit.
2. Delete `DijitWidget.getParent`.
3. Upgrade to Dojo 1.8.2 **or** backport the fix.

**Comment by jhpedemonte** [comment]
@JonFerraiolo, what's your take on [this](https://github.com/maqetta/maqetta/issues/3606#issuecomment-11275033) for M8?

**Comment by JonFerraiolo** [comment]
Risk/benefit ratio is such that I strongly recommend disabling the editable property for M8 and wait for M9 and Dojo 1.8.2.

**Comment by jhpedemonte** [comment]
Fixed the infinite loop, at least.  Remainder will have to wait for M9.
-> M9
