### ISSUE TITLE
dojox.mobile support

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#372]
@peller, @jhpedemonte

**Comment by jhpedemonte** [comment]
The docs at http://docs.dojocampus.org/dojox/mobile haven't been updated since March, so don't show Dojo 1.7 changes. @peller, is there a WIP 1.7 change overview file somewhere?

Going through the files, here are the widgets that aren't listed at the link, above, and are new to Dojo 1.7.  This doesn't take into account changes to existing widgets.
- Carousel
- Checkbox
- Combobox
- ContentPane
- EdgeToEdgeDataList
- ExpandingTextArea
- FixedSplitter
- FixedSplitterPane
- Opener
- Overlay
- PageIndicator
- RadioButton
- RoundRectDataList
- Slider
- SpinWheel
- SpinWheelDatePicker
- SpinWheelSlot
- SpinWheelTimePicker
- SwapView
- TextArea
- TextBox
- ToggleButton
- Tooltip
- TransitionEvent
- ViewController

**Comment by peller** [comment]
@jhpedemonte, try https://docs.google.com/document/pub?id=1lzdeIsZBMyU18t-Z4L8z6fqGkgJPnP9Aa29RZflYV9E

**Comment by jhpedemonte** [comment]
From link specified by peller:

## Differences from 1.6

**dojox.mobile.parser**
- Added support for jsId.
- Added dojo.parser = dojox.mobile.parser; so that other modules or user applications can directly call dojo.parser even when dojox.mobile.parser is used.
- Updated signature of parse() and instantiate() to align with dojo.parser’s ones.
- The 2nd argument of instantiate(), 'defaultParams', will no longer be mixed-in to widget parameters. It could break the widget, and the behavior is different from dojo.parser.
- Respect the noStart flag. If it is specified, startup() of the instantiated widget will not be called.
- Added support for the html5-style attributes, data-dojo-*.

**dojox.mobile.Button**
- Separated from _base.js and created dojox/mobile/Button.js. That means your application needs to add dojo.require(“dojox.mobile.Button”) if you use the button.
- btnClass has been changed to class. You need to specify a button class using the class attribute as follows.
  <button dojoType="dojox.mobile.Button" class="mblBlueButton">OK</button>
- The default button class no longer exists. You always need to explicitly specify a button class such as “mblBlueButton”.

**dojox.mobile.FlippableView**
- FlippableView has been renamed to “dojox.mobile.SwapView”.
- FlippableView still exists for backward compatibility, but will be removed before 1.7 is released.

## New Features in 1.7

**dojox.mobile.deviceTheme**

This module detects mobile devices from User-Agent string, and automatically loads an appropriate theme. The default is the iPhone theme.
You can also explicitly specify which device theme to load via query string in the URL. Below is examples.
- theme=Android
- theme=BlackBerry
- theme=iPad
- theme=iPhone (default)
  Ex. .../test_transition-animations.html?theme=Android

**dojox.mobile.SpinWheel**
**dojox.mobile.SpinWheelSlot**
**dojox.mobile.SpinWheelDatePicker**
**dojox.mobile.SpinWheelTimePicker**
**dojox.mobile.RoundRectDataList**
**dojox.mobile.EdgeToEdgeDataList**

**Comment by jhpedemonte** [comment]
Dojox Mobile widget gallery linked from here: http://dojotoolkit.org/features/mobile

**Comment by jhpedemonte** [comment]
Created several spin-off issues:
- #457 - Need icons for new dojox.mobile widgets
- #459 - How to handle dojox.mobile.View - only one visible at a time
- #460 - Allow user to switch between dojox.mobile themes
- #461 - Auto-add data store when dropping RoundRectDataList/EdgeToEdgeDataList?
- #462 - Support dojox.mobile.ProgressIndicator
- #463 - dojox.mobile.View should take up full screen
- #464 - Widget style selection wizard/dialog?

**Comment by jhpedemonte** [comment]
For reference, here are the (work-in-progress) release notes for Dojo 1.7: http://docs.dojocampus.org/releasenotes/1.7

**Comment by jhpedemonte** [comment]
Closing. Further issues handled in spin-off bugs.
