### ISSUE TITLE
Theme editor subwidget check boxes missing on FF 17

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#3733]
on FF when selecting a widget with subwidgets like calendar the subwidget list is displayed with checkboxes but then the checkboxes disapper and  I see the following in the console
"NetworkError: 404 Not Found - http://maqetta-app-test.austin.ibm.com/app/static/lib/dojo/1.8/dojo/resources/blank.gif"

**Comment by jhpedemonte** [comment]
How big is this for M9?  Push to M10?

@JonFerraiolo

**Comment by JonFerraiolo** [comment]
Normally a ship-stopper, but we've got to get the release out, so pushing this to M10. Maybe this is something we should fix in a dot release (if we have one)?

**Comment by peller** [comment]
Say no to dot releases.

**Comment by billreed63** [comment]
So for some reason now that we have gone to a relative path in the dojo-theme-editor.html files when we use the context dojo of the theme file to add subwidget context menu dojo has the wrong bath for _blankGif.

**Comment by billreed63** [comment]
Look for better solution for M10

**Comment by peller** [comment]
@wkeese, is the blank.gif still necessary in this widget or was it for old browser support?  It's a complication and an extra web hit I wish we could do without, but I'm sure it's there for a reason.

**Comment by wkeese** [comment]
@peller, are you talking about dijit/form/CheckBox?   I don't see it using a blank.gif or an IMG tag at all.

Speaking in general, a lot of widgets use an IMG tag rather than a SPAN because it works well as an inline-block element.   But with an IMG you need to specify src or you get warnings/errors from some browsers.   I don't remember which ones though.    SPAN with style="display: inline-block" surely works on newer browsers but probably had some complications on older ones

**Comment by peller** [comment]
@wkeese: @billreed63 informs me it's MenuItem's template, FWIW

**Comment by wkeese** [comment]
>  it's MenuItem's template

Not anymore, see http://bugs.dojotoolkit.org/changeset/30903/dojo
