### ISSUE TITLE
Review invitation email link should ultimately redirect user to review UI

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#377]
@EldonReturn, @waynevicknair, @jhpedemonte, @childsb

Right now we have a usability issue where reviewers who don't have an account
and/or aren't currently logged in are initially taken to review.html, but
immediately redirected to .../welcome to login. Upon logging in, they are taken
to the page editor instead of returned back to the reviewer UI.

We talked about this at today's call. Really nice to have for Preview 1, but
only if we have time and can add this feature safely.

**Comment by waynevicknair** [comment]
i ported the changes that brad and i made for preview1 to github. the solution is the addition of a command line parameter (loginUrl) which is set in the maqetta run script and read in the review and commenting servlet.

**Comment by waynevicknair** [comment]
revisiting

**Comment by waynevicknair** [comment]
i tested login (for existing reviewers) and register (for users that need to sign up). existing users get redirected to r&c after they successfully log in (instead of being redirected to the "Launch App" page). users who sign up go through the normal sign up procedure. after they click on the activation link in their activation email, they are shown their activation status and (if activation was successful) asked to login. when they login, they are redirected to r&c.

this preserves the original flow of both login and register up to the point where login is successful. so, the experience will not change for users who are just logging-in to launch the app or registering without having been invited to a review.
