### ISSUE TITLE
States are missing from event drop down in properties palette

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#3835]
Steps
(continuing on the same file created in the previous test)
Select the first button widget. On the Properties palette, go to the onclick property and use the dropdown menu to choose the option to switch to the "Background" state
Select the second button widget. On the Properties palette, go to the onclick property and use the dropdown menu to choose the option to switch to the "aaa" state
Select the third button widget. On the Properties palette, go to the onclick property and use the dropdown menu to choose the option to switch to the "ddd" state
Save and close the file.
In the Files palette, double-click on the file you just closed to re-open the file.
Click on the Preview in Browser button on the main toolbar. A new browser tab or window should appear with your new file showing within the frame.
Alternatively click on the 3 buttons.

**Comment by billreed63** [comment]
I don't think icon 6 is working either, I think we have issues with the whole states test case
maqetta.core.client/WebContent/test/testplan/StatesPalette/basic.html

**Comment by JonFerraiolo** [comment]
-> @peller - This commit caused the menu to not show any states: 

https://github.com/maqetta/maqetta/commit/2460303e1b970bdf52f8106cf907a0f81b0b166f#maqetta.core.client/WebContent/davinci/ve/widgets/EventSelection.js

When I use the EventSelection.js code from before that commit with the latest Maqetta, the states appear in the menu. 

I think the new code that tries to use Array.reduce is wrong (it seems to return the BODY element instead of a list of states), but there might be other things wrong with this commit. All changes need to be tested to make sure that they don't cause any regressions.

If you decide to simply revert to the old code to EventSelecdtion.js, don't forget to include the small change that @billreed made with his commit (31b55c395534be615ba160b4cdb400fe9db76744) which happened two days AFTER  the previously mentioned commit.

**Comment by billreed63** [comment]
working now
