### ISSUE TITLE
Eclipse projects has incorrect folder structure 

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3862]
@peller 

In Mac/FF, if I create an Eclipse project, then try to create a new desktop app, the new page editor hangs, and the console shows that there was a 500 return code on the call to getThemes.

Wouldn't be surprised if this is the same bug as #3839

**Comment by billreed63** [comment]
The root cause is the eclipse project has the wrong folder structure:
for M9 the folder structure is:
![image](https://f.cloud.github.com/assets/717822/329783/4b3d1ec6-9bbd-11e2-9588-4d742e571496.png)
For M10 the structure is:
![image](https://f.cloud.github.com/assets/717822/329790/78b21e38-9bbd-11e2-8a2f-064f9067a837.png)
Notice that the app.css, app.js. libs, themes and samples are outside of the WebContent folder.

**Comment by JonFerraiolo** [comment]
Was this fixed _AFTER_ the latest build was posted on maqetta-test? Because I still see the problem on maqetta-test

**Comment by jhpedemonte** [comment]
Yes, after.
