### ISSUE TITLE
Error opening up non-HTML review file

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#3914]
I created a review for **app.js**.  When opening up the file, I break in **davinci.dojo_1_8/WebContent/metadata/callbacks.js**, trying to reference `win["require"]`.  Since this isn't an HTML file, there is no `require` global.

**Comment by JonFerraiolo** [comment]
@peller 

I'm not sure when I'll find time to fix this problem. My first thought about how to fix would be to bracket all of the calls to `win[require]` with an `if` statement that makes sure that both `win` and `win.require` exist, but I would have to spend some time in the debugger to trace through what happens when a non-HTML file is used in a review.

**Comment by peller** [comment]
checking for `win` would be unnecessary, but a check for `win["require"]` would seem valid (we do that in Context.js, which is how we get this far).  However, that alone may not make any difference.  Commenting on non-HTML files still doesn't work.  References to `this.mainbody` in Comment.js are the next place it breaks.

**Comment by jhpedemonte** [comment]
Hmm, has it only ever worked on HTML files?  Can't remember what I've tested in the past.
