### ISSUE TITLE
surround with DIV, SPAN, A when children have position:absolute

### ISSUE THREAD

**Issue by waynevicknair** [maqetta/maqetta#396]
Suppose you have a Button with position:absolute;left:200;top:200; and then you
surround it with a DIV. You get:

&lt;div&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&lt;div dojoType="dijit.Form.Button" style="position:absolute;left:200;top:200;"&gt;
&lt;/div&gt;

which is typically correct, but if you go to the Outline palette and select the
Button and then the DIV, you'll see that the DIV's location is different than
the Button.

Proposal is that if any of the children have absolute position, then determine
the bounding box for all of children, make the DIV that size and position to
cover all of the children, and then change the left/top properties for all of
the children. Probably need to post a dialog telling the user about all of this
with OK and Cancel buttons.

bugzilla-5417

**Comment by JonFerraiolo** [comment]
Pushing to M6

**Comment by JonFerraiolo** [comment]
In addition to above, should disable surround with ... if there is a mix of absolute and flow layouts in selection. (Also, disable if anything in selection has a different parent, but I think we do that already)

**Comment by JonFerraiolo** [comment]
-> @doronrosenberg  - I would suggest pounding on the design/source pane selection bugs as way more important than this one, even if the selection issues are too big and risky for M6. This one is _much_ easier, but non-trivial. RIght now, the surround command creates a simple DIV that ends up at top of document (because no position property is assigned). What we need here is:
- (NOT SURE WHAT WE HAVE NOW) Surround commands should be enabled only if all selected widgets have same parent
- (NEW) If current selection is a mix of absolutely positioned widgets (ie computed style of position:absolute) and otherwise, then surround commands should be disabled
- For non-absolute selection, continue to do what we do now (simple add a DIV and reparent selected widgets)
- (NEW) When all selected widgets are absolute:
  - Get absolute page bounds of all selected widgets (recommendation: use davinci/ve/utils/GeomUtils.getMarginBoxPageCoords())
  - AddCommand for a new DIV
  - MoveCommand on the DIV to left/top bound of all selected widgets (note: MoveCommand uses page coordinates and widget margin box)
  - ResizeCommand on the DIV for the width/height of the bounding box
  - Then for each selected widget, need to do ReparentCommand. (I'm pretty sure this will fix up left/top properties on these widgets)

**Comment by JonFerraiolo** [comment]
See notes in #3288

**Comment by JonFerraiolo** [comment]
Progress on this issue is in branch 396SurroundAbsolute
