### ISSUE TITLE
my user account acn not use again?error starting Mqaetta: Can not read property '0' of undefined

### ISSUE THREAD

**Issue by ssiloveyouday** [maqetta/maqetta#3985]
I install a Maqetta in my localhost and sign in an account, and l have loggined in Mqetta two times, then afer a long time later, when I try to login, it shows:Error starting Maqetta: Can not read property '0' of undefined, why?

**Comment by JonFerraiolo** [comment]
Sorry, I don't have a good idea what might be going wrong. Sometimes Maqetta has problems at startup if one of the current open files from the last Maqetta session is damaged (often due to user doing hand-editing of source files, once in awhile due to a Maqetta bug). To address that particular situation, try launching Maqetta with http://localhost:50000/maqetta?resetWorkbenchState=1 (or hold down shift key when clicking "login" on the login screen). This will open Maqetta with no open files at startup. Another possible workaround is to create a new project (and abandon the previous project) by http://localhost:50000/maqetta?project=<new-project-name>. If neither of these work, then you may need to reinstall.
