### ISSUE TITLE
separate toolkit theme files from davinci-specific files

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#408]
Would like to restructure the user's copy of themes (davinci.dojo_1_x:/davinci/themes/... so that it doesn't have overlapping files specific to davinci (claro.theme, dojo-theme-editor.html, etc.)  That way, we can more easily clobber and upgrade the directory.

Talked to @billreed63 about this. It came up in the Dojo upgrade (#15)

@childsb: There's a version number in claro.theme.  Is this necessary, since the whole plugin assumes a particular version?

**Comment by JonFerraiolo** [comment]
Also, see #144: Move *.theme files up into themes/ folder

Regarding version# in claro.theme, is this a version# for the theme metadata "spec version"?

**Comment by peller** [comment]
@JonFerraiolo, there are both spec and dojo version numbers.  I guess I was referring to the latter.

``` javascript
({"className":"claro","name":"claro","version":"1.6","specVersion":"0.7","files":["claro.css"],"meta":["claro.json"],"themeEditorHtmls":["dojo-theme-editor.html"]})
```

**Comment by peller** [comment]
It doesn't seem right that the version number in Claro should be associated with the version number of Dojo.  The Sketch theme, for example, has an entirely different version number.

**Comment by JonFerraiolo** [comment]
@jhpedemonte

For Dijit-centric themes like claro and sketch, the theme CSS files really should be part of the Dojo distribution (e.g., dojo 1.7), and the *.theme and *.json files should be add-ons along the side that are tied to the theme CSS files within a particular Dojo distribution (e.g., dojo 1.7). I don't think we have any metadata in *.theme files that corresponds to the 'library' (<library>) feature we have in OAM. Maybe we need that. Need to coordinate with Javier if we go this route because might as well copy what we are doing on the OAM side, particularly the support for relocatable libraries. 

Whatever, assuming we figure out a mechanism for referencing the base folder for the theme CSS files, then the extra metadata that we would need that has to do with versioning would be: (a) "spec version", by which I mean a version number for the theme metadata format (in case that format gets tweaked in the coming years) and (b) (mentioned for completeness, probably an overkill feature) "content version", by which I mean a version number associated with the *.theme and *.json files in case there are multiple releases of these two files for a particular release of the corresponding library (e.g., Dojo). I would skip (b). Even if we really should have (b) for completeness and robustness, I doubt if people would remember to update that version number value.

**Comment by JonFerraiolo** [comment]
@billreed63 - could you please review this issue to see if it can be closed?

**Comment by billreed63** [comment]
#2673 current state
