### ISSUE TITLE
Review and Commenting Welcome content should be more relevant to Review and commenting

### ISSUE THREAD

**Issue by jmockler** [maqetta/maqetta#438]
This is a TODO for Review and Commenting UX as well as Development

Problem: when the user navigates to the URL in a Review Request Notification, they are taken to the Review and Commenting view, where they are shown an application layout which contains several views, one of which is an abbreviated Welcome. Which contains limited information.

Solution: add Relevant information around Review and Commenting to the Welcome, that is relevant to reviewers.

Some ideas could be: 
1. How to begin a review
2. Commenting and setting attributes for the comment
   (...)

@jmockler @JonFerraiolo @EldonReturn
 Review and Commenting Review - May 12, 2011

**Comment by JonFerraiolo** [comment]
With commit 98aecd677f3300fa4a71 I took care of the most critical UI shortcomings with the review and commenting welcome page, but there are a few things left to do:
- Both welcome pages (page designer and review mode) need some minor work regarding hyperlink behavior. Right now there is a big hyperlink over each section of page designer's welcome page. See item 3 on #544. For review's welcome page, there isn't a big hyperlink anywhere, but now what's broken is that we aren't switching between the icons when hovering and clicking on the Tutorial icon.
- For review mode, I think it would be better to include an additional entry on Help menu that takes the user to the Help documentation.
- Right now there is a single help page on review and commenting that covers both author things and reviewer things. This needs to be split into 2 separate help pages so that reviewers can go directly to the help information that they need, rather than having to scroll past a bunch of authoring information.

Because the most critical things have been addressed, reclassified remainder of bug to M3.

**Comment by JonFerraiolo** [comment]
Since the worst parts have been address, set to Priority-Low for M3. Ok to defer rest to M4 if we run out of time.

**Comment by JonFerraiolo** [comment]
Deferring remainder of this issue to M4.

**Comment by JonFerraiolo** [comment]
Reassigned to @waynevicknair and pushed to M5

**Comment by jhpedemonte** [comment]
Is this still relevant?  Since R&C now merged into core, there is no standalone R&C Welcome page.

Perhaps we should open a bug to add R&C content ("Recent Reviews") to Welcome page?

**Comment by JonFerraiolo** [comment]
Reassigning to me. I'll investigate and see if there is a safe and easy fix for M5 in this area.

**Comment by JonFerraiolo** [comment]
Pushing to M6. I don't see anything quick and easy that we can do for M5 for the "Welcome" content. I am hoping that we will have some UI redesigns for M6 that will address this particular UI issue.

**Comment by JonFerraiolo** [comment]
-> M7 Likely to become obsolete when we do our major UI makeover

**Comment by JonFerraiolo** [comment]
closing - after merging review/commenting into main app, there is no longer a separate welcome page for review/commenting.
