### ISSUE TITLE
Switching mobile silhouettes should auto-swap mobile themes

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#460]
dojox.mobile provides several different themes for different mobile product types.  We should provide a way to allow the user to switch between these different themes.

Currently, the dojox.mobile metadata files all include the iPhone theme, so this would need to be changed.

There is a `dojox.mobile.deviceTheme` module:

> This module detects mobile devices from User-Agent string, and automatically loads an appropriate theme. The default is the iPhone theme.
> You can also explicitly specify which device theme to load via query string in the URL. Below is examples.
> - theme=Android
> - theme=BlackBerry
> - theme=iPad
> - theme=iPhone (default)
>   Ex. .../test_transition-animations.html?theme=Android

How would this work for us?  If a user wants to switch to a different theme, would we need to reload the VE iframe with a new URL parameter?

@JonFerraiolo @peller @billreed63

**Comment by JonFerraiolo** [comment]
It looks like the themes are tied to devices, so we should switch themes when we switch silhouettes, right? Also, (preview in browser) mobile previewer should switch themes as you switch devices there.

Bill, how do we switch themes in the page editor? Just replace LINK element href and change class name on BODY? We should see if the same techniques will work with mobile themes.

(Subsequent addition to earlier comment) We should also persist the mobile device name into the saved HTML file so that when the user reloads, the previously used silhouette and theme appear.

(Another addition to earlier comment) Poking around the code, looks to me like ~90% of the work to reload a page from scratch can be accomplished in the scope of workbench/EditorContainer via these two calls:

this.editor.setContent(filename, content);
this.setDirty(editor.isDirty);

On paper, this looks like the first statement above will cause a reload of the both user's iframe and the corresponding model, biggest concern is cleaning up the old stuff before creating the new stuff

**Comment by billreed63** [comment]
The is what we do, the code is in davinci.ve.commands.ChangeThemeCommand.js

**Comment by JonFerraiolo** [comment]
@jhpedemonte: could you please change title of bug to "Switching mobile silhouettes should auto-swap mobile themes"

Reassigned to Bill to figure out how to force a reload when switching silhouettes

**Comment by jhpedemonte** [comment]
Also commit d0d6d1c18254015e03fa.

**Comment by billreed63** [comment]
put setDevice in setTimeout in ve.context.js so chrome will display mobile device correctly on editor load

July 2011
