### ISSUE TITLE
document.head is undefined in silhouetteiframe.js

### ISSUE THREAD

**Issue by childsb** [maqetta/maqetta#471]
when opening sample1.html on firefox 3.6 i get a "document.hea is undefined" around line 129 of silhouetteiframe.js

this is in firefox 3.6, and the page edit freezes.

**Comment by JonFerraiolo** [comment]
You got to this point after you saw the "You are using an unsupported browser dialog", right? :-)

FF3.6 apparently doesn't support document.head, so I replaced 'document.head' with a call to querySelectorAll, which does work in FF3.6. Also, I found various bugs with SVG animation tags in FF3.6, so I put IF statements around things to prevent FF3.6 from dying on those tags.

Closing issue because the reported problem has been fixed, but Maqetta doesn't work for me with FF3.6 in what appears to be an unrelated problem - dies loading plugins.
