### ISSUE TITLE
Clicking "Create" in new file dialog throws error

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#483]
Clicking on the **Create** button in the **New HTML File** dialog throws an error in `davinci.model.Resource._checkFileName()`.  The call to `dijit.byId('fileDialogFolderTree').getSelectedItems()` returns an array of length zero, which the code does not expect.

Not sure what caused this to fail, since it was working fine with code I pulled late last night.

@peller @JonFerraiolo

**Comment by JonFerraiolo** [comment]
I went through commits one by one to see where this broke. It works with the commit:
[2e42cb1cefbc3c802f84]
but fails after the following commit (_selectNode no longer exists in dijit.Tree for Dojo 1.6+. Fire this ):
[fecec78a4e15a892a2f8]

Here is a partial explanation of what's going wrong. With Preview 1, there was always a selected TreeItem. With the new code, by default nothing is selected. The _checkFileName() routine assumes there is at least one thing selected. With the new code, if you click on "." in the Tree widget that shows the workspace, and then hit Create, things work fine.

Of course, we could patch Resource.js to check if any resources are selected, but I'd rather understand why the old code managed to select "." before posting the Create New File dialog whereas the new code isn't selecting ".".

Digging deeper, my guess is that some code in davinci/ui/widgets/Tree.js that has been commented out and the lack of this code is the reason that "." is not selected when the Create New File dialog appears. Look at _selectNode(). The following lines have been commented out:

```
    if(node){
        node.setSelected(true);
        this.selectedNodes.push(node); 
    }
```

By commenting out this code, _selectNode() pretty much has become a no-op, which can't be right. (Otherwise, it would be called "_dontSelectNode")

**Comment by peller** [comment]
well, in Dijit, the entire _selectNode method disappeared, so I think it's all duplication at this point.  I was trying to connect the code which assumed its existence.  It's not clear why we're using this widget for the file view at all.

**Comment by peller** [comment]
it's coming back to me now... I think the reason a custom Tree widget is used here is to avoid showing the top-level root node

**Comment by jhpedemonte** [comment]
According to http://dojotoolkit.org/reference-guide/dijit/Tree.html, it should be as simple as setting `showRoot = false` to hide the root node. No custom widget required.

**Comment by JonFerraiolo** [comment]
But we need to show the root (i.e., "."). It's the default choice and somehow the user needs to say that the new file should be placed into the root folder of the workspace. Therefore, I'm pretty sure we need showRoot=true

**Comment by jhpedemonte** [comment]
@JonFerraiolo, I think @peller was referring to the tree in the Files view, which doesn't show a root.  As he mentioned in the call, the `davinci.ui.widgets.Tree` object may be used unnecessarily in other parts of the code, where `dijit.Tree` will do just fine.

**Comment by JonFerraiolo** [comment]
Ultimately, when we support multiple "file clients" from Orion, I think we'll need the root to show in Files palette (or even better replace Files palette with Orion navigator widget). But this bug is about "Create HTML File" palette, and on that palette, we do show the root (".") and have to show the root.

**Comment by peller** [comment]
I think this bug is trying to get a selection from the explorer first.

**Comment by JonFerraiolo** [comment]
This bug is about the Create New File dialog, which posts a tree widget that shows the user's workspace, with "." as the root node of that tree. When initializing the dialog that contains this tree widget, _selectNode() is called to select "." (or whatever folder was the last folder selected in the Files palette). The bug is that _selectNode() isn't actually selecting "." (or whatever folder it should be selecting) because the old logic in _selectNode() that did the selection magic has been commented out. Right?
