### ISSUE TITLE
Build number shows string "Preview1"

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#485]
The automatic build number that is stuffed into repositoryInfo.js starts with the string "Preview1". Can we change this because we are moving past Preview 1 to Preview 2?

Ideally, it would be good to replace "Preview1" with date/time so that the build# information consisted of date, time, commit#, but an easier fix would be to simply remove "Preview1" and simply leave last commit# information. The date/time would be very nice to have because just having the commit# means we would have to go to github.com to translate a commit# into a date/time.

**Comment by peller** [comment]
Wayne, is there an easy way to transform the git-describe string to date/time info?  If it's available as a url query, perhaps we could just provide the github url instead of date/time info?   In this case, I think git-describe/commit is more useful and precise than date/time.  We just need a way to get both easily, right?

**Comment by waynevicknair** [comment]
fixed in  db271b47a6668eeb451b
