### ISSUE TITLE
Datagrid doesn't refresh properly upon initial creation

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#488]
@peller, @jhpedemonte

With latest code, I'm seeing the new UI for DataGrid, and it looks pretty good to me. However, perhaps due to Dojo 1.7 update, the DataGrid doesn't redraw properly for me on Mac/Chrome. If I accept the default data, the bottom of the last row of data is clipped. I have to jiggle the size of the DataGrid to get all of the data to be visible.

**Comment by billreed63** [comment]
I have not been able to reproduce this on FF5 or Chrome with the code from
 commit 5e6cc2598bf0bcc70398d4aef8ef0f0c8282022f
Author: Bill Reed billreed@us.ibm.com 2011-06-15 16:15:15

**Comment by billreed63** [comment]
Just saw it again..
Steps to recreate:
1) New Browser window
2) Create new HTML file
3) Drag Drop DataGrid. 
4) Cancel SmartInput

**Comment by billreed63** [comment]
The root of the problem seems to be timing, When a new html file is created the theme CSS files are loaded, but dojo.css, Grid.css and claroGrid.css are not. When the first dojo widget is dropped on the page dojo.css gets loaded. When DataGrid gets dropped on the page Grid and ClaroGrid.css get loaded. If the first widget the user drops on the page is a DataGrid all 3 css files are added to the source and loading, this seems to cause the timing issue.
Once the first load happends the files are cached and all is well.
If I create a new file and manually the imports to the source:

```
@import "./lib/dojo/dojo/resources/dojo.css";
@import "./lib/dojo/dojox/grid/resources/Grid.css";
@import "./lib/dojo/dojox/grid/resources/claroGrid.css";
```

Then drop the grid all works, because the CSS files are loaded and cached.

**Comment by billreed63** [comment]
Now that I am running dojo 1.7 in the users workspace the timing issue seems to have resolved itself.
