### ISSUE TITLE
Preview in browser broken

### ISSUE THREAD

**Issue by cindyskach** [maqetta/maqetta#507]
If I drag a button onto the page and try to preview it, it doesn't show up properly. The sample html files work, but new files do not.

**Comment by JonFerraiolo** [comment]
I just pulled the latest code from GitHub, cleared my browser cache, restarted my server (from Eclipse), restarted a Maqetta browser session, dragged a Button (from Controls section of widget palette) onto canvas, and hit Preview-in-Browser button, and everything worked. I tried this in Mac/Chrome.

Maybe one of the check-ins today fixed this problem. Could you please try to reproduce with latest code? If still present, does debugger show any error messages in the console?

**Comment by cindyskach** [comment]
Yeah, I just pulled the latest code, and it's working. I was testing against the latest build from lab14 yesterday.

**Comment by cindyskach** [comment]
With the latest build from lab14, preview in window has an uncaught exception. dojo._hasResource is undefined. There's a comment beside the call that says not to use _hasResource directly in the code.

@peller

**Comment by peller** [comment]
that's generated by the build, so it probably should be there

**Comment by jhpedemonte** [comment]
Yes, it should be there, however, `dojo._hasResource` shouldn't be undefined.  When I looked at this with Cindy, I saw that `dojo` was defined, but had no `_hasResource` function.

I'm wondering if this is an issue with the app running Dojo 1.6 but the user's workspace running Dojo 1.7.  I just grepped the Dojo 1.7 source and only found a reference to `_hasResource` in **util/buildscripts/jslib/buildUtil.js** -- but I think that may be vestigial (yeah, I said it!).

I think this problem is caused by building States.js with Dojo 1.6 (which adds in the `_hasResource` wrapper) but using it in a Dojo 1.7 context (which uses AMD instead of `_hasResource`).

**Comment by JonFerraiolo** [comment]
As a short-term fix, could we copy workspace.maqetta.States.js somewhere into the davinci/ tree, and therefore the page editor references a different version of States.js than the built version, and then remove workspace/\* from the list of files that get built? Probably also have to do this for maqetta.js (very small file). And then log a cleanup bug for M3 to fix things up more nicely.

It means that we would temporarily have two copies of the same things floating around, one for the page editor (which would use dojo 1.6 build stuff) and a separate copy for runtime (running inside of Dojo 1.7 without being built)

**Comment by jhpedemonte** [comment]
I'm fine with this -- low risk.  Just add comments to the top of each so we remember what's going on.

**Comment by peller** [comment]
see also c0d42a94569520b75b23baa61ed0c215c64b00e5
