### ISSUE TITLE
Preview with mobile silhouettes broken

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#513]
When opening up the preview-in-browser window while using mobile silhouettes, I get this URL (**http://localhost:8081/maqetta/?preview=1&device=iphone&file=http://localhost:8081/maqetta/user/javier/ws/workspace/file2.html**) and the preview tab just opens up another instance of the Maqetta app, instead of a proper preview.

**Comment by JonFerraiolo** [comment]
@childsb

That's the correct URL. The server is supposed to see the preview=1 URL parameter and send down preview.html content (leaving URL intact) instead of sending down content for pagedesigner.html. If there is a bug, it's probably with the server. If you are running old server software, pagedesigner.html would come down, but for at least a week the server has been responding to the preview=1 url parameter correctly and sending down preview.html insteadl

**Comment by jhpedemonte** [comment]
OK, so it works correctly with the June 16 nightly build, but not when running from Eclipse.

**Comment by jhpedemonte** [comment]
And now I have it working properly from Eclipse.  Not sure why my previous purge didn't work, but all is swell now.
