### ISSUE TITLE
Fix sample image for dojox.mobile.IconContainer

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#516]
Currently, the sample image used by `dojox.mobile.IconContainer` is pulled from metadata.  The problem is that this isn't portable -- as soon as the files that make use of this widget are moved to another location, the image will no longer be found.

Instead, it needs to come from the user's workspace.  Will need to add image as sample data and use that as the default when dropping `IconContainer` (or `IconItem`).

Also, should get rid of `__MAQ_LIB_BASE_URL__`, which was a bad idea.

**Comment by jhpedemonte** [comment]
@JonFerraiolo @billreed63 - I added the image to `sample_data/images` folder in user's workspace.  Seem fine?

**Comment by JonFerraiolo** [comment]
Does this mean that the code from the davinci.dojo_1_5 project is depending on a particular sample file in order to work properly? If so, then we should probably do something else. We should avoid cross-project dependencies and samples shouldn't contain real data needed for real product operation, such as default values in our metadata files.

What we probably need to do is add a new mechanism where widgets.json identifies particular files to be installed somewhere in the libs/dojo folder, which is necessary because if dojo gets relocated by Brad's various relocation features, then the image file would move with Dojo and therefore relative URLs would continue to work. However, this is obviously a fairly large mechanism just to get one image file (all we have at this point) to work properly.

For a short-term fix, maybe we can hard-code a file in davinci.dojo_1_7/WebContent/dojo/images/whatever? Base64 might also help as a short-term fix, but that would result in some pretty ugly content in the Properties palette.

**Comment by jhpedemonte** [comment]
You're right; hadn't thought of the dependency implications.

Looked through the Dojo files -- there isn't an image we can really use for this.  So we'd have to add one, as you mentioned.
