### ISSUE TITLE
dojox.mobile.Slider doesn't display correctly (fixed in Dojo 1.7 final)

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#521]
The widget `dojox.mobile.Slider` does not display correctly when dropped in the VE.  The `<input>` element that is used by the slider should have `type="hidden"` set.

**Comment by jhpedemonte** [comment]
OK, after much testing, it seems that **Slider** requires the `name` attribute.  Otherwise, it will not render correctly.  This seems like a bug in the Dojo code.

@peller, I opened this bug on Dojo: http://bugs.dojotoolkit.org/ticket/13270

Unfortunately, I'm not sure about a good workaround for this.  I could change it so that the `content` in the metadata has a `name` attribute for the `input` element.  But is there a problem if multiple sliders are on the page, all with the same `name`?

@JonFerraiolo

**Comment by peller** [comment]
If it's a form element, name is pretty important -- worth generating in Maqetta, I think -- though perhaps not mandatory.  Names only need to be unique per form.  It probably wouldn't be fatal to have duplicate names within a form, but it should be avoided.  Could we just generate a unique name with a counter?

**Comment by JonFerraiolo** [comment]
IMO, Dojo and Maqetta shouldn't touch the name attribute. The name attribute is mostly about form submission. The user needs to be in charge of the name attribute so that when forms are submitted to the server, the URL parameters match what the server expects. Maybe we need to do something in the short-term while waiting for a Dojo fix, but in general I'm pretty sure we shouldn't touch the 'name' property.

But one thing we could do is add 'name' to the Properties palette. I created a bug for this just now: #593

**Comment by jhpedemonte** [comment]
The Dojo bug has already been fixed and will be in 1.7 final.  Keeping this issue open to verify, once we move up to new Dojo.

**Comment by jhpedemonte** [comment]
Fixed in Dojo 1.7b2.
