### ISSUE TITLE
Performance hit when switching states on Chrome/Mac

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#53]
I was following the tutorial on creating states (third page; "Build a Task
Manager (Application States)") and noticed that there was a very noticeable lag
when switching between states on Chrome/Mac.  During this time, the CPU was
more or less maxed.

------- Comment #1 From Jon Ferraiolo 2010-10-27 22:37 [reply] -------

Seems to be slower when switching to Normal state from a different state

------- Comment #2 From xxxxxx 2010-11-12 09:01 [reply] -------

When switching states within the designer the lag on switching to normal state
is greatly exaggerated because each widget is destroyed and recreated when
their style attributes are modified. We don't do this currently when switching
to other states because it would directly update the style attributes on the
model, which we don't want (the style attribute should only contain styles from
the normal state). Clearly there's room for improvement here. Another major
factor is that we loop over all the children of the body when changing the
state. If we filter out children that have not yet had state specific changes,
that should significantly improve performance.

------- Comment #5 From Adam Peller 2011-02-21 21:44 [reply] -------

I think the profile is telling me that a lot of the time is spent parsing HTML
going in the outline view.  Short of previous suggested change, it might be
interesting to see what happens if we can disable incremental updates to the
outline view while the state change is taking place.

**Comment by peller** [comment]
It wasn't just that rendering the tree is slow (it is... lots of innerHTML calls and such)  The problem was that onContentChange was bound to refresh in VisualEditorOutline, apparently as some sort of brute-force workaround.  The only supported way to change the content of the tree is by changing the model.  It looks like we're going in and manually replacing tree nodes.  The states code was recursing through the tree changing styles, and the way it was wired, each style change triggered a refresh() call to refresh the entire tree.

**Comment by peller** [comment]
FWIW, I found the performance seemed much worse on FF than Chrome

**Comment by billreed63** [comment]
Looks good. Review complete
