### ISSUE TITLE
Can't change button background color for states other than normal

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#531]
The test plan davinci.core/WebContent/test/testplan/StatesPalette/basic.html describes:

Changing properties in different states
### Steps

1 (continuing on the same file created in the previous test)
In the States palette, select the "ddd" state. Go to Outline palette and click on the closed eyeball icon for the Calendar to make it visible (the eyeball should open and the Calendar should become visible on the canvas), then click on the open eyeball icon for the TextBox to make it invisible (the eyeball should close and the TextBox should become invisible on the canvas).
(Note: For some of these cases below, the Properties palette will default to targeting the CSS style rule within a CSS style sheet. Instead, bring up CSS cascade and set the target to element.style. This might be something we fix in the future. We should know that you can set fonts on the root node for button and can set width on the root for calendar.)
On the States palette, go into the Normal state. Select the first button widget. On the Styling palette, set font color to a reddish color and font size to
1. Select the calendar widget. On the Object palette, set the width to 200px.
   On the States palette, go into the "aaa" state. Select the second button widget. On the Styling palette, set font color to a greenish color and font size to
2. Select the calendar widget. On the Object palette, set the width to 300px.
   On the States palette, go into the "ddd" state. Select the third button widget. On the Styling palette, set font color to a bluish color and font size to
3. Select the calendar widget. On the Object palette, set the width to 400px.
   Save and close the file.
   In the Files palette, double-click on the file you just closed to re-open the file.
   Click on the Preview in Browser button on the main toolbar. A new browser tab or window should appear with your new file showing within the frame.
   Alternatively click on the 3 buttons.
### Expected results

You should see slightly different results than in the previous section. The Label should disappear when you click on the second button and the TextBox should disappear when you click on the third button.
In all 3 states, the first button should have a reddish color and a font size of 20
In the normal state, the Calendar whould be 200px wide.
In the "aaa" state, the second button should have a greenish color and a font size of 30 and the Calendar whould be 300px wide.
In the "ddd" state, the third button should have a bluish color and a font size of 40 and the Calendar whould be 400px wide.

I can't change the styles when a state is selected.

**Comment by JonFerraiolo** [comment]
In this case, software works, but test plan is broken. I'll fix the test plan. 

By default starting I think with Preview 1, style rules always apply to Normal. In earlier releases, users were getting totally confused because if they were editing and a state other than Normal was in effect, changing size and position of elements were only applying to that state, and users couldn't keep track of things. 98% of the time they wanted their styling changes to apply across all states. Only occasionally does a user want to change a CSS property only for a particular state. So the way things work no, to set CSS style only for a particular state, a user has to open the css cascade view for a particular property (> sign to right of property in properties palette) and then scroll to very bottom and click the "Only apply to current state (<statename>)" checkbox.
