### ISSUE TITLE
Disable/remove "Add link" command?

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#539]
Don't remember:  what is the purpose of the **Add Link** command?  First of all, it doesn't currently work, but before filing that bug, I wanted to figure out what it does exactly and why we should have it in Maqetta.

@childsb

**Comment by JonFerraiolo** [comment]
Reassigned to Adam because he is messing with context menu on Files palette.

Adam, Could you please remove "Add link" command? ui_plugin.js has front-end logic and we can probably remove davinci/actions/AddLinkAction.js.

I can explain the history behind "Add link", but short version is that Orion file clients is a much better answer for the functionality that "Add link" was supposed to provide.

**Comment by peller** [comment]
thank goodness. I was about to ask you guys what it was supposed to do!
