### ISSUE TITLE
Deleting background image text results in "url('.')"

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#560]
First, there's not a way to delete a brackground image consistent with the other properties.  The only way I can do it is to select the text of the background image property and delete it.

Upon hitting enter, though (in order to set [or unset] property), the text "url('.')" appears.

**Comment by JonFerraiolo** [comment]
Brad, can you look at this one? Not absolutely critical for M2, but would fix a significant issue with the background-image property. Basically, we need a combobox instead of a textbox on background-image so that we include a drop-down menu. I looked at this and the drop-down menu logic is in MultiInputDropDown.js, but we can't just change background-image to a 'multi' because we still need the button to open the file palette. Maybe what we need to do is copy some code out of MultiInputDropDown.js into Background.js.

**Comment by JonFerraiolo** [comment]
Ran out of time, pushing to M4.

**Comment by billreed63** [comment]
mobile relies heavily on   on gradients

background-image : -webkit-gradient(linear, left top, left bottom, from(#ad7500), to(#ffaa00), color-stop(0.06, #ffb200), color-stop(0.5, #ffc700));

**Comment by childsb** [comment]
Fixed
