### ISSUE TITLE
background color change to DataGrid doesn't change background

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#568]
instead, it only seemed to affect part of the border.  is this a bug in our metadata, or is it a problem with the way dojox.grid is structured?
@billreed63

**Comment by JonFerraiolo** [comment]
-> M7 Prio-Med. Of course, we are now focused on gridx instead of DataGrid.

**Comment by billreed63** [comment]
Closing we are not supporting data grid, Gridx is the future

**Comment by aerwin** [comment]
--> @aerwin

Reopening... should probably see if this is an issue with GridX.

**Comment by aerwin** [comment]
Closing after looking at the behavior on GridX... It appears changing background color on GridX adds "background: red" to the style props for the &lt;table&gt; . And, when this is rendered changes the background of the non-data row part of the table body. I think this is all we can expect.

Eventually, GridX will be in the theme editor making it possible to style other parts of the GridX graphically. Otherwise (and in the meantime), I think the user will need to manually override GridX CSS props in app.css.
