### ISSUE TITLE
Multiple includes for dojo.js

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#602]
For some reason, I am seeing multiple includes for **dojo.js** in the source, after creating a page with several Dojo widgets.

@childsb

**Comment by JonFerraiolo** [comment]
(I thought there was an existing bug for this, but I haven't found it yet. Maybe it's inside of one of the SaveAs bugs?)

Assigned to Brad for time being because he is probably looking at related things as part of SaveAs fixes, but maybe someone else will end up picking this up.

We also have a multiple includes problem for dojo.css. See #71 and #9

**Comment by childsb** [comment]
Fixed with checkin 409bbf709a33ad8d5050de7b908af5750aa5b88e
