### ISSUE TITLE
Theme editor calendar widget - selected date doesn't show

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#644]
@peller, @jhpedemonte

In theme editor, click on Calendar. No date is highlighted as the selected date. If you click on the "Selected date" subwidget, no red highlight appears.

**Comment by billreed63** [comment]
This maybe related to 1.7 bugs with calendar, Adam changed Calendar to calendar lite, so I may need to talk to Adam

**Comment by peller** [comment]
for the record, the implementation of Calendar split and I made a bug fix to the CalendarLite base class.  We did not switch widgets.  But other implementation changes, such as the default "NaN" date seem to be causing problems in our code.  See #458.  The date is showing as the default invalid date, which then triggers bugs in our code that serialize it incorrectly.

**Comment by peller** [comment]
best to set a default selection anyway, don't you think?  NaN bugs in #458 still must be addressed.

**Comment by JonFerraiolo** [comment]
It's a regression versus Preview 1 if we don't have a default selected date for Calendar. In Preview 1, it defaulted successfully to today's date. I realize this is a minor regression, but a regression nonetheless. Should we reopen this bug or create a new bug for making the default date work properly?

**Comment by peller** [comment]
With 6e9e5bb9f86c74b760bc77fd286e4b318f05e432 we now have a default selected date in the themeEditor.  If you think there should be one selected in the designer, I think a separate bug would be appropriate.  I don't know where the code was to set the date.  Dijit does not define one by default, so that seems like a reasonable behavior.  The user is prompted by the smartinput, so there is an opportunity to set it.
