### ISSUE TITLE
Unable to upload file into correct folder from file exploer

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#648]
Create a new folder (see instructions above), perhaps named "ggg". With the mouse inside of the Files palette's main area, click on thie folder (e.g., ggg) and then click the right mouse button (or Ctrl-click on Mac) to bring up context menu and choose "Upload Files". In the dialog(s) that appear, choose a file from your disk and upload to your workspace. The new file should have been added into the ggg folder in the Files palette.

File is uploaded into user root

**Comment by JonFerraiolo** [comment]
Two things missing from current code that were present in Preview1:
(1) What Bill says above - with Preview1, if you invoke "upload" with mouse over a folder, then the file will get uploaded into that folder instead of root folder
(2) The new upload dialog is missing a field that was in the Preview 1 upload dialog: a read-only line of text that showed the Parent folder into which the file(s) would be uploaded.
This is a relatively important feature that has worked in the past. Users often want to put images into an img/ subfolder.

**Comment by peller** [comment]
dup of #628
