### ISSUE TITLE
copy and paste doesn't work in source editor

### ISSUE THREAD

**Issue by childsb** [maqetta/maqetta#655]
1) open sample1.html
2) select all the text
3) do copy keyboard command (no context menu)
4) observe error in JS/console

5) copy some text out of a file in the file sytstem
6) use paste command in editor
7) notice error in console or hault in script debugger on error.
@jhpedemonte

**Comment by peller** [comment]
please note the error in your report

**Comment by peller** [comment]
FWIW, I don't think this worked in preview 1.  It may have worked originally, but been broken when we migrated to the Orion editor, or perhaps I broke it when I did an upgrade (also prior to preview 1)  ...though I still see no error on the console.

**Comment by peller** [comment]
The clipboard actions in davinci/ve/actions/ContextActions have code like this:

``` js
        context = davinci.ve.actions.fixupContext(context);
        if(context){
            if (context.declaredClass=="davinci.ve.PageEditor" && context._displayMode=="source")
            {
                context.htmlEditor.copyAction.run();
                return;
            }
```

Both conditions in the inner `if` fail.  I suspect this has been broken a while, perhaps since the split viewer was built.  The following needs to be fixed, at a minimum:

The fixupContext method returns something which is no longer davinci.ve.PageEditor, so the first part fails.  The second part should probably compare against `!= "design"` since values like "splitVertical" are possible.  Then, we must deal with the focus, whether the copy operation is intended for the design side or the source side.

The code to handle the clipboard action and pass through to the Orion editor exists in the davinci.ui.Editor code.

**Comment by JonFerraiolo** [comment]
@peller - could you please review this and close if this issue no longer exists?
