### ISSUE TITLE
Dropping dijit.Tree results in errors

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#664]
@billreed63

This is probably due to the same problems affecting the mobile data-bound widgets. Certainly related to #244 and mabye related to #662.

(Note: I didn't see a bug regarding mobile data-bound widgets not working with the new allowedParent/allowedChild metadata feature.)

**Comment by jhpedemonte** [comment]
I'm not seeing this.  Instead, I get other errors when dropping `dijit.Tree` on page:

```
TypeError: Cannot set property '_dvWidget' of undefined             widget.js:1490
Uncaught TypeError: Cannot call method 'getUniqueID' of undefined   widget.js:414
```

And these errors occur even if I comment out the call to `_getAllowedTargetWidget()` in **CreateTool.js**.

From the preliminary investigation, code is trying to instantiate `davinci.ve._Widget` for **ForestStoreModel**, in this line in **widget.js**:

`var dijitWidget = markupFactory ? markupFactory(params, node, c) : new c(params, node);`

Instead of coming back as an object, `dijitWidget` is set to `"dijit.tree.ForestStoreModel"`.  Code dies couple of lines later trying to read `dijitWidget.domNode._dvWidget`.

**Comment by jhpedemonte** [comment]
Re-assigning to @billreed63, since he knows this code better.

**Comment by billreed63** [comment]
Closed July 2011
