### ISSUE TITLE
Smart input for Calendar in page designer

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#668]
@peller, @jhpedemonte

Only reason why this is currently an M2 bug is that this feature worked in Preview 1.

When you add a Calendar with the current code, smart input comes up and says "Invalid date". In Preview 1, at Calendar creation time, smart input showed an RFC822 date string such as "Wed Jul 06 2011 00:00:00 GMT-0700 (PDT)" (which Adam and I believe is the wrong thing to do - should use ECMA5-compliant formats, such as 2011-07-06).

Also, I don't think Calendar should post a smart input prompt at Calendar creation time. In fact, I don't think we need smart input at all for Calendar - the widget-specific property is enough.

Adam points out that Calendar doesn't have a default date normally.

One more bit of background info: the widget-specific 'Value' property in Properties palette works fine with ECMA5 data values (e.g., 2011-07-08).

So here is what I propose:
- Let's get rid of smart input on Calendar
- Selected date doesn't show by default. Only shows if user enters a value for the "Value" property.
- We create a separate bug for M3 or later to do something better than print "Invalid date" in the "value" field if no date is provided, and to show ECMA-compatible values rather than RFC822 values for the "Value" property in the Properties palette.

**Comment by peller** [comment]
"ISO" datea (i.e. yyyy-MM-dd) are accepted by the properties panel, but they are not reflected in the source view and does not persist.

**Comment by billreed63** [comment]
We can easily remove the inline edit. 

Not having a selected date set is what is causing the "Invalid Date" when we retrieve the calendar widgets value attributed a Date object is returned from dijit but no value is set. So attempting to get the data string from the data object return invalid date. 

If we leave the widget with the selected date (value) unset, when the user goes to the properties palette to set the widget specific value property they will see "Invalid Date" until they set a value.

**Comment by peller** [comment]
Perhaps the smart inline edit could just check for the unselected state (isNaN(dateObject) is truthy) and display an empty string?  Setting an empty string back to a Date constructor would complete the cycle.

**Comment by JonFerraiolo** [comment]
Adam's suggestion is definitely worth a quick try.

**Comment by billreed63** [comment]
Sorry did not explain this well, Smart Input is easy to fix,

If we do not set a selected date, when the widget properties palette is display the  widget specific-> value will be "Invalid Date" The reason for this value is that the Calendar widget is define with the  
 "value": {
            "datatype": "string",
            "format": "date",
            "title": "Value"
        },

So the widget proprieties palette retrieves  the value attribute from the widget. In this case the widget returns a Date object, but because no selected date was set when the widget palette gets the string value from the Date object returned from the Calendar widget we get a string that say "Invalid Date"  

Seems to me this is a bug in Calendar, if a selected date is not set the "value" attribute should be null

**Comment by billreed63** [comment]
July 2011

**Comment by peller** [comment]
See #458 also http://bugs.dojotoolkit.org/ticket/13362 regarding the null vs. Date("")/NaN issue
