### ISSUE TITLE
Paste cursor disabled if page canvas is scrolled

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#675]
(not urgent)
- New HTML file
- Add Button and 4 Calendars (to provide height to the content)
- Make canvas smaller such that there is a vertical scrollbar on canvas
- Select Button, copy
- Scroll canvas so Button is invisible due to scrolling off top of canvas
- Click on Paste icon on editor toolbar
- Try to click on canvas. You'll notice that the paste cursor either doesn't appear at all or only is visible at the top part of the canvas

There is likely a problem where we aren't adding scroll amount into a calculation

**Comment by jhpedemonte** [comment]
This isn't just an issue when pasting.  I saw it when trying to add a widget to the page.  The crosshairs did not appear in the area below the original viewport.  However, they did appear when I moved the mouse over widgets that appeared in the area under the original viewport.

**Comment by jhpedemonte** [comment]
-> M6/High

We have a few bugs dealing with widget creation/movement past the initial viewport.  This is a **usability** issue as users start creating more involved pages.  Increasing priority to high.

**Comment by JonFerraiolo** [comment]
I think this got fixed somehow. I'm seeing the crosshair all of the way to the bottom of the visual editor's canvas even when the page is scrolled. Reassigning to @jhpedemonte to review and hopefully close if he agrees the problem got solved somehow. (Actually not totally surprising. A good part of the visual editor logic has been rewritten in past few months).

We still have the issue about being able to drop a new widget off the bottom of the page: #1616. My thinking is leave that one open, but close this one.

**Comment by jhpedemonte** [comment]
Closing, since this specific issue seems to be fixed.

However, I'm seeing some oddities when the page is scrolled.  If I select a widget at the very bottom of a scrolled page, the bottom of the selection box shows above everything else, disconnected from the rest of the selection box.  Sometimes there is grey shading when hovering over a widget -- when the page is scrolled and the widget is towards the bottom, the grey shading extends up far beyond the bounds of the widget.

So still some things wrong.  Not sure if there are bugs for the above.

**Comment by JonFerraiolo** [comment]
> Sometimes there is grey shading when hovering over a widget -- when the page is scrolled and the widget is towards the bottom, the grey shading extends up far beyond the bounds of the widget.

Were you running on Firefox? I fixed some bugs there: fc1cf6aa20
