### ISSUE TITLE
dojox.mobileTextBox, ComboBox, TextArea inline edit reparents to previous DIV

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#741]
@billreed63, @jhpedemonte
- New HTML file
- Add a View
- Add a DIV
- Into the DIV, put a RadioButton and an &lt;label>
- Add a dojox.mobile.TextBox under the DIV
- Double-click on TextBox and change text to "aaa"

Result=> dojox.mobile.TextBox gets reparented and appears on screen between the RadioButton and the LABEL

Same thing with dojox.mobile.ComboBox and TextArea

**Comment by JonFerraiolo** [comment]
I have partial understanding of what's going wrong here. It looks like addChild() from _Container is getting called, and it is looking for a dijitWidget after which to put the revised ComboBox. But we really shouldn't be calling dijit to do the addChild in this case and instead should be doing it in Maqetta code because we need to re-inject the revised ComboBox as a child of a DIV, which isn't (of course) a Dijit widget. It might be that logic at widget.js:1552

```
        if (this.dijitWidget.addChild && child.dijitWidget) {
```

**Comment by JonFerraiolo** [comment]
I have a proposed fix, reassigning to Javier to review and decide if this fix is good.

First, change widget.js:1552 to:

```
        if (!this.acceptsHTMLChildren && this.dijitWidget.addChild && child.dijitWidget) {
```

Then change allowedChild for TabContainer, Accordion, and BorderContainer from "ANY" to "dijit.layout.ContentPane". The reason for this change is that although technically Dijit sometimes works with arbitrary content for these 3 widgets, we don't have all of the code in place within Maqetta to support these scenarios and right now only have code that supports ContentPane as children.

**Comment by jhpedemonte** [comment]
So the main issue here is that **dojox.mobile.View** inherits from **dijit._Container**, which specifies the `addChild()` API.  But `addChild` is only meant for container widgets that only accept Dijit widgets, not generic HTML elements.

So really, our code is right.  The problem is that View can accept both Dojo widgets and HTML elements -- this is a Dojo problem.  @peller emailed someone about the issue, so hopefully it will get resolved.

In the meantime, we need a workaround.  I'll investigate your proposal, Jon.

**Comment by jhpedemonte** [comment]
What happens inside of Dojo is that `addChild()` is called, which then calls `getChildren()`.  This only returns Dojo widgets -- in this case, it returns an array consisting only of dojox.mobile.RadioButton (even though it is nested inside of a DIV).  The code then calls `dojo.place()` relative to the RadioButton, instead of the DIV.

**Comment by jhpedemonte** [comment]
This is basically the same issue as #514.  However, the extra check I added there wasn't enough.  Followed Jon's lead and just replaced that check (for `child.dijitWidget`) with check for `! this.acceptsHTMLChildren`.

Still left to investigate is this:

> Then change allowedChild for TabContainer, Accordion, and BorderContainer from "ANY" to "dijit.layout.ContentPane". The reason for this change is that although technically Dijit sometimes works with arbitrary content for these 3 widgets, we don't have all of the code in place within Maqetta to support these scenarios and right now only have code that supports ContentPane as children.

**Comment by jhpedemonte** [comment]
Made `allowedChild` changes, as outlined above.  Opened #755 to track future changes.
