### ISSUE TITLE
Reconcile allowedChild, isContainer, isLayoutContainer

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#745]
@peller

@billreed63 and I are noticing that there is a 100% commonality between widgets that have isContainer:true and any value for allowedChild. Maybe we can get rid of isContainer as a redundant metadata property.

Not sure what isLayoutContainer does. Seems like there is some redundancy there, too.

**Comment by jhpedemonte** [comment]
Re: **isLayoutContainer**

This is a Dojo-ism.  See http://dojotoolkit.org/reference-guide/quickstart/layoutWidgetHierarchies.html.

Question is why do we define this in metadata.  But only for 2 widgets: `dijit.Toolbar` and `dijit.TitlePane`.  The latter doesn't seem to really need it defined in metadata, since the widget itself sets that property, and we check for that in various places in the code (which we should refactor, since it's Dojo-specific).

Not sure why `dijit.Toolbar` sets it in metadata, though.

Limited testing shows that it might not be necessary at all and can be removed.

**Comment by jhpedemonte** [comment]
Didn't notice anything during testing, so committed changes.  Closing this issue...
