### ISSUE TITLE
In Android silhouettes font color initially wrong for EdgetoEdgeList and RoundRectList

### ISSUE THREAD

**Issue by cindyskach** [maqetta/maqetta#767]
- new HTML file
- choose one of the Android silhouettes
- drop View onto canvas
- drop either EdgetoEdgeList or RoundRectList onto canvas

The font inside this widget is black on a black background at the start.
Switching between silhouettes switches the font color to the right color. You only see this issue if you start with an Android silhouette from the beginning.

Tested on Win/FF
lab14 build:
Version: Preview 2
Date: Jul 21, 2011 7:02:02 AM
Build: 09fca203d8fe228...

**Comment by JonFerraiolo** [comment]
Can be deferred to M3, but leaving as Priority Low for M2 to see if this is easy to fix.

**Comment by JonFerraiolo** [comment]
@billreed63

I think this is a fixable bug. The problem appears to be that we initially load iphone.css, even before choosing the first silhouette (android in this case). By switching devices, the logic to remove all of the old theme CSS files kicks in and gets rid of iphone.cass.

After studying this some more:
- After choosing Android silhouette, android.css gets added to HEAD for iframe
- When dropping a View, iphone.css gets added to HEAD for iframe even though Android silhouette is being used

**Comment by JonFerraiolo** [comment]
More info: tracing through Maqetta, the culprit is loadRequires:

```
        {
            "type": "javascript",
            "$text": "dojo.require('dojox.mobile.deviceTheme');"
        },
```

As a result of loading dojox.mobile.deviceTheme.js, the iphone.css stylesheet is added to the end of the HEAD for the user's iframe even though android.css is already there. I'm looking at deviceTheme.js and it seems to maintain it's own tables about which CSS files are loaded to determine whether to load a CSS file and not searching the HEAD to see if a CSS file is loaded.

Lots of ways to skin this cat, but not sure yet which is the best

**Comment by JonFerraiolo** [comment]
The logic in deviceTheme.js is determine which stylesheet to load based on this line of code:

```
var ua = (location.search.match(/theme=(\w+)/)) ? RegExp.$1 : navigator.userAgent;
```

**Comment by JonFerraiolo** [comment]
Adam, make sure to coordinate with Bill and Javier on this one. Bill knows how the iframe magically gets the right mobile theme. Javier probably put the dojo.require('dojox.mobile.deviceTheme') in the metadata.

**Comment by JonFerraiolo** [comment]
I played around with this some more. Really, what we want to have happen is that we put a dojo.require(...deviceTheme) in the model but don't load deviceTheme.js for the iframe within the page editor. I fooled around with loadRequires() and temporarily hacked my local copy to include this logic:

```
                    case "javascript":
                        if(r.$text.match('deviceTheme')){
                            break;
                        }
                        this.addJavaScript(null, r.$text, updateSrc, doUpdateModelDojoRequires);
                        break;
```

And the bug goes away. However, the above hack prevents deviceTheme.js both from getting added to the model and to the iframe. What would be better would be to add another parameter/flag to this.addJavaScript() that indicates whether to add a particular file to the page editor's iframe so that we could have addJavaScript only add deviceTheme.js to the model. 

We could put an ugly special case if statement into loadRequires like I have done above where loadRequires treats deviceTheme.js as a special case. Instead of putting dojox.mobile-specific code into a general purpose routine, it would be good if we could invent some sort of plugin mechanism and then solve deviceTheme.js issue with this plugin mechanism.

**Comment by billreed63** [comment]
Added CreateTool for mobile widgets, .mobile.MobileCreateTool.js overrides create() which is invoked after the widget is created. In MobileCreateTool.create I call context.setMobileTheme to fixes up the style sheets in the head ensuring that only the correct mobile theme style sheets are in play.

July 2011

**Comment by JonFerraiolo** [comment]
I like this solution!
