### ISSUE TITLE
File deletion gets confused when deleting multiple files

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#768]
- Create 2 new files ('file1.html', 'file2.html').
- Right click on file1.html and select delete resource.  Should be deleted fine.
- Right click on file2.html and select delete resource.  Notice that the dialog asks, "Are you sure you want to delete **./file1.html**?".  Pressing OK fails to delete file and throws errors in browser and server.

For some reason, the deletion code still thinks the now non-existent "file1.html" is still selected, even though the user can clearly see that "file2.html" is selected.

Adam, if this is an easy enough fix, please try to get it in for M2.

@JonFerraiolo

**Comment by JonFerraiolo** [comment]
I'm pretty sure this is a manifestation of an old problem where the context menu on the Files palette attempts to delete what it thinks is the currently selected file instead of the file under the mouse. If you select foo1.html by carefully clicking on it and making sure it stays highlighted after moving the mouse away, and the put the mouse over foo2.html and immediately bring up the context menu before doing a selection click (i.e., LMB), and choose delete command, then the popup says are you sure you want to delete foo1.html (even though action initiated while mouse is over foo2.html). My feeling about proper behavior:
- If nothing is selected, delete file under the mouse
- If 1 file is selected and mouse is over another file, delete the file under the mouse
- If 2 or more files are selected and mouse if over another file, then that's a toss up. Probably best to delete the selected files since that's probably what the user is trying to do.
