### ISSUE TITLE
Setting the 'back' property in Heading and erasing it causes icon to stay on Heading

### ISSUE THREAD

**Issue by cindyskach** [maqetta/maqetta#771]
- new HTML file
- drag mobile View onto canvas
- drag Heading onto canvas
- go to widget-specific for the Heading
- set the 'back' property to "home"
- press [enter] to see the change
- erase "home" so that the 'back' property is empty again

While the word, "home" disappears, the arrow stays in the Heading and only goes away while previewing in the browser or after closing and reopening the file.

Tested with Win/FF
lab14 build
Version: Preview 2
Date: Jul 22, 2011 7:02:13 AM
Build: d04db9aaeb52c27...

**Comment by jhpedemonte** [comment]
This is only an issue within the Visual Editor, since neither Preview nor closing/reopening show this issue. Late for M2, so setting for M3.

**Comment by JonFerraiolo** [comment]
I tried this experiment:
- New HTML File
- Add View
- Add Heading into View
- Set 'back' to a value
- Remove value from 'back' (note: same problem as listed above)
- set/change the 'id' on the Heading

Result=> arrow goes away

This is because changing the 'id' attribute triggers a ModifyCommand which causes the existing View element and children to get totally recreated from scratch (because that's how ModifyCommand does its magic). It looks like changing 'back' doesn't go through ModifyCommand. If we can somehow get 'back' to go through ModifyCommand, then maybe we will have a fix.

**Comment by waynevicknair** [comment]
The setting of the `back` attribute does indeed cause ModifyCommand to be called. However, `dojox.mobile.Heading` has logic in its `_setBackAttr` method to reuse the existing button DOM and is not checking the `back` string input parameter for empty string or null. When we set the `back` property in the properties pane to empty string, we must remove or hide the dojox widget's button DOM.

Otherwise, we might want to open a bug on dojox to correct the setter behavior. I'm sure they didn't intend for the button to display if it's label is empty.

**Comment by JonFerraiolo** [comment]
Your comment caused me to get into the debugger. I had just been in and around similar issues, so my interested was piqued.

ModifyCommand recreates the widget from scratch. The Dojo widget gets recreated at widget.js:491:

```
var widget = new c(data.properties, node, type, metadata, srcElement);
```

The "bug" is because Dojo interprets an empty string value differently than Maqetta. At widget.js:1223:

```
if(property || typeof property == "boolean"){
```

Therefore in the Maqetta logic, if "property" is an empty string, JS will evaluate to false and we drop into the logic that removes the property (including removing the attribute from the model). However, the Dojo logic treats an empty string as an actual value that is distinct from the default value (presumably, undefined in this case).

We really need to clean up the code around differentiating between empty string values vs "no value", but for time being what I try is:
- Before widget.js:491, I would remove all properties with an empty string value
- If there isn't already a bug for this, I would create a bug to clean up the code around differentiating between empty string values vs "no value"

**Comment by peller** [comment]
filed @waynevicknair's patch here: http://bugs.dojotoolkit.org/ticket/13776
