### ISSUE TITLE
Failed to find States.js script tag

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#780]
@jhpedemonte

Set to priority high just to investigate. This might be deferred or dropped entirely.

When I opened a theme created in M1 using M2 build, I see the following message in my console. Theme editor comes up correctly (after properly posting the warning), so my guess is that this warning is innocuous.

```
Failed to find States.js script tag.  States and dojox.mobile widgets may not work properly
```

**Comment by jhpedemonte** [comment]
I believe this always comes up with the Theme Editor.  The was based on a fix to make sure that States.js was added to page after dojo.js, so that it can properly patch dojo.parser.  I added a warning just to make sure nothing went wrong -- should have probably added something to prevent warning in case of Theme Editor.

I think the proper fix will be to redo States.js' patching of dojo, which is another bug.

**Comment by JonFerraiolo** [comment]
I'll leave this to you, Bill and Adam to decide about whether to close this bug or defer it.

**Comment by jhpedemonte** [comment]
Deferring to M3, priority low.  Just so we can track this warning and deal with it.

**Comment by jhpedemonte** [comment]
-> M6

**Comment by billreed63** [comment]
I don't see this error in the console now...
