### ISSUE TITLE
Draging in outline has issues if scrolling is involved

### ISSUE THREAD

**Issue by cindyskach** [maqetta/maqetta#797]
- new HTML file
- drop enough widgets onto the canvas so that the outline has a scroll bar
- drop a button onto canvas
- drop a toolbar onto the canvas so that it's now the last widget listed on the outline
- from the outline select the button (any button you have in the outline) and try to drag it down into the toolbar (all done within the outline)

I found it a little challenging because the browser window scrolls down rather than the outline palette.

Tested in Win/Chrome and Win/FF

**Comment by JonFerraiolo** [comment]
I run into this problem all of the time when I used Maqetta. I've classified this as Priority High for M3 and initially assigned to Adam so that someone is assigned, although someone else might ultimately get this bug and we might not be able to address it for M3. 

This might be at least partially a Dijit issue. My instincts are that we are exposing a flaw with DND in dijit.Tree when placed in containers that have particular characteristics, (e.g., BODY height:100%).

**Comment by peller** [comment]
I think it's because the height of the avatar, when extended below the bottom of the screen, immediately increases what 100% is of the body, permitting the entire screen to scroll.  This same problem can be observed in the Dijit themeTester demo.
