### ISSUE TITLE
Hide frame content during silhouette rotation

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#798]
Currently, when clicking on the silhouette rotation button (portrait <-> landscape), the internal frame stays visible during the rotation and doesn't look good.

A better solution would be to:
1. Before starting rotation, hide frame.
2. If possible, make internal part of silhouette gray (or a dark color), rather then the normal white.  This is purely for aesthetics and completely subjective.
3. At end of rotation, make frame visible again.

**Comment by peller** [comment]
...or rotate the content.  I remember trying both with little success.  I tried using a key-frame with two stops at 0 and 100 for opacity, but it didn't work.

**Comment by JonFerraiolo** [comment]
Yeah, rotating the content is likely to cause all sorts of issues.

@peller, @waynevicknair, @billreed63 - OK to snatch this one from me. Should only require a couple of lines of code change.

**Comment by peller** [comment]
what approach do you suggest?  Should I try key-frame again, or is there a better way to turn visibility off then back on?

**Comment by JonFerraiolo** [comment]
No, I'd avoid any more trickiness with animations. That's a potentially large time sink that might expose browser bugs. I would simply set display:none on the iframe before the animation starts and the restore the display property when the animation ends. Two lines of code for that part. I haven't studied the code closely here, so maybe it's not that simple.

**Comment by peller** [comment]
how do you know when it ends?  Just make a timer and hope they line up, I guess?

**Comment by JonFerraiolo** [comment]
Looking at the code, the animation seems to be done by an SVG <animateTransform> element. SVG provides an 'onend' attribute on all of its animation elements that allows you to define JS that gets called when the animation ends. I am assuming that all of the browsers we support also support the 'onend' attribute. There are actually two animateTransform elements, one to do a translate and the second to do a rotate, and these two animations are "additive" in the sense that the two transforms are added to each other geometrically. Best to put the 'onend' event only on the second one (which theoretically is processed after the first one). No need for the JS to be called twice. 

There is a small example of 'onend' inside of http://srufaculty.sru.edu/david.dailey/svg/smil_svg.html

One more thing. Note that there is a doAnimations parameter in the code. Only hide the iframe content if doAnimations is true. Otherwise, if doAnimations is false, the iframe content will get hidden and never restored because the animation will never run and therefore the onend callback will never get invoked.

Have a few more minutes here to look at code. If the onend callback function is an inner function within _silhouette_reset_size_position and therefore there is a closure, then I think the variable that needs to get display:none and then restored is 'ifr_body'

**Comment by JonFerraiolo** [comment]
Too late for this sort of a fix. Pushed to M4.

**Comment by JonFerraiolo** [comment]
Pushing to M5

**Comment by jhpedemonte** [comment]
`onend` works on Firefox, but not on Chrome.

**Comment by jhpedemonte** [comment]
Fixed, but had to use `setTimeout` for the duration of animation, instead of the `onend` event, which doesn't seem work on Chrome (WebKit?).

Now, is there any way to fix the clipping of the silhouette during the rotation?  I'm referring to how part of the silhouette becomes hidden at the beginning of the rotation.  Would be best if we saw the full device during rotation.

**Comment by JonFerraiolo** [comment]
I wonder if the clipping is because of the overflow:hidden on silhouette_div_container:

```
<div class="silhouette_div_container" style="position: relative; overflow-x: hidden; overflow-y: hidden; margin-left: 0px; margin-top: 0px; width: 747.8541030511408px; height: 385.56449984131103px; ">
  <span class="silhouetteiframe_object_container">
    <object class="silhouetteiframe_object" data="app/preview/images/iphone.svg" type="image/svg+xml" onload="event.target.parentNode.parentNode._silhouetteiframe.svgloadhandler(event.target)" style="overflow-x: hidden; overflow-y: hidden; width: 749px; height: 387px; "></object>
  </span>
  <iframe class="silhouetteiframe_iframe" style="overflow-x: hidden; overflow-y: hidden; margin-left: 134.33444735639924px; margin-top: 31.056868345884148px; width: 480px; height: 320px; "></iframe>
</div>
```

I'm focused on other assignments, so I'm not going to fool around with this right now, but if there was someone out there who was totally obsessed with this area of the UI, maybe he/she would investigate :-)

**Comment by jhpedemonte** [comment]
Closing and opening new bug for clipping during rotation.
