### ISSUE TITLE
Documented HorizontalSlider functionality in Untested Widgets

### ISSUE THREAD

**Issue by cindyskach** [maqetta/maqetta#816]
HorizontalSlider and its two children, HorizontalRule and HorizontalRuleLabels, can now be dropped onto the canvas, edited and previewed in the browser correctly (aside from any work with the Container property).

I had to add the following block of code to widget.js to assure that the Labels property (taken in as a string but treated as an array) was handled properly. There was also a dependency between Labels, Count and NumericMargin that is addressed in HorizontalRuleLabelsHelper:

```
var helper = davinci.ve.metadata.queryDescriptor(type, "helper");
    if (helper) {
        var myHelper;
        try {
            dojo["require"](helper);
        } catch(e) {
            console.error("Failed to load helper: " + helper);
            console.error(e);
        }
        var aClass = dojo.getObject(helper);
        if (aClass) {
            myHelper  = new aClass();
        }
        var obj = dojo.getObject(helper);
        myHelper = new obj();
        if(myHelper.preProcessData)
            data =  myHelper.preProcessData(data);

    }
```

There is still one known issue:
- The Container property for HorizontalRule and HorizontalRuleLabels can be either 'bottomDecoration' or 'topDecoration.' Currently only 'bottomDecoration' works.
  - After changing Container to topDecoration, the canvas doesn't display it correctly but it previews correctly.
  - Closing and reopening the file makes it display correctly in the canvas but whatever has the property will no longer show up in the Outline.
  - I'm still working on this, but I'm thinking this has to do with how we currently generate the outline

Other things to note:
- HorizontalRule and HorizontalRuleLabels might need their own icons once this widget is completed

**Comment by aerwin** [comment]
Ran the following by @peller this evening on ST, and he agreed to help me look at it tomorrow...

I suspect the issue with the outline (and maybe more likely the underlying model) is because `topDecoration` causes the element to be rendered above the slider at runtime. So, the runtime DOM doesn't really reflect the HTML structure.

For example, below I've set `topDecoration` on the HorizontalRuleLabels (a child of the HorizontalSlider):

``` html
<div dojoType="dijit.form.HorizontalSlider" style="width: 200px;">
   <div dojoType="dijit.form.HorizontalRule" style="height:5px;" container="bottomDecoration"></div>
   <ol dojoType="dijit.form.HorizontalRuleLabels" container="topDecoration" labels="50%" style="height: 20px;"></ol>
 </div>
```

In the runtime DOM, a table is used to layout the slider and the labels get placed in a TR _before_ the TR containing the slider:

``` html
<table class="dijit dijitReset dijitSliderH dijitSlider" cellspacing="0"
    cellpadding="0" border="0" rules="none"
    data-dojo-attach-event="onkeypress:_onKeyPress,onkeyup:_onKeyUp"
    id="dijit_form_HorizontalSlider_0" style="width: 200px;"
    widgetid="dijit_form_HorizontalSlider_0">
    <tbody>
        <tr class="dijitReset">
            <td class="dijitReset" colspan="2"></td>
            <td data-dojo-attach-point="topDecoration"
                class="dijitReset dijitSliderDecoration dijitSliderDecorationT dijitSliderDecorationH"><div
                    class="dijitRuleContainer dijitRuleContainerH dijitRuleLabelsContainer dijitRuleLabelsContainerH"
                    id="dijit_form_HorizontalRuleLabels_0" style="height: 20px;"
                    widgetid="dijit_form_HorizontalRuleLabels_0">
                    <div class="dijitRuleLabelContainer dijitRuleLabelContainerH"
                        style="left: 50%;">
                        <div class="dijitRuleLabel dijitRuleLabelH">50%</div>
                    </div>
                </div></td>
            <td class="dijitReset" colspan="2"></td>
        </tr>
        <tr class="dijitReset">
            <td
                class="dijitReset dijitSliderButtonContainer dijitSliderButtonContainerH"><div
                    class="dijitSliderDecrementIconH" style=""
                    data-dojo-attach-point="decrementButton">
                    <span class="dijitSliderButtonInner">-</span>
                </div></td>
            <td class="dijitReset"><div
                    class="dijitSliderBar dijitSliderBumper dijitSliderBumperH dijitSliderLeftBumper"
                    data-dojo-attach-event="press:_onClkDecBumper"></div></td>
            <td class="dijitReset"><input data-dojo-attach-point="valueNode"
                type="hidden" value="68.45637583892618">
            <div class="dijitReset dijitSliderBarContainerH" role="presentation"
                    data-dojo-attach-point="sliderBarContainer">
                    <div role="presentation" data-dojo-attach-point="progressBar"
                        class="dijitSliderBar dijitSliderBarH dijitSliderProgressBar dijitSliderProgressBarH"
                        data-dojo-attach-event="press:_onBarClick"
                        style="width: 68.45637583892618%;">
                        <div class="dijitSliderMoveable dijitSliderMoveableH">
                            <div data-dojo-attach-point="sliderHandle,focusNode"
                                class="dijitSliderImageHandle dijitSliderImageHandleH"
                                data-dojo-attach-event="press:_onHandleClick" role="slider"
                                valuemin="0" valuemax="100" aria-valuemin="0"
                                aria-valuemax="100" tabindex="0"
                                aria-valuenow="68.45637583892618"></div>
                        </div>
                    </div>
                    <div role="presentation" data-dojo-attach-point="remainingBar"
                        class="dijitSliderBar dijitSliderBarH dijitSliderRemainingBar dijitSliderRemainingBarH"
                        data-dojo-attach-event="press:_onBarClick"
                        style="width: 31.543624161073826%;"></div>
                </div></td>
            <td class="dijitReset"><div
                    class="dijitSliderBar dijitSliderBumper dijitSliderBumperH dijitSliderRightBumper"
                    data-dojo-attach-event="press:_onClkIncBumper"></div></td>
            <td
                class="dijitReset dijitSliderButtonContainer dijitSliderButtonContainerH"><div
                    class="dijitSliderIncrementIconH" style=""
                    data-dojo-attach-point="incrementButton">
                    <span class="dijitSliderButtonInner">+</span>
                </div></td>
        </tr>
        <tr class="dijitReset">
            <td class="dijitReset" colspan="2"></td>
            <td data-dojo-attach-point="containerNode,bottomDecoration"
                class="dijitReset dijitSliderDecoration dijitSliderDecorationB dijitSliderDecorationH"><div
                    class="dijitRuleContainer dijitRuleContainerH"
                    id="dijit_form_HorizontalRule_0" style="height: 5px;"
                    widgetid="dijit_form_HorizontalRule_0">
                    <div class="dijitRuleMark dijitRuleMarkH" style="left: 0%;"></div>
                    <div class="dijitRuleMark dijitRuleMarkH" style="left: 50%;"></div>
                    <div class="dijitRuleMark dijitRuleMarkH" style="left: 100%;"></div>
                </div></td>
            <td class="dijitReset" colspan="2"></td>
        </tr>
    </tbody>
</table>

```

**Comment by aerwin** [comment]
@JonFerraiolo @jhpedemonte 

Regarding usability for the designer trying to use horizontal/vertical sliders, I had some ST discussion with @JonFerraiolo this morning, but wanted to capture my latest thoughts below...

There are two companion elements to HorizontalSlider that can be added as children (HorizontalRule and HorizontalRuleLabels). I believe the typical case would be represented by something like following:

``` html
<div dojoType="dijit.form.HorizontalSlider" style="width: 200px;">
   <div dojoType="dijit.form.HorizontalRule" style="height:5px;" container="bottomDecoration"></div>
   <ol dojoType="dijit.form.HorizontalRuleLabels" container="bottomDecoration" labels="50%" style="height: 20px;"></ol>
 </div>
```

And, would display something like this:

![Slider with single set of labels](http://i.imgur.com/OhFIY.jpg)

But, from a usability perspective, I hate for designer to have to worry these children as separate entities. And, since they can't be dropped into any other parents, it seems a waste to have them on the widget palette.  

@JonFerraiolo and I had briefly discussed coming up with a smart input dialog. I envisioned something simple like the really rough sketch below:

![Smart input example](http://i.imgur.com/1o4Do.jpg)

But, then it occurred to me later in the day while looking at the docs/sample code for HorizontalSlider that there are legitimate cases where a designer might want multiple sets of labels/rules. Obviously, the smart input proposal above doesn't address this. For example:

![Slider with multiple sets of labels](http://i.imgur.com/QnaLS.jpg)

If we want to allow the designer to build things like that (or even more complex sliders), then we're probably back to just having the separate entities for HorizontalRule and HorizontalRuleLabels on the palette (and no smart input).

Thoughts? I tend to believe the case with a single set of labels/rules covers 75-80% of the situations. So, guess the question is do we think the added simplicity is worth less flexibility in this case?

**Comment by JonFerraiolo** [comment]
Here are some thoughts for consideration. I don't have great confidence in these suggestions. I expect we will continue to iterate.

One way to do would be to only support the 80/20 approach by defining pseudo properties that appear in the widget-specific section of props palette for h-slider and v-slider widgets, where the first half of the widget-specific section lists properties having to do with the rule (e.g., container for the rule) and the second half lists properties for the labels (e.g., container for the labels). From an implementation perspective, I suspect this would be a certain amount of work, mostly in creating helper functions for getPropertyValue and setPropertyValue, which would map between the pseudo properties in the widget-specific section and the actual HTML markup. I'm not thrilled with this idea.

A second approach would be to create a widget-specific SmartInput control, in same direction as @aerwin proposed up above.. I was hoping to find a way to avoid this because it represents a certain amount of work, but it's probably roughly about the same effort as the option in the previous paragraph, much better from a user perspective, and would provide us the UI flexibility that our UI could convey the richness of options within dijit sliders, and also allow full and complete round-tripping between markup and our UI. 

What I'm thinking is that in this case it might be better to go to a near 100% solution rather than 80/20 approach. I'm thinking that when we parse the markup for a slider, we have the capacity for showing any number of rules and rulelabels in our SmartInput UI, using the UI we have now for editing gradient stops in the Background dialog as a partial model. I'm thinking that our default slider has one rule and one rulelabel, which would cause the SmartInput to look something like this (using ASCII art):

```
Rule:  [X]
 Posiiion: [top|bottom] (maps to 'container' property)
 (other rule properties)
Label row: [X]
  Position: [top|bottom] (maps to 'container' property)
  (other rule properties)
[Add rule] [Add label row]
```

Is this comprehensible?

**Comment by aerwin** [comment]
Thanks for the thorough feedback! Yes, that's comprehensible. I think the last proposal has promise. Let me spend some time exploring that today.

**Comment by aerwin** [comment]
@peller 

As for the outline issue we discussed this afternoon... after spending time in the debugger, the bottomline is I believe there is a bug (or design flaw) with `dijit.form.HorizontalSlider` that keeps its `getChildren` function from returning elements targeted for `topDecoration`.

From the template of `HorizontalSlider` you can see there are two main attach points. One is for `topDecoration` and the other is `containerNode,bottomDecoration`. 

``` html
<table class="dijit dijitReset dijitSlider dijitSliderH" cellspacing="0"
        cellpadding="0" border="0" rules="none"
        data-dojo-attach-event="onkeypress:_onKeyPress,onkeyup:_onKeyUp">
    <tr class="dijitReset">
        <td class="dijitReset" colspan="2"></td>
        <td data-dojo-attach-point="topDecoration"
            class="dijitReset dijitSliderDecoration dijitSliderDecorationTdijitSliderDecorationH"></td>
        <td class="dijitReset" colspan="2"></td>
    </tr>
    LONG <TR> BLOCK REMOVED FOR CLARITY
    <tr class="dijitReset">
        <td class="dijitReset" colspan="2"></td>
        <td data-dojo-attach-point="containerNode,bottomDecoration"
            class="dijitReset dijitSliderDecoration dijitSliderDecorationBdijitSliderDecorationH"></td>
        <td class="dijitReset" colspan="2"></td>
    </tr>
</table>
```

This probably isn't bad by itself, but it's directly in conflict with the design of the `_Container` mixin. The description of `_Container` pretty clearly states that it's not appropriate when contained widgets are not "directly below this.containerNode" and also says that calls to addChild "wouldn't make sense" in this situation.

``` javascript
                // summary:
        //      Mixin for widgets that contain a set of widget children.
        // description:
        //      Use this mixin for widgets that needs to know about and
        //      keep track of their widget children. Suitable for widgets like BorderContainer
        //      and TabContainer which contain (only) a set of child widgets.
        //
        //      It's not suitable for widgets like ContentPane
        //      which contains mixed HTML (plain DOM nodes in addition to widgets),
        //      and where contained widgets are not necessarily directly below
        //      this.containerNode.   In that case calls like addChild(node, position)
        //      wouldn't make sense.
```

@peller, would you be able to bring this up with your Dojo contacts?

**Comment by peller** [comment]
Doug said that indeed the inner widgets get moved around at `startup()` time.  Following the strict meaning of `getChildren()` I guess it's doing the right thing, just not what we expect!  One could argue over what the proper behavior is, whether HorizontalSlider should override `getChildren`.  One option is for us to monkey-patch `getChildren`.  Another is to explore using `findWidget()` in dijit/_base/manager to find child widgets instead of `getChildren()`.  That would possibly bring out other children in other widgets which aren't under containerNode -- may be a bad thing.

**Comment by JonFerraiolo** [comment]
@jhpedemonte 

ScrollableView reparents its subnodes depending on various circumstances. We created some helper functions to deal with that. I don't remember the details, but I believe the way to go in this case is to define helper functions that provide an API to Maqetta that looks like Maqetta's view of the world and deal with widget-specific idiosyncracies under the hood.

**Comment by aerwin** [comment]
Thanks @peller and @JonFerraiolo ! In the end, I took @JonFerraiolo 's suggestion to look at ScrollableViewHelper and I was able to create a HorizontalSpinnerHelper with my own getChildren function to solve the problem.

**Comment by jhpedemonte** [comment]
The issue with `ScrollableView` had to do specifically with setting the `fixed` property on `Heading` (while in the presence of ScrollableView).  The fix I implemented was to support a declarative property which says that if the given property is changed, then refresh the whole VE iframe.  See `refreshFromSource` in _dojo_1_7/WebContent/metadata/widgets.json_.

Not sure if that will work with this particular situation.  Tony, we can discuss this later today.

**Comment by aerwin** [comment]
Yes, as part of the work I did last week, I started using the `refreshFromSource` property. And, I think I'm on pretty good shape here. Now, mainly need to finish the smart input work.

**Comment by aerwin** [comment]
@JonFerraiolo @jhpedemonte 

I've pushed out my branch containing the horizontal and vertical slider changes (which includes smart input w/ preview). Would either of you like to review before I merge into master?

Also, there are a few open issues that I'll look to get resolved in one or more feature/problem reports. But, I wanted to get what I have in front of folks for discussion (since there was some debate on how smart input for sliders should work in the first place) and because I want to get going on the higher priority #1638 (since it relates to AMD).

Outstanding issues include:
- Sliders are active on the canvas in that users can slide them, etc.. I think this needs to be restricted like other widgets (e.g., I can't check a checkbox on the canvas), but I don't see how it was restricted for those other widgets.
- Not all properties for `HorizontalRule`/`VerticalRule` get passed through (e.g., `count` doesn't make it to my smart input code, so doesn't get reflected in preview and gets lost on OK). However, this is _not_ an issue for `HorizontalRuleLabels`/`VerticalRuleLabels`.
- `refreshFromSource` issues
  - would be nice if a property marked as `refreshFromSource` gets changed that the widget gets re-selected
  - need to add `refreshFromSource` to some other properties on rule labels (like `count` and `labels`), but `preProcessData` in my helper for `HorizontalRuleLabels`/`VerticalRuleLabels` gets bypassed in that case
  - Outline
    - Re-ordering slider children needs to do equivalent of `refreshFromSource`
- Smart input only accepts input for type (rule or labels) and `container`, but might be nice to include some other properties like `count`, `constraints`, etc.
- Helper for `HorizontalRuleLabels`/`VerticalRuleLabels` should possibly take some other things (like `constraints`) into account in `preProcessData`

**Comment by aerwin** [comment]
FYI... I've opened a few issues to track the misc outstanding items I listed on Feb 6. These include #1726, #1727, and #1728.. (Also, added a couple items to #1716 that Jon had opened.)
