### ISSUE TITLE
Editing widget loses state

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#843]
Open Sample1.html and double click on the **New** button. Edit the text to something else.  Run the web app in Preview, notice that clicking that button (which previously was labeled "New") doesn't cause any action.  Back in the Visual Editor, notice that there is no longer a state action attached to the button (**Properties->Events**).

I'm thinking this has to do with the **destroy/recreation** process that happens when changing widget properties.

@JonFerraiolo

**Comment by JonFerraiolo** [comment]
@peller

Yikes! Likely this bug has been in there forever. Assigning to me for time being because I suspect I know where to fix. My guess is that we need to stash the dvStates attribute before doing widget changes and then restore after it. I've fixed a similar bug recently where some other widget properties were getting dropped with a change.

**Comment by JonFerraiolo** [comment]
We deal with on\* attributes in a special way in the page editor because we don't want UI events (e.g., click, mouseover) defined on the page content to be active while the page editor is running. The on\* attributes are in the model but not on the DOM elements in the iframe in the page editor. I'll bet this has something to do with this bug, but I don't yet see the exact reason why things are broken.

**Comment by JonFerraiolo** [comment]
More research into this bug:
- Doesn't have anything to do with states. If you create a new HTML file, add a button, enter "console.log('aaa')" for onclick on the button, and then change the button label, the onclick property gets wiped out.
- Doesn't have anything to do with buttons or Dojo. If you create a DIV, add onclick property of "console.log('aaa')", and bring up smart input to add text inside of DIV, the onclick property gets wiped out.

I'm 95% certain this has to do with how we have special logic to deal with the on\* event attributes, where they are in the model but not in the HTML DOM that shows in the canvas. I think the fix is to update getData or _getData to include special logic to pull the on\* event attributes out of the model and stuff into the "data" object, and then upon creating the replacement widget, make sure the on\* event attributes are added back into the model but not included in the HTML DOM that shows in the canvas.

For the logic that strips out the on\* event attributes from the DOM shown in the canvas, open up Context.js and search for "event attributes".

**Comment by JonFerraiolo** [comment]
@billreed63, @peller, @waynevicknair

This might be a good one for one of you to pick up.
