### ISSUE TITLE
Palette Icon text is mispelled

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#846]
@jmockler @jinsil

The Dojo Container and Controls icons are mispelled "digit" -- the project name is "Dijit"

Putting text in the icon makes it hard to read and is redundant with the adjoining label.  I think it would be more informative to have a generic "widget" icon used by this and other libraries (as opposed to HTML tags) and use the name "Dijit" in the label instead of Dojo: "Dijit Container", "Dijit Controls"

**Comment by jhpedemonte** [comment]
Huh, I never noticed that. Assigning to @jmockler.

Here's the icon in question:
![Dijit icon](http://i.imgur.com/fqiDH.png)

Used for both "Dojo Containers" and "Dojo Controls" sections in the Widgets palette.

Janet, do you think we could get updated icon within the next week or two?

@JonFerraiolo

**Comment by jmockler** [comment]
@jhpedemonte - @jinsil is going to provide a new one via this Issue. Can't believe we missed that one.. 8-)

**Comment by peller** [comment]
@jmockler: should we consider unifying the text on "Dijit" or "Dojo"?  Then we may not need the text in the icon at all.

**Comment by jinsil** [comment]
The icon was delivered thru Request 7531. Please let me know if you need the same icon.

**Comment by jmockler** [comment]
will clarify with @jinsil

**Comment by jmockler** [comment]
@peller - I understood when we created the icon that we wanted to distinguish between "Dijit" or "Dojo" objects. Is that still the case?

**Comment by jmockler** [comment]
@jhpedemonte - sent via email

**Comment by JonFerraiolo** [comment]
Had a discussion with Adam. Background is that we have widget collections. Right now we have Dojo Containers, Dojo Controls, HTML, Dojo Mobile, YUI, jQuery, and then various company-specific icons via extensibility.

Another bit of background is that we might do a major makeover for the Widgets palette in the coming months.

A 3rd bit of background is that there is visual inconsistency now where the "Dijit" widget icon has "digit" going horizontally and the Dojo Mobile icon has "dojo" going vertically.

4th comment: My guess is that Maqetta users are more likely to think of Dojo's widget libraries are being "Dojo" and the term "dijit" is much less likely to be meaningful to them.

First question: Do we need different icons for different widget collections: presumed answer is yes. 

Second question: If so, what's the best visual strategy for helping user distinguish between widget collections? Adam points out that we have textual labels on the widget collections, so it isn't that important to put a string into the icon itself (e.g., "dojo" or "dijit"), and text strings in icons tend to cause trouble (e.g., our misspelling case). Options that come to mind: (1) similar approach to what we have now where we put the word "dojo" or "dijit" into the icon, (2) avoid the "dojo" vs "dijit" branding issue by having only the letter "d" in the icon ("d" for "dojo" and "dijit"), (3) come up with (pretty much) random graphics without any text for any Dojo widget collection icons

I'd like a good solution for this by the time we do the Widget palette makeover. OK with me if we do a temporary patch by fixing the current icon to say "dijit" instead of "digit" so long as we come up with a consistent approach to these icons in the next couple of months.

**Comment by peller** [comment]
FWIW, I vote for (3) and put whatever descriptive information we need into the label.  I think a single letter in the icon (2) would be cryptic, and likely to have collisions.

Note also that "Dojo" is a toolkit which encompasses Dijit as well as other widgets, so it's not really an either-or situation.  Dijit is the family of icons which is supposed to carry with it consistency as well as guarantees of themeing, i18n, a11y, etc.  Other widgets presently get lumped into a bucket called "DojoX" but over time they are likely to develop their own independent subprojects and brands.  Like widgets based on JQuery, they will happen to use Dojo, but will hopefully get their own community and branding going.

**Comment by jmockler** [comment]
We need to avoid overloading the palette object icons. The busier the 16x16 iconography gets, the harder it is for users to distinguish between them. I also think using the letter d on its own won't help users identify it as a dojo collection of widgets. That being said, there is an overlap between widgets used for mobile design vs. web design.. right? 

Why can't we group the widgets by the kind of UI that its relative to? Mobile design, Web Design, etc. A button is a button, and the context of the button determines the form it takes. 

Also shouldn't the strategy for the icons be affected by the way objects are organized in the widget palette view?

**Comment by peller** [comment]
Yes, the strategy is important.  It's unclear whether the icon represents the "brand", the purpose, the technology (mobile) or all the above.   We've gone back and forth on the grouping many times... if successful with our metadata, the theory goes, implementation should be irrelevant.  But there's still a long way to go before the underlying libraries are transparent, and there are issues of consistency across the widgets, both in terms of programming and the design.

**Comment by JonFerraiolo** [comment]
> Also shouldn't the strategy for the icons be affected by the way objects are organized in the widget palette view?

That's why I suggested the option to simply replace the "g" with a "j" in the icon for now and then readdress the icon strategy once we do the widget palette makeover.

**Comment by jhpedemonte** [comment]
Committed updated icon.  Should we just close this and come back to the larger issues when we do Widgets palette makeover?

**Comment by JonFerraiolo** [comment]
Yeah, closing this issue. We addressed the bug completely. There is a bunch of other things about what to do when we do a widget palette makeover. That discussion is retained here for posterity.
