### ISSUE TITLE
Paste broken by data.data changes

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#876]
Cut/copy/paste (ContextActions.js) depends on the old "data" instead of the new "data.data" so we are crashing now with a paste action. Could you please fix?

**Comment by billreed63** [comment]
I backed out the changes I made in #837, and change the code in CreateTool that was throwing the original exception. The root cause is that the data that is passed to the CreateTool at creation can be a object or an array of objects. The array of objects can be a complex object that is dropped from the palette of a paste of multiple objects.

I changed the code CreateTool that invokes 'onFirstAdd' callback, to deal with either a single data object or an array of data objects and invoke onFirstAdd on all object libraries that are in the array
