### ISSUE TITLE
Focus ring needs to be reset on page resize

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#894]
Drop a BorderContainer on the page (hit ok for the dialog you get)
Select the center element
Now resize the visual editor using the splitter OR choose a split source/visual view from the toolbar

Result: you'll see that the selection (focus ring) still represents the old position and no longer aligns with the center element.

---

**[Updated 2012-03-14](https://github.com/maqetta/maqetta/issues/894#issuecomment-4497916):**

What's left?:

> just the silhouette or orientation change part

**Comment by JonFerraiolo** [comment]
Set this to Priority-Low for M3, meaning nice to fix.

Note that I added a new routine in Context.js: updateFocus(). I broke it out from the select() function for cases where the selection doesn't need to change (which has side effects) and all that needs to be done is recompute the focus box. The trick is to figure out how to establish an appropriate event listener in order to make the call to updateFocus. I suggest grep'ing for updateFocus, including dojo_1_7, maybe it will spur some ideas.

**Comment by peller** [comment]
I was thinking of just adding a resize event handler on the iframe or document (might be some browser quirks here) and resetting the selection.

**Comment by peller** [comment]
see also #28

**Comment by peller** [comment]
also on silhouette or perhaps even theme changes

**Comment by peller** [comment]
focus box not resize on silhouette change or orientation change - see #798

**Comment by jhpedemonte** [comment]
@peller: There's a lot of commits here -- how much is left?

**Comment by peller** [comment]
just the silhouette or orientation change part

**Comment by jhpedemonte** [comment]
-> M6

**Comment by peller** [comment]
-> M7

**Comment by JonFerraiolo** [comment]
This should be easy to fix. Just add 

```
setTimeout(function(){
   context.updateFocusAll();
},somenumber);
```

at the end of actions that change device (ChooseDeviceAction) or orientation RotateDeviceAction). The setTimeout is because of browser quirks where browser geometry calculations are sometimes not immediately available and because updateFocusAll is a safe operation to happen asynchronously.

**Comment by jhpedemonte** [comment]
I'm fine with Jon's suggested fix, as long as it's properly documented why we need it in a setTimeout, etc.

**Comment by peller** [comment]
-> M8

**Comment by JonFerraiolo** [comment]
Closing.

At this point, all of the cases listed above have been addressed. Switching devices and resizing the window all cause the focus chrome to get recomputed. Switch themes addresses this by turning off selection.

If I'm wrong and there are still redraw issues remaining, please create a new bug that targets the specific problem.

**Comment by peller** [comment]
somehow the orientation and device issues did get fixed.  thanks!
