### ISSUE TITLE
TitlePane doesn't really work (M3, M2, ...)

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#940]
@peller, @jhpedemonte

We probably won't have time for this fix, but TitlePane is basically unusable. Three options for M3:
- 1) Leave it as is in its current pretty-much-broken state. (Same state as with M2 and M1)
- 2) Move TitlePane into Untested until it actually works
- 3) Fix TitlePane before we ship M3

Here is how to reproduce at least one major problem with TitlePane:
- New HTML File
- Add a TitlePane
- Drop a Button into TitlePane's content area
- Go into split pane and look at source code

Result=> So far so good. Button is a child of TitlePane
- Double click on TitlePane's title bar and change the text for the title, save, close, and reopen
- Go into split pane and look at the source code

Result=> Button is now stored within the 'content' attribute of the TItlePane's DOM node. As a result, we get runtime exceptions at Context.js:156 because somehow or other we are getting a davinci.ve.ObjectWidget object and widget.type is null.

**Comment by jhpedemonte** [comment]
I'm fine with moving to "untested" and fixing this in M4.

**Comment by peller** [comment]
+1.  I'm happy to look at this in M4.

**Comment by JonFerraiolo** [comment]
I moved TitlePane temporarily to "Untested" with 9822c7c34df858556d8a111fdca2a6353214e468 and pushed this bug to M4

**Comment by billreed63** [comment]
TitlePane has a "content" property where content can be stored for the title pane, because of this property any change to the titlePane was putting all the children in the "content" property. I noticed several properties in TitlePane that where commented out with 

```
 /* FIXME: Temporarily comment out some properties that result in really ugly attributes in generated source code or are broken.
```

So I commented out the "content" property as well, I think this is the desired approach for us if we did put content in this property it would hide the children from the outline palette and not allow editing of the child widgets..

**Comment by billreed63** [comment]
fixed with above commit
