### ISSUE TITLE
Can't drop absolute layout widget into container

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#995]
create html file
change layout to absolute 
drag TabContainer drop
select Tab one
Drag drop button

Notice that button is sibling of TabContainer instead of child of Tab one container. The user must drag the button to Tab one container in the outline palette.

**Comment by JonFerraiolo** [comment]
Not a bug! This is by design. I can explain in more detail, but basically the approach I am pushing for absolute positioning is that by default new widgets are added as last child of BODY so that Maqetta will work like common drawing tools (PowerPoint, Illustrator, Photoshop, etc) where the objects at the bottom of the document render on top of the earlier objects.

One thing I hope to add in M4 is a provision where users can choose a parent widget upon dropping. I have this programmed in prototype form waiting to be included into the code base. The trick here is when to post the dialog to choose the parent: always when there are more than one choice? when a preference is set? if user holds down a modifier? See #708
